from __future__ import annotations

from typing import Protocol

from storage_durable.domain.failure import StorageFailure

class FileSystemPort(Protocol):
    def read(self, path: str) -> bytes | None: ...
    def write(self, path: str, data: bytes) -> None: ...
    def append(self, path: str, data: bytes) -> None: ...
    def remove(self, path: str) -> bool: ...
    def rename(self, source: str, target: str) -> None: ...
    def exists(self, path: str) -> bool: ...
    def size(self, path: str) -> int | None: ...
    def truncate(self, path: str, length: int) -> None: ...
    def sync_file(self, path: str) -> None: ...
    def sync_directory(self, path: str) -> None: ...
    def list_directory(self, path: str) -> tuple[str, ...]: ...
    def make_directories(self, path: str) -> None: ...
