// CODEGEN-BEGIN
//! Emit a Python client: one method per operation, with pydantic-validated
//! sync and async responses. The generated default runtime speaks h2c for
//! http:// and ALPN h2 for https://, while callers may inject any httpx-like
//! object with `request`.

use crate::emit::py::pymap;
use crate::ir::names::{to_snake, NameRegistry};
use crate::ir::openapi::RefOr;
use crate::ir::operations::{OperationIR, ParamIR};
use crate::ir::typemap::TypeMap;
use crate::{FileBearerAuth, PythonTarget};

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

pub fn emit(
    ops: &[OperationIR],
    tm: &TypeMap,
    target: Option<PythonTarget>,
    auth: Option<&FileBearerAuth>,
) -> String {
    let mut out = String::from(HEADER);
    out.push_str("from __future__ import annotations\n");
    out.push_str("import ssl\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from urllib.parse import urlsplit\n");
    if auth.is_some() {
        out.push_str("from ipaddress import ip_address\n");
        out.push_str("from pathlib import Path\n");
    }
    if target.is_some() {
        out.push_str("from typing import Any, Literal, Mapping, Protocol, Self\n");
    } else {
        out.push_str("from typing import Any, Literal, Mapping, Optional, Protocol\n");
    }
    out.push_str("from pydantic import BaseModel\n");
    out.push_str("from .h2c_runtime import AsyncH2CClient, H2CClient\n");
    out.push_str("from .models import *  # noqa: F401,F403\n\n\n");

    if let Some(auth) = auth {
        out.push_str(&format!(
            "_FILE_BEARER_TOKEN_PATH = {}\n",
            python_literal(
                auth.token_path()
                    .to_str()
                    .expect("FileBearerAuth validates UTF-8 paths")
            )
        ));
        out.push_str(&format!(
            "_FILE_BEARER_HOSTNAME_SUFFIX = {}\n",
            python_literal(auth.hostname_suffix())
        ));
        let schemes = auth
            .schemes()
            .map(|scheme| python_literal(scheme.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "_FILE_BEARER_SCHEMES = frozenset(({schemes},))\n\n\n"
        ));
        out.push_str("def _has_authorization(headers: Mapping[str, Any]) -> bool:\n");
        out.push_str(
            "    return any(str(name).casefold() == \"authorization\" for name in headers)\n\n\n",
        );
        out.push_str("def _is_dns_hostname(host: str) -> bool:\n");
        out.push_str("    if not host or len(host) > 253 or host.endswith(\".\"):\n");
        out.push_str("        return False\n");
        out.push_str("    try:\n");
        out.push_str("        ip_address(host)\n");
        out.push_str("        return False\n");
        out.push_str("    except ValueError:\n");
        out.push_str("        pass\n");
        out.push_str("    for label in host.split(\".\"):\n");
        out.push_str("        if not (1 <= len(label) <= 63):\n");
        out.push_str("            return False\n");
        out.push_str(
            "        if not ((\"a\" <= label[0] <= \"z\") or (\"0\" <= label[0] <= \"9\")):\n",
        );
        out.push_str("            return False\n");
        out.push_str(
            "        if not ((\"a\" <= label[-1] <= \"z\") or (\"0\" <= label[-1] <= \"9\")):\n",
        );
        out.push_str("            return False\n");
        out.push_str("        if not all((\"a\" <= char <= \"z\") or (\"0\" <= char <= \"9\") or char == \"-\" for char in label):\n");
        out.push_str("            return False\n");
        out.push_str("    return True\n\n\n");
        out.push_str(
            "def _file_bearer_headers(base_url: str, headers: dict[str, Any]) -> dict[str, Any]:\n",
        );
        out.push_str("    if _has_authorization(headers):\n");
        out.push_str("        return headers\n");
        out.push_str("    try:\n");
        out.push_str("        parsed = urlsplit(base_url)\n");
        out.push_str("        host = parsed.hostname or \"\"\n");
        out.push_str("    except ValueError:\n");
        out.push_str("        return headers\n");
        out.push_str("    if (\n");
        out.push_str("        parsed.scheme not in _FILE_BEARER_SCHEMES\n");
        out.push_str("        or parsed.username is not None\n");
        out.push_str("        or parsed.password is not None\n");
        out.push_str("        or \"?\" in base_url\n");
        out.push_str("        or \"#\" in base_url\n");
        out.push_str("        or parsed.path not in (\"\", \"/\")\n");
        out.push_str("        or not _is_dns_hostname(host)\n");
        out.push_str("        or not host.endswith(_FILE_BEARER_HOSTNAME_SUFFIX)\n");
        out.push_str("        or not host.removesuffix(_FILE_BEARER_HOSTNAME_SUFFIX)\n");
        out.push_str(
            "        or host.removesuffix(_FILE_BEARER_HOSTNAME_SUFFIX).endswith(\".\")\n",
        );
        out.push_str("    ):\n");
        out.push_str("        return headers\n");
        out.push_str("    try:\n");
        out.push_str(
            "        token = Path(_FILE_BEARER_TOKEN_PATH).read_text(encoding=\"utf-8\").strip()\n",
        );
        out.push_str("        value = f\"Bearer {token}\"\n");
        out.push_str("        if not token or not token.isascii() or not all(char.isprintable() and not char.isspace() for char in token):\n");
        out.push_str("            raise ValueError\n");
        out.push_str("    except (OSError, UnicodeError, ValueError):\n");
        out.push_str("        raise ValueError(\"request authentication token is unavailable or invalid\") from None\n");
        out.push_str("    result = dict(headers)\n");
        out.push_str("    result[\"Authorization\"] = value\n");
        out.push_str("    return result\n\n\n");
    }

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class PrivateTrust:\n");
    out.push_str(
        "    \"\"\"Verify the server against a private CA instead of the public roots.\n\n",
    );
    out.push_str("    For a service published only inside a cluster the public roots cannot\n");
    out.push_str("    vouch for it and should not be consulted: a private trust domain merely\n");
    out.push_str("    *added* to the public set still lets any public CA certify this name. The\n");
    out.push_str(
        "    context built from this replaces the root store rather than extending it.\n\n",
    );
    out.push_str("    There is no option to skip verification. If the server cannot be\n");
    out.push_str("    verified, the fix is the anchor or the name -- not the check.\n");
    out.push_str("    \"\"\"\n\n");
    out.push_str("    #: PEM bundle holding the CA that signed the server's leaf.\n");
    out.push_str("    ca_bundle: str\n");
    out.push_str("    #: The DNS name the leaf must assert. The base URL has to address this\n");
    out.push_str("    #: same name: a client that verified one name while addressing another\n");
    out.push_str("    #: would be checking a certificate it never actually relies on.\n");
    out.push_str("    server_name: str\n\n\n");
    out.push_str(
        "def _private_trust_context(trust: PrivateTrust, base_url: str) -> ssl.SSLContext:\n",
    );
    out.push_str("    addressed = urlsplit(base_url).hostname or \"\"\n");
    out.push_str("    if addressed != trust.server_name:\n");
    out.push_str("        raise ValueError(\n");
    out.push_str(
        "            f\"this client would verify {trust.server_name} while addressing \"\n",
    );
    out.push_str(
        "            f\"{addressed}; point the base URL at the name the certificate asserts\"\n",
    );
    out.push_str("        )\n");
    out.push_str(
        "    # Naming a cafile makes this the *only* trust anchor: create_default_context\n",
    );
    out.push_str("    # loads the system store only when no explicit one is given.\n");
    out.push_str("    context = ssl.create_default_context(cafile=trust.ca_bundle)\n");
    out.push_str("    context.check_hostname = True\n");
    out.push_str("    context.verify_mode = ssl.CERT_REQUIRED\n");
    out.push_str("    return context\n\n\n");
    out.push_str("class ResponseLike(Protocol):\n");
    out.push_str("    def raise_for_status(self) -> None: ...\n");
    out.push_str("    def json(self) -> Any: ...\n\n\n");
    out.push_str("class SupportsRequest(Protocol):\n");
    out.push_str(&format!(
        "    def request(self, method: str, url: str, *, params: dict[str, Any], headers: dict[str, Any], json: Any = None, data: Any = None, content: Any = None, timeout: {} = None) -> ResponseLike: ...\n\n\n",
        pymap::optional("float", target),
    ));
    out.push_str("class AsyncSupportsRequest(Protocol):\n");
    out.push_str(&format!(
        "    async def request(self, method: str, url: str, *, params: dict[str, Any], headers: dict[str, Any], json: Any = None, data: Any = None, content: Any = None, timeout: {} = None) -> ResponseLike: ...\n\n\n",
        pymap::optional("float", target),
    ));

    out.push_str("class Client:\n");
    out.push_str(&format!(
        "    def __init__(self, base_url: str, *, client: {} = None, default_headers: {} = None, auth_token: {} = None, trust: {} = None, use_post_fallback: bool = False) -> None:\n",
        pymap::optional("SupportsRequest", target),
        pymap::optional("Mapping[str, Any]", target),
        pymap::optional("str", target),
        pymap::optional("PrivateTrust", target),
    ));
    out.push_str("        self._base_url = base_url.rstrip(\"/\")\n");
    out.push_str("        if trust is None:\n");
    out.push_str("            ssl_context = None\n");
    out.push_str("        elif client is not None:\n");
    out.push_str(
        "            # An injected transport carries its own TLS configuration; silently\n",
    );
    out.push_str("            # ignoring `trust` here would leave the caller believing they had\n");
    out.push_str("            # pinned an anchor that nothing consults.\n");
    out.push_str("            raise ValueError(\n");
    out.push_str("                \"pass trust to the injected client instead; this one cannot configure it\"\n");
    out.push_str("            )\n");
    out.push_str("        else:\n");
    out.push_str("            ssl_context = _private_trust_context(trust, self._base_url)\n");
    out.push_str("        self._client = client or H2CClient(ssl_context=ssl_context)\n");
    out.push_str("        self._default_headers: dict[str, Any] = dict(default_headers or {})\n");
    out.push_str("        # Epic #1296 POST-twin fallback: route QUERY operations through their\n");
    out.push_str("        # documented POST twin instead of the HTTP QUERY method (RFC 10008).\n");
    out.push_str("        self._use_post_fallback = use_post_fallback\n");
    out.push_str("        if auth_token is not None:\n");
    out.push_str(
        "            self._default_headers[\"Authorization\"] = f\"Bearer {auth_token}\"\n",
    );
    out.push_str("\n");
    if target.is_some() {
        out.push_str("    def __enter__(self) -> Self:\n");
    } else {
        out.push_str("    def __enter__(self) -> \"Client\":\n");
    }
    out.push_str("        return self\n");
    out.push_str("\n");
    out.push_str("    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:\n");
    out.push_str("        self.close()\n");
    out.push_str("\n");
    out.push_str("    def close(self) -> None:\n");
    out.push_str("        close = getattr(self._client, \"close\", None)\n");
    out.push_str("        if close is not None:\n");
    out.push_str("            close()\n");

    let mut reg = NameRegistry::new();
    reg.unique("__init__");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(
            ir,
            tm,
            &mut reg,
            false,
            target,
            auth.is_some(),
        ));
    }

    out.push_str("\n\nclass AsyncClient:\n");
    out.push_str(&format!(
        "    def __init__(self, base_url: str, *, client: {} = None, default_headers: {} = None, auth_token: {} = None, trust: {} = None, use_post_fallback: bool = False) -> None:\n",
        pymap::optional("AsyncSupportsRequest", target),
        pymap::optional("Mapping[str, Any]", target),
        pymap::optional("str", target),
        pymap::optional("PrivateTrust", target),
    ));
    out.push_str("        self._base_url = base_url.rstrip(\"/\")\n");
    out.push_str("        if trust is None:\n");
    out.push_str("            ssl_context = None\n");
    out.push_str("        elif client is not None:\n");
    out.push_str(
        "            # An injected transport carries its own TLS configuration; silently\n",
    );
    out.push_str("            # ignoring `trust` here would leave the caller believing they had\n");
    out.push_str("            # pinned an anchor that nothing consults.\n");
    out.push_str("            raise ValueError(\n");
    out.push_str("                \"pass trust to the injected client instead; this one cannot configure it\"\n");
    out.push_str("            )\n");
    out.push_str("        else:\n");
    out.push_str("            ssl_context = _private_trust_context(trust, self._base_url)\n");
    out.push_str("        self._client = client or AsyncH2CClient(ssl_context=ssl_context)\n");
    out.push_str("        self._default_headers: dict[str, Any] = dict(default_headers or {})\n");
    out.push_str("        # Epic #1296 POST-twin fallback: route QUERY operations through their\n");
    out.push_str("        # documented POST twin instead of the HTTP QUERY method (RFC 10008).\n");
    out.push_str("        self._use_post_fallback = use_post_fallback\n");
    out.push_str("        if auth_token is not None:\n");
    out.push_str(
        "            self._default_headers[\"Authorization\"] = f\"Bearer {auth_token}\"\n",
    );
    out.push_str("\n");
    if target.is_some() {
        out.push_str("    async def __aenter__(self) -> Self:\n");
    } else {
        out.push_str("    async def __aenter__(self) -> \"AsyncClient\":\n");
    }
    out.push_str("        return self\n");
    out.push_str("\n");
    out.push_str("    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:\n");
    out.push_str("        await self.aclose()\n");
    out.push_str("\n");
    out.push_str("    async def aclose(self) -> None:\n");
    out.push_str("        close = getattr(self._client, \"aclose\", None) or getattr(self._client, \"close\", None)\n");
    out.push_str("        if close is not None:\n");
    out.push_str("            result = close()\n");
    out.push_str("            if hasattr(result, \"__await__\"):\n");
    out.push_str("                await result\n");
    out.push_str("\n");
    out.push_str("    async def close(self) -> None:\n");
    out.push_str("        await self.aclose()\n");
    let mut async_reg = NameRegistry::new();
    async_reg.unique("__init__");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(
            ir,
            tm,
            &mut async_reg,
            true,
            target,
            auth.is_some(),
        ));
    }
    out
}

fn fn_name(ir: &OperationIR) -> String {
    match &ir.operation_id {
        Some(id) if !id.trim().is_empty() => to_snake(id),
        _ => to_snake(&format!(
            "{}_{}",
            ir.method,
            ir.path.replace(['/', '{', '}'], "_")
        )),
    }
}

/// `(python_param, type, required)` for a parameter.
fn param_ann(p: &ParamIR, tm: &TypeMap, target: Option<PythonTarget>) -> (String, String, bool) {
    let ty = p
        .schema
        .as_ref()
        .map(|s| pymap::type_expr(s, tm, target))
        .unwrap_or_else(|| "str".to_string());
    (to_snake(&p.name), ty, p.required)
}

fn emit_method(
    ir: &OperationIR,
    tm: &TypeMap,
    reg: &mut NameRegistry,
    is_async: bool,
    target: Option<PythonTarget>,
    file_bearer_auth: bool,
) -> String {
    let name = reg.unique(&fn_name(ir));

    // Signature parameters in a stable order: path, query, header, body.
    let mut sig: Vec<String> = Vec::new();
    let path_anns: Vec<(String, String, bool)> = ir
        .path_params
        .iter()
        .map(|p| param_ann(p, tm, target))
        .collect();
    let query_anns: Vec<(String, String, bool)> = ir
        .query_params
        .iter()
        .map(|p| param_ann(p, tm, target))
        .collect();
    let header_anns: Vec<(String, String, bool)> = ir
        .header_params
        .iter()
        .map(|p| param_ann(p, tm, target))
        .collect();

    for (n, t, _) in &path_anns {
        sig.push(format!("{n}: {t}")); // path params are always required
    }
    for (n, t, req) in query_anns.iter().chain(header_anns.iter()) {
        if *req {
            sig.push(format!("{n}: {t}"));
        } else {
            sig.push(format!("{n}: {} = None", pymap::optional(t, target)));
        }
    }
    let body_ty = ir
        .body
        .as_ref()
        .map(|b| pymap::type_expr(&b.schema, tm, target));
    if let Some(ty) = &body_ty {
        let required = ir.body.as_ref().map(|b| b.required).unwrap_or(false);
        if required {
            sig.push(format!("body: {ty}"));
        } else {
            sig.push(format!("body: {} = None", pymap::optional(ty, target)));
        }
    }

    let (ret_ann, ret_stmt) = response(ir, tm, target);
    let sig_str = if sig.is_empty() {
        String::new()
    } else {
        format!(", *, {}", sig.join(", "))
    };

    let async_prefix = if is_async { "async " } else { "" };
    let mut m = format!("    {async_prefix}def {name}(self{sig_str}) -> {ret_ann}:\n");

    // Path with python param names substituted into the f-string.
    let mut path = ir.path.clone();
    for (p, (snake, ..)) in ir.path_params.iter().zip(&path_anns) {
        path = path.replace(&format!("{{{}}}", p.name), &format!("{{{snake}}}"));
    }
    m.push_str(&format!("        _path = f\"{path}\"\n"));

    // Epic #1296 POST-twin fallback: a `QUERY` operation always carries a
    // twin path (`x-post-twin` override, else its own path); at call time,
    // `self._use_post_fallback` picks POST + twin path over HTTP QUERY.
    let twin = ir.post_twin_path.as_ref().map(|twin_path| {
        let mut twin_path = twin_path.clone();
        for (p, (snake, ..)) in ir.path_params.iter().zip(&path_anns) {
            twin_path = twin_path.replace(&format!("{{{}}}", p.name), &format!("{{{snake}}}"));
        }
        twin_path
    });

    m.push_str("        _params: dict[str, Any] = {}\n");
    for (p, (snake, _, req)) in ir.query_params.iter().zip(&query_anns) {
        if *req {
            m.push_str(&format!(
                "        _params[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        } else {
            m.push_str(&format!(
                "        if {snake} is not None:\n            _params[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        }
    }
    m.push_str("        _headers: dict[str, Any] = dict(self._default_headers)\n");
    for (p, (snake, _, req)) in ir.header_params.iter().zip(&header_anns) {
        if *req {
            m.push_str(&format!(
                "        _headers[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        } else {
            m.push_str(&format!(
                "        if {snake} is not None:\n            _headers[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        }
    }
    if file_bearer_auth {
        m.push_str("        _headers = _file_bearer_headers(self._base_url, _headers)\n");
    }

    let json_arg = if body_ty.is_some() {
        m.push_str("        _json = body.model_dump(by_alias=True, exclude_none=True) if isinstance(body, BaseModel) else body\n");
        ", json=_json"
    } else {
        ""
    };

    let method_expr = match &twin {
        Some(twin_path) => {
            m.push_str("        if self._use_post_fallback:\n");
            m.push_str("            _method = \"POST\"\n");
            m.push_str(&format!("            _path = f\"{twin_path}\"\n"));
            m.push_str("        else:\n");
            m.push_str(&format!("            _method = \"{}\"\n", ir.http_method));
            "_method".to_string()
        }
        None => format!("\"{}\"", ir.http_method),
    };

    if is_async {
        m.push_str(&format!(
            "        _resp = await self._client.request({method_expr}, self._base_url + _path, params=_params, headers=_headers{json_arg})\n"
        ));
    } else {
        m.push_str(&format!(
            "        _resp = self._client.request({method_expr}, self._base_url + _path, params=_params, headers=_headers{json_arg})\n"
        ));
    }
    m.push_str("        _resp.raise_for_status()\n");
    m.push_str(&format!("        {ret_stmt}\n"));
    m
}

/// `(return annotation, return statement)` for the operation's response.
fn response(ir: &OperationIR, tm: &TypeMap, target: Option<PythonTarget>) -> (String, String) {
    match &ir.response {
        None => ("None".to_string(), "return None".to_string()),
        Some(RefOr::Ref(r)) => match tm.resolve_ref(&r.reference) {
            Some(model) => (
                model.clone(),
                format!("return {model}.model_validate(_resp.json())"),
            ),
            None => ("Any".to_string(), "return _resp.json()".to_string()),
        },
        Some(node @ RefOr::Item(_)) => (
            pymap::type_expr(node, tm, target),
            "return _resp.json()".to_string(),
        ),
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn python_literal(value: &str) -> String {
    serde_json::to_string(value).expect("serialize generated Python string literal")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::openapi::Spec;
    use crate::ir::operations;
    use crate::{build_type_map, PythonTarget};

    fn spec(json: &str) -> Spec {
        serde_json::from_str(json).unwrap()
    }

    #[test]
    fn init_signatures_accept_use_post_fallback() {
        let s = spec(r##"{"paths":{}}"##);
        let tm = build_type_map(&s);
        let out = emit(&operations::build(&s), &tm, Some(PythonTarget::Py311), None);
        assert!(out.contains("use_post_fallback: bool = False"));
        assert!(out.contains("self._use_post_fallback = use_post_fallback"));
        // Both Client and AsyncClient carry the flag.
        assert_eq!(out.matches("use_post_fallback: bool = False").count(), 2);
    }

    #[test]
    fn a_private_ca_is_the_only_anchor_and_the_name_must_match_the_base_url() {
        let s = spec(r##"{"paths":{}}"##);
        let tm = build_type_map(&s);
        let out = emit(&operations::build(&s), &tm, Some(PythonTarget::Py311), None);
        // A cafile makes create_default_context skip the system store entirely,
        // which is the point: a private domain merged into the public one still
        // lets any public CA certify this name.
        assert!(out.contains("ssl.create_default_context(cafile=trust.ca_bundle)"));
        assert!(out.contains("context.check_hostname = True"));
        assert!(out.contains("context.verify_mode = ssl.CERT_REQUIRED"));
        assert!(out.contains("if addressed != trust.server_name:"));
        // Both Client and AsyncClient accept it and hand it to their transport.
        assert_eq!(out.matches("trust: PrivateTrust | None = None").count(), 2);
        assert_eq!(
            out.matches("ssl_context = _private_trust_context(trust, self._base_url)")
                .count(),
            2
        );
    }

    #[test]
    fn no_generated_client_offers_to_skip_verification() {
        let s = spec(r##"{"paths":{}}"##);
        let tm = build_type_map(&s);
        let out = emit(&operations::build(&s), &tm, Some(PythonTarget::Py311), None);
        for weakening in [
            "CERT_NONE",
            "check_hostname = False",
            "verify=False",
            "insecure",
        ] {
            assert!(
                !out.contains(weakening),
                "generated clients must not ship {weakening}: the fix for an unverifiable \
                 server is the anchor or the name, not the check"
            );
        }
    }

    #[test]
    fn query_operation_sends_query_method_with_json_body_by_default() {
        let s = spec(
            r##"{"paths":{"/pets":{
              "query":{"operationId":"searchPets",
                "requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object"}}}},
                "responses":{"200":{"content":{"application/json":{"schema":{"type":"array","items":{"type":"string"}}}}}}}}}}"##,
        );
        let tm = build_type_map(&s);
        let out = emit(&operations::build(&s), &tm, Some(PythonTarget::Py311), None);
        assert!(out.contains("def search_pets(self, *, body:"));
        assert!(out.contains("if self._use_post_fallback:"));
        assert!(out.contains("_method = \"POST\""));
        assert!(out.contains("_path = f\"/pets\""));
        assert!(out.contains("_method = \"QUERY\""));
        assert!(out.contains(
            "_resp = self._client.request(_method, self._base_url + _path, params=_params, headers=_headers, json=_json)"
        ));
    }

    #[test]
    fn query_operation_honors_x_post_twin_path_override() {
        let s = spec(
            r##"{"paths":{"/pets/{petId}":{
              "query":{"operationId":"searchPetById","x-post-twin":"/pets/{petId}/search",
                "parameters":[{"name":"petId","in":"path","required":true,"schema":{"type":"integer"}}],
                "requestBody":{"required":true,"content":{"application/json":{"schema":{"type":"object"}}}},
                "responses":{"200":{"content":{"application/json":{"schema":{"type":"string"}}}}}}}}}"##,
        );
        let tm = build_type_map(&s);
        let out = emit(&operations::build(&s), &tm, Some(PythonTarget::Py311), None);
        assert!(out.contains("_path = f\"/pets/{pet_id}/search\""));
    }

    #[test]
    fn non_query_operation_has_no_fallback_branch() {
        let s = spec(
            r##"{"paths":{"/pets":{"get":{"operationId":"listPets","responses":{"200":{"content":{"application/json":{"schema":{"type":"array","items":{"type":"string"}}}}}}}}}}"##,
        );
        let tm = build_type_map(&s);
        let out = emit(&operations::build(&s), &tm, Some(PythonTarget::Py311), None);
        assert!(!out.contains("if self._use_post_fallback:"));
        assert!(out.contains(
            "_resp = self._client.request(\"GET\", self._base_url + _path, params=_params, headers=_headers)"
        ));
    }
}
// CODEGEN-END
