//! Emit a Python client: one method per operation, with pydantic-validated
//! sync and async responses. The generated default runtime speaks h2c for
//! http:// and ALPN h2 for https://, while callers may inject any httpx-like
//! object with `request`.

use crate::emit::py::pymap;
use crate::ir::names::{to_snake, NameRegistry};
use crate::ir::openapi::RefOr;
use crate::ir::operations::{OperationIR, ParamIR};
use crate::ir::typemap::TypeMap;

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

pub fn emit(ops: &[OperationIR], tm: &TypeMap) -> String {
    let mut out = String::from(HEADER);
    out.push_str("from __future__ import annotations\n");
    out.push_str("from typing import Any, Literal, Mapping, Optional, Protocol\n");
    out.push_str("from pydantic import BaseModel\n");
    out.push_str("from .h2c_runtime import AsyncH2CClient, H2CClient\n");
    out.push_str("from .models import *  # noqa: F401,F403\n\n\n");

    out.push_str("class ResponseLike(Protocol):\n");
    out.push_str("    def raise_for_status(self) -> None: ...\n");
    out.push_str("    def json(self) -> Any: ...\n\n\n");
    out.push_str("class SupportsRequest(Protocol):\n");
    out.push_str("    def request(self, method: str, url: str, *, params: dict[str, Any], headers: dict[str, Any], json: Any = None, data: Any = None, content: Any = None, timeout: Optional[float] = None) -> ResponseLike: ...\n\n\n");
    out.push_str("class AsyncSupportsRequest(Protocol):\n");
    out.push_str("    async def request(self, method: str, url: str, *, params: dict[str, Any], headers: dict[str, Any], json: Any = None, data: Any = None, content: Any = None, timeout: Optional[float] = None) -> ResponseLike: ...\n\n\n");

    out.push_str("class Client:\n");
    out.push_str("    def __init__(self, base_url: str, *, client: Optional[SupportsRequest] = None, default_headers: Optional[Mapping[str, Any]] = None, auth_token: Optional[str] = None) -> None:\n");
    out.push_str("        self._base_url = base_url.rstrip(\"/\")\n");
    out.push_str("        self._client = client or H2CClient()\n");
    out.push_str("        self._default_headers: dict[str, Any] = dict(default_headers or {})\n");
    out.push_str("        if auth_token is not None:\n");
    out.push_str(
        "            self._default_headers[\"Authorization\"] = f\"Bearer {auth_token}\"\n",
    );
    out.push_str("\n");
    out.push_str("    def __enter__(self) -> \"Client\":\n");
    out.push_str("        return self\n");
    out.push_str("\n");
    out.push_str("    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:\n");
    out.push_str("        self.close()\n");
    out.push_str("\n");
    out.push_str("    def close(self) -> None:\n");
    out.push_str("        close = getattr(self._client, \"close\", None)\n");
    out.push_str("        if close is not None:\n");
    out.push_str("            close()\n");

    let mut reg = NameRegistry::new();
    reg.unique("__init__");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(ir, tm, &mut reg, false));
    }

    out.push_str("\n\nclass AsyncClient:\n");
    out.push_str("    def __init__(self, base_url: str, *, client: Optional[AsyncSupportsRequest] = None, default_headers: Optional[Mapping[str, Any]] = None, auth_token: Optional[str] = None) -> None:\n");
    out.push_str("        self._base_url = base_url.rstrip(\"/\")\n");
    out.push_str("        self._client = client or AsyncH2CClient()\n");
    out.push_str("        self._default_headers: dict[str, Any] = dict(default_headers or {})\n");
    out.push_str("        if auth_token is not None:\n");
    out.push_str(
        "            self._default_headers[\"Authorization\"] = f\"Bearer {auth_token}\"\n",
    );
    out.push_str("\n");
    out.push_str("    async def __aenter__(self) -> \"AsyncClient\":\n");
    out.push_str("        return self\n");
    out.push_str("\n");
    out.push_str("    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:\n");
    out.push_str("        await self.aclose()\n");
    out.push_str("\n");
    out.push_str("    async def aclose(self) -> None:\n");
    out.push_str("        close = getattr(self._client, \"aclose\", None) or getattr(self._client, \"close\", None)\n");
    out.push_str("        if close is not None:\n");
    out.push_str("            result = close()\n");
    out.push_str("            if hasattr(result, \"__await__\"):\n");
    out.push_str("                await result\n");
    out.push_str("\n");
    out.push_str("    async def close(self) -> None:\n");
    out.push_str("        await self.aclose()\n");
    let mut async_reg = NameRegistry::new();
    async_reg.unique("__init__");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(ir, tm, &mut async_reg, true));
    }
    out
}

fn fn_name(ir: &OperationIR) -> String {
    match &ir.operation_id {
        Some(id) if !id.trim().is_empty() => to_snake(id),
        _ => to_snake(&format!(
            "{}_{}",
            ir.method,
            ir.path.replace(['/', '{', '}'], "_")
        )),
    }
}

/// `(python_param, type, required)` for a parameter.
fn param_ann(p: &ParamIR, tm: &TypeMap) -> (String, String, bool) {
    let ty = p
        .schema
        .as_ref()
        .map(|s| pymap::type_expr(s, tm))
        .unwrap_or_else(|| "str".to_string());
    (to_snake(&p.name), ty, p.required)
}

fn emit_method(ir: &OperationIR, tm: &TypeMap, reg: &mut NameRegistry, is_async: bool) -> String {
    let name = reg.unique(&fn_name(ir));

    // Signature parameters in a stable order: path, query, header, body.
    let mut sig: Vec<String> = Vec::new();
    let path_anns: Vec<(String, String, bool)> =
        ir.path_params.iter().map(|p| param_ann(p, tm)).collect();
    let query_anns: Vec<(String, String, bool)> =
        ir.query_params.iter().map(|p| param_ann(p, tm)).collect();
    let header_anns: Vec<(String, String, bool)> =
        ir.header_params.iter().map(|p| param_ann(p, tm)).collect();

    for (n, t, _) in &path_anns {
        sig.push(format!("{n}: {t}")); // path params are always required
    }
    for (n, t, req) in query_anns.iter().chain(header_anns.iter()) {
        if *req {
            sig.push(format!("{n}: {t}"));
        } else {
            sig.push(format!("{n}: {} = None", pymap::optional(t)));
        }
    }
    let body_ty = ir.body.as_ref().map(|b| pymap::type_expr(&b.schema, tm));
    if let Some(ty) = &body_ty {
        let required = ir.body.as_ref().map(|b| b.required).unwrap_or(false);
        if required {
            sig.push(format!("body: {ty}"));
        } else {
            sig.push(format!("body: {} = None", pymap::optional(ty)));
        }
    }

    let (ret_ann, ret_stmt) = response(ir, tm);
    let sig_str = if sig.is_empty() {
        String::new()
    } else {
        format!(", *, {}", sig.join(", "))
    };

    let async_prefix = if is_async { "async " } else { "" };
    let mut m = format!("    {async_prefix}def {name}(self{sig_str}) -> {ret_ann}:\n");

    // Path with python param names substituted into the f-string.
    let mut path = ir.path.clone();
    for (p, (snake, ..)) in ir.path_params.iter().zip(&path_anns) {
        path = path.replace(&format!("{{{}}}", p.name), &format!("{{{snake}}}"));
    }
    m.push_str(&format!("        _path = f\"{path}\"\n"));

    m.push_str("        _params: dict[str, Any] = {}\n");
    for (p, (snake, _, req)) in ir.query_params.iter().zip(&query_anns) {
        if *req {
            m.push_str(&format!(
                "        _params[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        } else {
            m.push_str(&format!(
                "        if {snake} is not None:\n            _params[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        }
    }
    m.push_str("        _headers: dict[str, Any] = dict(self._default_headers)\n");
    for (p, (snake, _, req)) in ir.header_params.iter().zip(&header_anns) {
        if *req {
            m.push_str(&format!(
                "        _headers[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        } else {
            m.push_str(&format!(
                "        if {snake} is not None:\n            _headers[\"{}\"] = {snake}\n",
                esc(&p.name)
            ));
        }
    }

    let json_arg = if body_ty.is_some() {
        m.push_str("        _json = body.model_dump(by_alias=True, exclude_none=True) if isinstance(body, BaseModel) else body\n");
        ", json=_json"
    } else {
        ""
    };

    if is_async {
        m.push_str(&format!(
            "        _resp = await self._client.request(\"{}\", self._base_url + _path, params=_params, headers=_headers{json_arg})\n",
            ir.http_method
        ));
    } else {
        m.push_str(&format!(
            "        _resp = self._client.request(\"{}\", self._base_url + _path, params=_params, headers=_headers{json_arg})\n",
            ir.http_method
        ));
    }
    m.push_str("        _resp.raise_for_status()\n");
    m.push_str(&format!("        {ret_stmt}\n"));
    m
}

/// `(return annotation, return statement)` for the operation's response.
fn response(ir: &OperationIR, tm: &TypeMap) -> (String, String) {
    match &ir.response {
        None => ("None".to_string(), "return None".to_string()),
        Some(RefOr::Ref(r)) => match tm.resolve_ref(&r.reference) {
            Some(model) => (
                model.clone(),
                format!("return {model}.model_validate(_resp.json())"),
            ),
            None => ("Any".to_string(), "return _resp.json()".to_string()),
        },
        Some(node @ RefOr::Item(_)) => (
            pymap::type_expr(node, tm),
            "return _resp.json()".to_string(),
        ),
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
