//! Emit pydantic v2 models for the spec's component schemas.

use crate::emit::py::pymap;
use crate::ir::names::to_pascal;
use crate::ir::openapi::{RefOr, Schema, Spec};
use crate::ir::typemap::TypeMap;

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

const PY_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

/// True when `s` is a usable bare Python identifier (and not a keyword).
pub fn is_py_ident(s: &str) -> bool {
    let mut c = s.chars();
    match c.next() {
        Some(ch) if ch.is_ascii_alphabetic() || ch == '_' => {}
        _ => return false,
    }
    c.all(|ch| ch.is_ascii_alphanumeric() || ch == '_') && !PY_KEYWORDS.contains(&s)
}

pub fn emit(spec: &Spec, tm: &TypeMap) -> String {
    let mut out = String::from(HEADER);
    out.push_str("from __future__ import annotations\n");
    out.push_str("from typing import Any, Literal, Optional\n");
    out.push_str("from pydantic import BaseModel, Field\n");

    let blocks: Vec<String> = spec
        .components
        .schemas
        .iter()
        .map(|(key, schema)| {
            let name = tm.names.get(key).cloned().unwrap_or_else(|| to_pascal(key));
            emit_schema(&name, schema, tm)
        })
        .collect();
    if !blocks.is_empty() {
        out.push('\n');
        out.push_str(&blocks.join("\n\n"));
    }
    out.push('\n');
    out
}

fn emit_schema(name: &str, node: &RefOr<Schema>, tm: &TypeMap) -> String {
    match node {
        // A component that is itself a `$ref` → a plain alias.
        RefOr::Ref(_) => format!("{name} = {}", pymap::type_expr(node, tm)),
        RefOr::Item(schema) if schema.properties.is_empty() => {
            // enum / union / primitive / free-form object → type alias
            format!("{name} = {}", pymap::type_expr(node, tm))
        }
        RefOr::Item(schema) => emit_model(name, schema, tm),
    }
}

fn emit_model(name: &str, schema: &Schema, tm: &TypeMap) -> String {
    let mut s = format!("class {name}(BaseModel):\n");
    for (key, prop) in &schema.properties {
        let required = schema.required.iter().any(|r| r == key);
        let ty = pymap::type_expr(prop, tm);
        let ty = if required { ty } else { pymap::optional(&ty) };
        let (field, alias) = if is_py_ident(key) {
            (key.clone(), None)
        } else {
            (sanitize(key), Some(key.clone()))
        };
        let tail = match (required, alias) {
            (true, None) => String::new(),
            (true, Some(a)) => format!(" = Field(alias=\"{}\")", esc(&a)),
            (false, None) => " = None".to_string(),
            (false, Some(a)) => format!(" = Field(default=None, alias=\"{}\")", esc(&a)),
        };
        s.push_str(&format!("    {field}: {ty}{tail}\n"));
    }
    s
}

fn sanitize(key: &str) -> String {
    let mut out: String = key
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if !out
        .chars()
        .next()
        .map(|c| c.is_ascii_alphabetic() || c == '_')
        .unwrap_or(false)
    {
        out.insert(0, '_');
    }
    out
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
