// CODEGEN-BEGIN
//! Emit pydantic v2 models for the spec's component schemas.

use crate::emit::py::pymap;
use crate::ir::names::to_pascal;
use crate::ir::openapi::{AdditionalProperties, RefOr, Schema, Spec};
use crate::ir::typemap::TypeMap;
use crate::PythonTarget;
use std::collections::BTreeSet;

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

const PY_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

/// True when `s` is a usable bare Python identifier (and not a keyword).
pub fn is_py_ident(s: &str) -> bool {
    let mut c = s.chars();
    match c.next() {
        Some(ch) if ch.is_ascii_alphabetic() || ch == '_' => {}
        _ => return false,
    }
    c.all(|ch| ch.is_ascii_alphanumeric() || ch == '_') && !PY_KEYWORDS.contains(&s)
}

pub fn emit(spec: &Spec, tm: &TypeMap, target: Option<PythonTarget>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("from __future__ import annotations\n");
    if target.is_some() {
        out.push_str("from typing import Any, Literal\n");
    } else {
        out.push_str("from typing import Any, Literal, Optional, Union\n");
    }
    out.push_str("from pydantic import BaseModel, Field, RootModel\n");

    // Python aliases evaluate their right-hand side at import time, unlike
    // pydantic annotations (which are deferred by ``from __future__``).  Keep
    // concrete models ahead of aliases, then emit aliases in dependency order.
    // OpenAPI component names are alphabetically ordered in the IR, so without
    // this pass `BatchSearchItem = SearchRequest` can precede `SearchRequest`.
    let mut emitted: BTreeSet<&str> = BTreeSet::new();
    let mut blocks: Vec<String> = Vec::new();
    let mut aliases: Vec<(&str, &RefOr<Schema>)> = Vec::new();
    for (key, schema) in &spec.components.schemas {
        if is_runtime_alias(schema) {
            aliases.push((key, schema));
        } else {
            emitted.insert(key);
            let name = tm.names.get(key).cloned().unwrap_or_else(|| to_pascal(key));
            blocks.push(emit_schema(&name, schema, tm, target));
        }
    }

    // An alias may itself reference another alias (for example an array or a
    // union alias).  Topologically order that acyclic subset; retain the
    // source's deterministic BTreeMap order if an invalid recursive alias
    // cycle remains, so generation never becomes nondeterministic.
    while !aliases.is_empty() {
        let next = aliases.iter().position(|(_, schema)| {
            component_dependencies(schema)
                .iter()
                .all(|dependency| emitted.contains(dependency.as_str()))
        });
        let index = next.unwrap_or(0);
        let (key, schema) = aliases.remove(index);
        let name = tm.names.get(key).cloned().unwrap_or_else(|| to_pascal(key));
        blocks.push(emit_schema(&name, schema, tm, target));
        emitted.insert(key);
    }
    if !blocks.is_empty() {
        out.push('\n');
        out.push_str(&blocks.join("\n\n"));
    }
    out.push('\n');
    out
}

fn is_runtime_alias(node: &RefOr<Schema>) -> bool {
    matches!(node, RefOr::Ref(_))
        || matches!(node, RefOr::Item(schema) if !root_union_is_useful(schema) && schema.properties.is_empty())
}

fn component_dependencies(node: &RefOr<Schema>) -> BTreeSet<String> {
    let mut dependencies = BTreeSet::new();
    collect_component_dependencies(node, &mut dependencies);
    dependencies
}

fn collect_component_dependencies(node: &RefOr<Schema>, dependencies: &mut BTreeSet<String>) {
    match node {
        RefOr::Ref(reference) => {
            if let Some(name) = reference.reference.strip_prefix("#/components/schemas/") {
                dependencies.insert(name.to_string());
            }
        }
        RefOr::Item(schema) => {
            for property in schema.properties.values() {
                collect_component_dependencies(property, dependencies);
            }
            if let Some(items) = &schema.items {
                collect_component_dependencies(items, dependencies);
            }
            for variant in schema
                .one_of
                .iter()
                .chain(schema.any_of.iter())
                .chain(schema.all_of.iter())
            {
                collect_component_dependencies(variant, dependencies);
            }
            if let Some(AdditionalProperties::Schema(value)) = &schema.additional_properties {
                collect_component_dependencies(value, dependencies);
            }
        }
    }
}

fn emit_schema(
    name: &str,
    node: &RefOr<Schema>,
    tm: &TypeMap,
    target: Option<PythonTarget>,
) -> String {
    match node {
        // A component that is itself a `$ref` → a plain alias.
        RefOr::Ref(_) => emit_alias(name, &pymap::type_expr(node, tm, target), target),
        RefOr::Item(schema) if root_union_is_useful(schema) => {
            emit_root_union_model(name, schema, tm, target)
        }
        RefOr::Item(schema) if schema.properties.is_empty() => {
            // enum / union / primitive / free-form object → type alias
            emit_alias(name, &pymap::type_expr(node, tm, target), target)
        }
        RefOr::Item(schema) => emit_model(name, schema, tm, target),
    }
}

fn emit_alias(name: &str, ty: &str, target: Option<PythonTarget>) -> String {
    if target.is_some_and(PythonTarget::uses_pep695_type_aliases) {
        format!("type {name} = {ty}")
    } else {
        format!("{name} = {ty}")
    }
}

fn root_union_is_useful(schema: &Schema) -> bool {
    let variants = if !schema.one_of.is_empty() {
        &schema.one_of
    } else if !schema.any_of.is_empty() {
        &schema.any_of
    } else {
        return false;
    };
    variants.iter().any(|variant| match variant {
        RefOr::Item(s) => !s.properties.is_empty(),
        RefOr::Ref(_) => false,
    })
}

fn emit_root_union_model(
    name: &str,
    schema: &Schema,
    tm: &TypeMap,
    target: Option<PythonTarget>,
) -> String {
    let variants = if !schema.one_of.is_empty() {
        &schema.one_of
    } else {
        &schema.any_of
    };
    let mut blocks: Vec<String> = Vec::new();
    let mut variant_names: Vec<String> = Vec::new();
    for (idx, variant) in variants.iter().enumerate() {
        match variant {
            RefOr::Ref(_) => variant_names.push(pymap::type_expr(variant, tm, target)),
            RefOr::Item(s) if s.properties.is_empty() => {
                variant_names.push(pymap::type_expr(variant, tm, target))
            }
            RefOr::Item(s) => {
                let variant_name = inline_variant_name(name, s, idx);
                blocks.push(emit_model(&variant_name, s, tm, target));
                variant_names.push(variant_name);
            }
        }
    }
    blocks.push(format!(
        "class {name}(RootModel[{}]):\n    pass\n",
        pymap::union_expr(variant_names, target)
    ));
    blocks.join("\n\n")
}

fn inline_variant_name(parent: &str, schema: &Schema, idx: usize) -> String {
    if schema.required.len() == 1 && schema.properties.contains_key(&schema.required[0]) {
        format!("{parent}{}", to_pascal(&schema.required[0]))
    } else {
        format!("{parent}Variant{}", idx + 1)
    }
}

fn emit_model(name: &str, schema: &Schema, tm: &TypeMap, target: Option<PythonTarget>) -> String {
    let mut s = format!("class {name}(BaseModel):\n");
    for (key, prop) in &schema.properties {
        let required = schema.required.iter().any(|r| r == key);
        let ty = pymap::type_expr(prop, tm, target);
        let ty = if required {
            ty
        } else {
            pymap::optional(&ty, target)
        };
        let (field, alias) = if is_py_ident(key) {
            (key.clone(), None)
        } else {
            (sanitize(key), Some(key.clone()))
        };
        let tail = match (required, alias) {
            (true, None) => String::new(),
            (true, Some(a)) => format!(" = Field(alias=\"{}\")", esc(&a)),
            (false, None) => " = None".to_string(),
            (false, Some(a)) => format!(" = Field(default=None, alias=\"{}\")", esc(&a)),
        };
        s.push_str(&format!("    {field}: {ty}{tail}\n"));
    }
    s
}

fn sanitize(key: &str) -> String {
    let mut out: String = key
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if !out
        .chars()
        .next()
        .map(|c| c.is_ascii_alphabetic() || c == '_')
        .unwrap_or(false)
    {
        out.insert(0, '_');
    }
    if !is_py_ident(&out) {
        out.push('_');
    }
    out
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::build_type_map;

    #[test]
    fn emits_reference_alias_after_its_model() {
        let spec: Spec = serde_json::from_str(
            r##"{
              "openapi": "3.0.0",
              "info": { "title": "Aliases", "version": "1" },
              "paths": {},
              "components": { "schemas": {
                "BatchSearchItem": { "$ref": "#/components/schemas/SearchRequest" },
                "SearchRequest": {
                  "type": "object",
                  "properties": { "query": { "type": "string" } },
                  "required": ["query"]
                }
              } }
            }"##,
        )
        .expect("parse alias ordering fixture");
        let rendered = emit(&spec, &build_type_map(&spec), Some(PythonTarget::Py311));

        assert!(
            rendered.find("class SearchRequest(BaseModel):").unwrap()
                < rendered.find("BatchSearchItem = SearchRequest").unwrap()
        );
    }
}
// CODEGEN-END
