//! Emit the generated Python HTTP/2 runtime.

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

const RUNTIME: &str = r####"from __future__ import annotations

import asyncio
import json as _json
import socket
import ssl
import threading
from dataclasses import dataclass
from typing import Any, AsyncIterator, Iterable, Iterator, Mapping, Optional
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit


_CLIENT_PREFACE = b"PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n"
_CLIENT_SETTINGS = b"\x00\x02\x00\x00\x00\x00"
_FRAME_DATA = 0
_FRAME_HEADERS = 1
_FRAME_PRIORITY = 2
_FRAME_RST_STREAM = 3
_FRAME_SETTINGS = 4
_FRAME_PUSH_PROMISE = 5
_FRAME_PING = 6
_FRAME_GOAWAY = 7
_FRAME_WINDOW_UPDATE = 8
_FRAME_CONTINUATION = 9
_FLAG_ACK = 0x1
_FLAG_END_STREAM = 0x1
_FLAG_END_HEADERS = 0x4
_FLAG_PADDED = 0x8
_FLAG_PRIORITY = 0x20
_ERROR_REFUSED_STREAM = 7
_MAX_INBOUND_FRAME = 16384
_MAX_HEADER_BLOCK = 65536
_MAX_HEADER_TABLE_SIZE = 4096
_MAX_FLOW_CONTROL_WINDOW = 0x7FFFFFFF
_DEFAULT_TIMEOUT = 5.0
_DEFAULT_MAX_RESPONSE_BYTES = 64 * 1024 * 1024
_TOKEN_SEPARATORS = set("()<>@,;:\\\"/[]?={}")


class H2CError(RuntimeError):
    pass


class H2CProtocolError(H2CError):
    pass


class H2CConnectionClosed(H2CError):
    pass


class H2CTimeout(H2CError):
    pass


class H2CStatusError(H2CError):
    def __init__(self, response: "H2CResponse") -> None:
        self.response = response
        super().__init__(f"HTTP {response.status_code}: {response.text}")


@dataclass
class H2CResponse:
    status_code: int
    headers: dict[str, str]
    content: bytes

    @property
    def text(self) -> str:
        charset = "utf-8"
        content_type = self.headers.get("content-type", "")
        for part in content_type.split(";"):
            part = part.strip()
            if part.lower().startswith("charset="):
                charset = part.split("=", 1)[1].strip()
        return self.content.decode(charset, errors="replace")

    def json(self) -> Any:
        if not self.content:
            return None
        return _json.loads(self.content.decode("utf-8"))

    def raise_for_status(self) -> None:
        if self.status_code >= 400:
            raise H2CStatusError(self)


def _without_none(values: Mapping[str, Any] | Iterable[tuple[str, Any]] | None) -> list[tuple[str, Any]]:
    if values is None:
        return []
    items = values.items() if isinstance(values, Mapping) else values
    return [(str(k), v) for k, v in items if v is not None]


def _url_with_params(url: str, params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None) -> str:
    extra = _without_none(params)
    if not extra:
        return url
    parsed = urlsplit(url)
    query = parse_qsl(parsed.query, keep_blank_values=True)
    query.extend(extra)
    return urlunsplit((parsed.scheme, parsed.netloc, parsed.path, urlencode(query, doseq=True), parsed.fragment))


def _authority(parsed: Any) -> str:
    if parsed.hostname is None:
        raise H2CError("absolute http URL required")
    if parsed.port is None:
        return parsed.hostname
    return f"{parsed.hostname}:{parsed.port}"


def _request_path(parsed: Any) -> str:
    path = parsed.path or "/"
    if parsed.query:
        return f"{path}?{parsed.query}"
    return path


def _validate_header_pair(name: str, value: str) -> None:
    if not name:
        raise H2CProtocolError("HTTP header name cannot be empty")
    for char in name:
        code = ord(char)
        if code <= 32 or code >= 127 or char in _TOKEN_SEPARATORS:
            raise H2CProtocolError(f"invalid HTTP header name: {name!r}")
    if "\r" in value or "\n" in value or "\0" in value:
        raise H2CProtocolError(f"invalid HTTP header value for {name!r}")


def _validate_method(method: str) -> str:
    method = method.upper()
    if not method:
        raise H2CProtocolError("HTTP method cannot be empty")
    for char in method:
        code = ord(char)
        if code <= 32 or code >= 127 or char in _TOKEN_SEPARATORS:
            raise H2CProtocolError(f"invalid HTTP method: {method!r}")
    return method


def _header_pairs(headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None) -> list[tuple[str, str]]:
    blocked = {
        "connection",
        "keep-alive",
        "proxy-connection",
        "te",
        "transfer-encoding",
        "upgrade",
        "http2-settings",
    }
    out: list[tuple[str, str]] = []
    for key, value in _without_none(headers):
        name = key.lower()
        if name.startswith(":") or name in blocked:
            continue
        header_value = str(value)
        _validate_header_pair(name, header_value)
        out.append((name, header_value))
    return out


def _body_bytes(json_body: Any = None, data: Any = None, content: Any = None) -> tuple[Optional[bytes], dict[str, str]]:
    if json_body is not None:
        return (
            _json.dumps(json_body, separators=(",", ":"), ensure_ascii=False).encode("utf-8"),
            {"content-type": "application/json"},
        )
    if content is not None:
        if isinstance(content, bytes):
            return content, {}
        if isinstance(content, str):
            return content.encode("utf-8"), {}
        return bytes(content), {}
    if data is not None:
        if isinstance(data, bytes):
            return data, {}
        if isinstance(data, str):
            return data.encode("utf-8"), {}
        if isinstance(data, Mapping):
            return urlencode(_without_none(data), doseq=True).encode("utf-8"), {
                "content-type": "application/x-www-form-urlencoded"
            }
        return bytes(data), {}
    return None, {}


async def _await_with_timeout(awaitable: Any, timeout: Optional[float]) -> Any:
    if timeout is None:
        return await awaitable
    return await asyncio.wait_for(awaitable, timeout)


def _frame_bytes(frame_type: int, flags: int, stream_id: int, payload: bytes) -> bytes:
    if len(payload) > 0xFFFFFF:
        raise H2CProtocolError("HTTP/2 frame payload too large")
    return (
        len(payload).to_bytes(3, "big")
        + bytes([frame_type, flags])
        + (stream_id & 0x7FFFFFFF).to_bytes(4, "big")
        + payload
    )


def _encode_int(value: int, prefix_bits: int, prefix: int = 0) -> bytes:
    max_prefix = (1 << prefix_bits) - 1
    if value < max_prefix:
        return bytes([prefix | value])
    out = bytearray([prefix | max_prefix])
    value -= max_prefix
    while value >= 128:
        out.append((value % 128) + 128)
        value //= 128
    out.append(value)
    return bytes(out)


def _decode_int(data: bytes, pos: int, prefix_bits: int) -> tuple[int, int]:
    max_prefix = (1 << prefix_bits) - 1
    value = data[pos] & max_prefix
    pos += 1
    if value < max_prefix:
        return value, pos
    shift = 0
    while True:
        if pos >= len(data):
            raise H2CError("truncated HPACK integer")
        b = data[pos]
        pos += 1
        value += (b & 0x7F) << shift
        if (b & 0x80) == 0:
            return value, pos
        shift += 7


_HUFFMAN_CODES: tuple[tuple[int, int], ...] = (
    (13, 0x1ff8), (23, 0x007fffd8), (28, 0x0fffffe2), (28, 0x0fffffe3),
    (28, 0x0fffffe4), (28, 0x0fffffe5), (28, 0x0fffffe6), (28, 0x0fffffe7),
    (28, 0x0fffffe8), (24, 0x00ffffea), (30, 0x3ffffffc), (28, 0x0fffffe9),
    (28, 0x0fffffea), (30, 0x3ffffffd), (28, 0x0fffffeb), (28, 0x0fffffec),
    (28, 0x0fffffed), (28, 0x0fffffee), (28, 0x0fffffef), (28, 0x0ffffff0),
    (28, 0x0ffffff1), (28, 0x0ffffff2), (30, 0x3ffffffe), (28, 0x0ffffff3),
    (28, 0x0ffffff4), (28, 0x0ffffff5), (28, 0x0ffffff6), (28, 0x0ffffff7),
    (28, 0x0ffffff8), (28, 0x0ffffff9), (28, 0x0ffffffa), (28, 0x0ffffffb),
    (6, 0x14), (10, 0x3f8), (10, 0x3f9), (12, 0xffa),
    (13, 0x1ff9), (6, 0x15), (8, 0xf8), (11, 0x7fa),
    (10, 0x3fa), (10, 0x3fb), (8, 0xf9), (11, 0x7fb),
    (8, 0xfa), (6, 0x16), (6, 0x17), (6, 0x18),
    (5, 0x0), (5, 0x1), (5, 0x2), (6, 0x19),
    (6, 0x1a), (6, 0x1b), (6, 0x1c), (6, 0x1d),
    (6, 0x1e), (6, 0x1f), (7, 0x5c), (8, 0xfb),
    (15, 0x7ffc), (6, 0x20), (12, 0xffb), (10, 0x3fc),
    (13, 0x1ffa), (6, 0x21), (7, 0x5d), (7, 0x5e),
    (7, 0x5f), (7, 0x60), (7, 0x61), (7, 0x62),
    (7, 0x63), (7, 0x64), (7, 0x65), (7, 0x66),
    (7, 0x67), (7, 0x68), (7, 0x69), (7, 0x6a),
    (7, 0x6b), (7, 0x6c), (7, 0x6d), (7, 0x6e),
    (7, 0x6f), (7, 0x70), (7, 0x71), (7, 0x72),
    (8, 0xfc), (7, 0x73), (8, 0xfd), (13, 0x1ffb),
    (19, 0x7fff0), (13, 0x1ffc), (14, 0x3ffc), (6, 0x22),
    (15, 0x7ffd), (5, 0x3), (6, 0x23), (5, 0x4),
    (6, 0x24), (5, 0x5), (6, 0x25), (6, 0x26),
    (6, 0x27), (5, 0x6), (7, 0x74), (7, 0x75),
    (6, 0x28), (6, 0x29), (6, 0x2a), (5, 0x7),
    (6, 0x2b), (7, 0x76), (6, 0x2c), (5, 0x8),
    (5, 0x9), (6, 0x2d), (7, 0x77), (7, 0x78),
    (7, 0x79), (7, 0x7a), (7, 0x7b), (15, 0x7ffe),
    (11, 0x7fc), (14, 0x3ffd), (13, 0x1ffd), (28, 0x0ffffffc),
    (20, 0xfffe6), (22, 0x003fffd2), (20, 0xfffe7), (20, 0xfffe8),
    (22, 0x003fffd3), (22, 0x003fffd4), (22, 0x003fffd5), (23, 0x007fffd9),
    (22, 0x003fffd6), (23, 0x007fffda), (23, 0x007fffdb), (23, 0x007fffdc),
    (23, 0x007fffdd), (23, 0x007fffde), (24, 0x00ffffeb), (23, 0x007fffdf),
    (24, 0x00ffffec), (24, 0x00ffffed), (22, 0x003fffd7), (23, 0x007fffe0),
    (24, 0x00ffffee), (23, 0x007fffe1), (23, 0x007fffe2), (23, 0x007fffe3),
    (23, 0x007fffe4), (21, 0x001fffdc), (22, 0x003fffd8), (23, 0x007fffe5),
    (22, 0x003fffd9), (23, 0x007fffe6), (23, 0x007fffe7), (24, 0x00ffffef),
    (22, 0x003fffda), (21, 0x001fffdd), (20, 0xfffe9), (22, 0x003fffdb),
    (22, 0x003fffdc), (23, 0x007fffe8), (23, 0x007fffe9), (21, 0x001fffde),
    (23, 0x007fffea), (22, 0x003fffdd), (22, 0x003fffde), (24, 0x00fffff0),
    (21, 0x001fffdf), (22, 0x003fffdf), (23, 0x007fffeb), (23, 0x007fffec),
    (21, 0x001fffe0), (21, 0x001fffe1), (22, 0x003fffe0), (21, 0x001fffe2),
    (23, 0x007fffed), (22, 0x003fffe1), (23, 0x007fffee), (23, 0x007fffef),
    (20, 0xfffea), (22, 0x003fffe2), (22, 0x003fffe3), (22, 0x003fffe4),
    (23, 0x007ffff0), (22, 0x003fffe5), (22, 0x003fffe6), (23, 0x007ffff1),
    (26, 0x03ffffe0), (26, 0x03ffffe1), (20, 0xfffeb), (19, 0x7fff1),
    (22, 0x003fffe7), (23, 0x007ffff2), (22, 0x003fffe8), (25, 0x01ffffec),
    (26, 0x03ffffe2), (26, 0x03ffffe3), (26, 0x03ffffe4), (27, 0x07ffffde),
    (27, 0x07ffffdf), (26, 0x03ffffe5), (24, 0x00fffff1), (25, 0x01ffffed),
    (19, 0x7fff2), (21, 0x001fffe3), (26, 0x03ffffe6), (27, 0x07ffffe0),
    (27, 0x07ffffe1), (26, 0x03ffffe7), (27, 0x07ffffe2), (24, 0x00fffff2),
    (21, 0x001fffe4), (21, 0x001fffe5), (26, 0x03ffffe8), (26, 0x03ffffe9),
    (28, 0x0ffffffd), (27, 0x07ffffe3), (27, 0x07ffffe4), (27, 0x07ffffe5),
    (20, 0xfffec), (24, 0x00fffff3), (20, 0xfffed), (21, 0x001fffe6),
    (22, 0x003fffe9), (21, 0x001fffe7), (21, 0x001fffe8), (23, 0x007ffff3),
    (22, 0x003fffea), (22, 0x003fffeb), (25, 0x01ffffee), (25, 0x01ffffef),
    (24, 0x00fffff4), (24, 0x00fffff5), (26, 0x03ffffea), (23, 0x007ffff4),
    (26, 0x03ffffeb), (27, 0x07ffffe6), (26, 0x03ffffec), (26, 0x03ffffed),
    (27, 0x07ffffe7), (27, 0x07ffffe8), (27, 0x07ffffe9), (27, 0x07ffffea),
    (27, 0x07ffffeb), (28, 0x0ffffffe), (27, 0x07ffffec), (27, 0x07ffffed),
    (27, 0x07ffffee), (27, 0x07ffffef), (27, 0x07fffff0), (26, 0x03ffffee),
    (30, 0x3fffffff),
)

_HUFFMAN_ROOT: dict[int, Any] | None = None


def _huffman_root() -> dict[int, Any]:
    global _HUFFMAN_ROOT
    if _HUFFMAN_ROOT is not None:
        return _HUFFMAN_ROOT
    root: dict[int, Any] = {}
    for symbol, (nbits, code) in enumerate(_HUFFMAN_CODES):
        node = root
        for shift in range(nbits - 1, -1, -1):
            bit = (code >> shift) & 1
            node = node.setdefault(bit, {})
        node["sym"] = symbol
    _HUFFMAN_ROOT = root
    return root


def _decode_huffman(raw: bytes) -> bytes:
    root = _huffman_root()
    node = root
    out = bytearray()
    pending_bits = 0
    pending_value = 0
    for byte in raw:
        for shift in range(7, -1, -1):
            bit = (byte >> shift) & 1
            if bit not in node:
                raise H2CError("invalid HPACK Huffman code")
            node = node[bit]
            pending_bits += 1
            pending_value = (pending_value << 1) | bit
            symbol = node.get("sym")
            if symbol is not None:
                if symbol == 256:
                    raise H2CError("HPACK Huffman EOS symbol inside string")
                out.append(symbol)
                node = root
                pending_bits = 0
                pending_value = 0
    if node is not root:
        if pending_bits > 7 or pending_value != (1 << pending_bits) - 1:
            raise H2CError("invalid HPACK Huffman padding")
    return bytes(out)


def _encode_string(value: str) -> bytes:
    raw = value.encode("utf-8")
    return _encode_int(len(raw), 7, 0) + raw


def _decode_string(data: bytes, pos: int) -> tuple[str, int]:
    if pos >= len(data):
        raise H2CError("truncated HPACK string")
    huffman = (data[pos] & 0x80) != 0
    length, pos = _decode_int(data, pos, 7)
    raw = data[pos : pos + length]
    if len(raw) != length:
        raise H2CError("truncated HPACK string body")
    if huffman:
        raw = _decode_huffman(raw)
    return raw.decode("utf-8"), pos + length


_STATIC_TABLE: list[tuple[str, str]] = [
    (":authority", ""),
    (":method", "GET"),
    (":method", "POST"),
    (":path", "/"),
    (":path", "/index.html"),
    (":scheme", "http"),
    (":scheme", "https"),
    (":status", "200"),
    (":status", "204"),
    (":status", "206"),
    (":status", "304"),
    (":status", "400"),
    (":status", "404"),
    (":status", "500"),
    ("accept-charset", ""),
    ("accept-encoding", "gzip, deflate"),
    ("accept-language", ""),
    ("accept-ranges", ""),
    ("accept", ""),
    ("access-control-allow-origin", ""),
    ("age", ""),
    ("allow", ""),
    ("authorization", ""),
    ("cache-control", ""),
    ("content-disposition", ""),
    ("content-encoding", ""),
    ("content-language", ""),
    ("content-length", ""),
    ("content-location", ""),
    ("content-range", ""),
    ("content-type", ""),
    ("cookie", ""),
    ("date", ""),
    ("etag", ""),
    ("expect", ""),
    ("expires", ""),
    ("from", ""),
    ("host", ""),
    ("if-match", ""),
    ("if-modified-since", ""),
    ("if-none-match", ""),
    ("if-range", ""),
    ("if-unmodified-since", ""),
    ("last-modified", ""),
    ("link", ""),
    ("location", ""),
    ("max-forwards", ""),
    ("proxy-authenticate", ""),
    ("proxy-authorization", ""),
    ("range", ""),
    ("referer", ""),
    ("refresh", ""),
    ("retry-after", ""),
    ("server", ""),
    ("set-cookie", ""),
    ("strict-transport-security", ""),
    ("transfer-encoding", ""),
    ("user-agent", ""),
    ("vary", ""),
    ("via", ""),
    ("www-authenticate", ""),
]

_STATIC_EXACT: dict[tuple[str, str], int] = {
    header: index + 1 for index, header in enumerate(_STATIC_TABLE)
}
_STATIC_NAME: dict[str, int] = {}
for _index, (_name, _value) in enumerate(_STATIC_TABLE, start=1):
    _STATIC_NAME.setdefault(_name, _index)


def _encode_headers(headers: list[tuple[str, str]]) -> bytes:
    block = bytearray()
    for name, value in headers:
        exact = _STATIC_EXACT.get((name, value))
        if exact is not None:
            block.extend(_encode_int(exact, 7, 0x80))
            continue
        name_index = _STATIC_NAME.get(name)
        if name_index is None:
            block.append(0x00)  # literal header field without indexing, new name
            block.extend(_encode_string(name))
        else:
            block.extend(_encode_int(name_index, 4, 0x00))
        block.extend(_encode_string(value))
    return bytes(block)


class _HpackDecoder:
    def __init__(self) -> None:
        self._dynamic: list[tuple[str, str]] = []
        self._max_size = 4096
        self._size = 0

    def decode(self, block: bytes) -> list[tuple[str, str]]:
        headers: list[tuple[str, str]] = []
        pos = 0
        while pos < len(block):
            b = block[pos]
            if b & 0x80:
                index, pos = _decode_int(block, pos, 7)
                headers.append(self._lookup(index))
            elif b & 0x40:
                index, pos = _decode_int(block, pos, 6)
                name, pos = self._name(block, pos, index)
                value, pos = _decode_string(block, pos)
                headers.append((name, value))
                self._insert(name, value)
            elif b & 0x20:
                size, pos = _decode_int(block, pos, 5)
                self._resize(size)
            else:
                prefix = 4
                index, pos = _decode_int(block, pos, prefix)
                name, pos = self._name(block, pos, index)
                value, pos = _decode_string(block, pos)
                headers.append((name, value))
        return headers

    def _name(self, block: bytes, pos: int, index: int) -> tuple[str, int]:
        if index == 0:
            return _decode_string(block, pos)
        return self._lookup(index)[0], pos

    def _lookup(self, index: int) -> tuple[str, str]:
        if index <= 0:
            raise H2CError("invalid HPACK index 0")
        if index <= len(_STATIC_TABLE):
            return _STATIC_TABLE[index - 1]
        dyn = index - len(_STATIC_TABLE) - 1
        if dyn < 0 or dyn >= len(self._dynamic):
            raise H2CError(f"invalid HPACK dynamic index {index}")
        return self._dynamic[dyn]

    def _insert(self, name: str, value: str) -> None:
        size = len(name.encode("utf-8")) + len(value.encode("utf-8")) + 32
        if size > self._max_size:
            self._dynamic.clear()
            self._size = 0
            return
        self._dynamic.insert(0, (name, value))
        self._size += size
        self._evict()

    def _resize(self, size: int) -> None:
        if size > _MAX_HEADER_TABLE_SIZE:
            raise H2CProtocolError("HPACK dynamic table size exceeds local limit")
        self._max_size = size
        self._evict()

    def _evict(self) -> None:
        while self._size > self._max_size and self._dynamic:
            name, value = self._dynamic.pop()
            self._size -= len(name.encode("utf-8")) + len(value.encode("utf-8")) + 32


class H2CClient:
    """Stdlib-only httpx-like HTTP/2 client.

    The runtime is generated with the OpenAPI client so adopters do not need an
    extra HTTP/2 dependency. It uses cleartext prior-knowledge h2c for http://
    origins, TLS ALPN h2 for https:// origins, keeps one reusable HTTP/2
    connection per origin, opens many streams on that connection, and exposes
    both unary request() and bidirectional stream() APIs.
    """

    def __init__(
        self,
        *,
        timeout: Optional[float] = _DEFAULT_TIMEOUT,
        max_connections_per_origin: int = 1,
        max_response_bytes: Optional[int] = _DEFAULT_MAX_RESPONSE_BYTES,
        ssl_context: Optional[ssl.SSLContext] = None,
    ) -> None:
        if max_response_bytes is not None and max_response_bytes < 0:
            raise ValueError("max_response_bytes must be non-negative or None")
        self._timeout = timeout
        self._max_connections_per_origin = max(1, max_connections_per_origin)
        self._max_response_bytes = max_response_bytes
        self._ssl_context = ssl_context
        self._connections: dict[tuple[str, str, int], list[H2CConnection]] = {}
        self._lock = threading.RLock()
        self._closed = False

    def __enter__(self) -> "H2CClient":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        self.close()

    def request(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        json: Any = None,
        data: Any = None,
        content: Any = None,
        timeout: Optional[float] = None,
    ) -> H2CResponse:
        body, body_headers = _body_bytes(json, data, content)
        merged_headers = {**body_headers, **dict(_without_none(headers))}
        stream = self.open_stream(
            method,
            url,
            params=params,
            headers=merged_headers,
            timeout=timeout,
            end_stream=body is None,
        )
        try:
            if body is not None:
                stream.send_data(body, end_stream=True)
            return stream.read_response()
        finally:
            stream.close()

    def get(self, url: str, **kwargs: Any) -> H2CResponse:
        return self.request("GET", url, **kwargs)

    def post(self, url: str, **kwargs: Any) -> H2CResponse:
        return self.request("POST", url, **kwargs)

    def put(self, url: str, **kwargs: Any) -> H2CResponse:
        return self.request("PUT", url, **kwargs)

    def patch(self, url: str, **kwargs: Any) -> H2CResponse:
        return self.request("PATCH", url, **kwargs)

    def delete(self, url: str, **kwargs: Any) -> H2CResponse:
        return self.request("DELETE", url, **kwargs)

    def stream(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        timeout: Optional[float] = None,
    ) -> "H2CStream":
        return self.open_stream(method, url, params=params, headers=headers, timeout=timeout, end_stream=False)

    def open_stream(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        timeout: Optional[float] = None,
        end_stream: bool = False,
    ) -> "H2CStream":
        full_url = _url_with_params(url, params)
        parsed = urlsplit(full_url)
        conn = self._connection_for(parsed, self._timeout if timeout is None else timeout)
        return conn.open_stream(method, full_url, headers=headers, end_stream=end_stream)

    def close(self) -> None:
        with self._lock:
            self._closed = True
            conns = [conn for group in self._connections.values() for conn in group]
            self._connections.clear()
        for conn in conns:
            conn.close()

    def _connection_for(self, parsed: Any, timeout: Optional[float]) -> "H2CConnection":
        if parsed.scheme not in {"http", "https"}:
            raise H2CError("HTTP/2 runtime requires an absolute http:// or https:// URL")
        if parsed.hostname is None:
            raise H2CError("absolute http or https URL required")
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        key = (parsed.scheme, parsed.hostname, port)
        with self._lock:
            if self._closed:
                raise H2CConnectionClosed("client is closed")
            group = self._connections.setdefault(key, [])
            for conn in group:
                if conn.can_open_stream():
                    return conn
            if len(group) >= self._max_connections_per_origin:
                return min(group, key=lambda conn: conn.open_stream_count)
            conn = H2CConnection(
                parsed.scheme,
                parsed.hostname,
                port,
                timeout=timeout,
                max_response_bytes=self._max_response_bytes,
                ssl_context=self._ssl_context,
            )
            conn.connect()
            group.append(conn)
            return conn


class H2CConnection:
    def __init__(
        self,
        scheme: str,
        host: str,
        port: int,
        *,
        timeout: Optional[float] = None,
        max_response_bytes: Optional[int] = _DEFAULT_MAX_RESPONSE_BYTES,
        ssl_context: Optional[ssl.SSLContext] = None,
    ) -> None:
        if max_response_bytes is not None and max_response_bytes < 0:
            raise ValueError("max_response_bytes must be non-negative or None")
        self._scheme = scheme
        self._host = host
        self._port = port
        self._timeout = timeout
        self._max_response_bytes = max_response_bytes
        self._ssl_context = ssl_context
        self._sock: Optional[socket.socket] = None
        self._next_stream_id = 1
        self._streams: dict[int, H2CStream] = {}
        self._decoder = _HpackDecoder()
        self._conn_send_window = 65535
        self._remote_initial_window = 65535
        self._max_frame = 16384
        self._max_concurrent_streams = 100
        self._closed = False
        self._goaway_last_stream_id: Optional[int] = None
        self._lock = threading.RLock()
        self._read_lock = threading.Lock()
        self._send_lock = threading.Lock()

    @property
    def open_stream_count(self) -> int:
        with self._lock:
            return len(self._streams)

    def can_open_stream(self) -> bool:
        with self._lock:
            return (
                not self._closed
                and self._goaway_last_stream_id is None
                and len(self._streams) < self._max_concurrent_streams
            )

    def connect(self) -> None:
        with self._lock:
            if self._sock is not None:
                return
            if self._closed:
                raise H2CConnectionClosed("connection is closed")
            try:
                raw_sock = socket.create_connection((self._host, self._port), timeout=self._timeout)
                raw_sock.settimeout(self._timeout)
                if self._scheme == "https":
                    context = self._ssl_context or ssl.create_default_context()
                    context.set_alpn_protocols(["h2"])
                    sock = context.wrap_socket(raw_sock, server_hostname=self._host)
                    if sock.selected_alpn_protocol() != "h2":
                        sock.close()
                        raise H2CProtocolError("TLS ALPN did not negotiate h2")
                else:
                    sock = raw_sock
                sock.settimeout(self._timeout)
                self._sock = sock
                sock.sendall(_CLIENT_PREFACE + _frame_bytes(_FRAME_SETTINGS, 0, 0, _CLIENT_SETTINGS))
            except socket.timeout as exc:
                self._sock = None
                raise H2CTimeout("timed out connecting HTTP/2 socket") from exc
            except OSError as exc:
                self._sock = None
                raise H2CConnectionClosed(f"failed to connect HTTP/2 socket: {exc}") from exc

    def close(self) -> None:
        with self._lock:
            self._closed = True
            streams = list(self._streams.values())
            self._streams.clear()
            sock = self._sock
            self._sock = None
        for stream in streams:
            stream._mark_error(H2CConnectionClosed("connection closed"))
        if sock is not None:
            try:
                sock.close()
            except OSError:
                pass

    def open_stream(
        self,
        method: str,
        url: str,
        *,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None,
        end_stream: bool,
    ) -> "H2CStream":
        self.connect()
        parsed = urlsplit(url)
        with self._lock:
            if not self.can_open_stream():
                raise H2CConnectionClosed("connection cannot open more streams")
            stream_id = self._next_stream_id
            self._next_stream_id += 2
            stream = H2CStream(self, stream_id)
            stream._send_window = self._remote_initial_window
            self._streams[stream_id] = stream

        request_headers = [
            (":method", _validate_method(method)),
            (":scheme", parsed.scheme),
            (":authority", _authority(parsed)),
            (":path", _request_path(parsed)),
            ("accept", "application/json"),
        ]
        request_headers.extend(_header_pairs(headers))
        self._send_frame(
            _FRAME_HEADERS,
            _FLAG_END_HEADERS | (_FLAG_END_STREAM if end_stream else 0),
            stream_id,
            _encode_headers(request_headers),
        )
        if end_stream:
            stream._request_ended = True
        return stream

    def send_data(self, stream: "H2CStream", data: bytes | str, *, end_stream: bool = False) -> None:
        body = data.encode("utf-8") if isinstance(data, str) else bytes(data)
        if not body:
            if end_stream:
                self._send_frame(_FRAME_DATA, _FLAG_END_STREAM, stream.stream_id, b"")
                stream._request_ended = True
            return

        view = memoryview(body)
        offset = 0
        while offset < len(view):
            with self._lock:
                stream._raise_if_error()
                if stream._closed:
                    raise H2CConnectionClosed("stream is closed")
                size = min(
                    len(view) - offset,
                    self._max_frame,
                    stream._send_window,
                    self._conn_send_window,
                )
                if size > 0:
                    stream._send_window -= size
                    self._conn_send_window -= size
            if size <= 0:
                self.receive_one()
                continue
            final = end_stream and offset + size == len(view)
            self._send_frame(
                _FRAME_DATA,
                _FLAG_END_STREAM if final else 0,
                stream.stream_id,
                view[offset : offset + size].tobytes(),
            )
            if final:
                stream._request_ended = True
            offset += size

    def end_stream(self, stream: "H2CStream") -> None:
        self.send_data(stream, b"", end_stream=True)

    def read_chunk(self, stream: "H2CStream") -> Optional[bytes]:
        while True:
            with self._lock:
                stream._raise_if_error()
                if stream._chunks:
                    return stream._chunks.pop(0)
                if stream._response_ended:
                    return None
            with self._read_lock:
                with self._lock:
                    stream._raise_if_error()
                    if stream._chunks:
                        return stream._chunks.pop(0)
                    if stream._response_ended:
                        return None
                self._receive_one_unlocked()

    def receive_one(self) -> None:
        with self._read_lock:
            self._receive_one_unlocked()

    def _receive_one_unlocked(self) -> None:
        frame_type, flags, stream_id, payload = self._read_frame()
        self._handle_frame(frame_type, flags, stream_id, payload)

    def remove_stream(self, stream_id: int) -> None:
        with self._lock:
            self._streams.pop(stream_id, None)

    def _send_frame(self, frame_type: int, flags: int, stream_id: int, payload: bytes) -> None:
        frame = _frame_bytes(frame_type, flags, stream_id, payload)
        with self._send_lock:
            sock = self._sock
            if sock is None:
                raise H2CConnectionClosed("connection is closed")
            try:
                sock.sendall(frame)
            except socket.timeout as exc:
                raise H2CTimeout("timed out writing h2c frame") from exc
            except OSError as exc:
                self.close()
                raise H2CConnectionClosed(f"failed writing h2c frame: {exc}") from exc

    def _recv_exact(self, n: int) -> bytes:
        sock = self._sock
        if sock is None:
            raise H2CConnectionClosed("connection is closed")
        out = bytearray()
        try:
            while len(out) < n:
                chunk = sock.recv(n - len(out))
                if not chunk:
                    raise H2CConnectionClosed("connection closed before stream ended")
                out.extend(chunk)
        except socket.timeout as exc:
            raise H2CTimeout("timed out reading h2c frame") from exc
        except OSError as exc:
            self.close()
            raise H2CConnectionClosed(f"failed reading h2c frame: {exc}") from exc
        return bytes(out)

    def _read_frame(self) -> tuple[int, int, int, bytes]:
        header = self._recv_exact(9)
        length = int.from_bytes(header[:3], "big")
        if length > _MAX_INBOUND_FRAME:
            raise H2CProtocolError("HTTP/2 inbound frame exceeds local limit")
        frame_type = header[3]
        flags = header[4]
        stream_id = int.from_bytes(header[5:9], "big") & 0x7FFFFFFF
        return frame_type, flags, stream_id, self._recv_exact(length)

    def _handle_frame(self, frame_type: int, flags: int, stream_id: int, payload: bytes) -> None:
        if frame_type == _FRAME_SETTINGS:
            self._handle_settings(flags, payload)
        elif frame_type == _FRAME_HEADERS:
            self._handle_headers_frame(flags, stream_id, payload)
        elif frame_type == _FRAME_PUSH_PROMISE:
            self._handle_push_promise(flags, stream_id, payload)
        elif frame_type == _FRAME_DATA:
            self._handle_data_frame(flags, stream_id, payload)
        elif frame_type == _FRAME_WINDOW_UPDATE:
            self._handle_window_update(stream_id, payload)
        elif frame_type == _FRAME_RST_STREAM:
            self._handle_rst_stream(stream_id, payload)
        elif frame_type == _FRAME_GOAWAY:
            self._handle_goaway(payload)
        elif frame_type == _FRAME_PING and not (flags & _FLAG_ACK):
            self._send_frame(_FRAME_PING, _FLAG_ACK, 0, payload[:8].ljust(8, b"\0"))
        elif frame_type == _FRAME_PRIORITY:
            return

    def _handle_settings(self, flags: int, payload: bytes) -> None:
        if flags & _FLAG_ACK:
            return
        if len(payload) % 6 != 0:
            raise H2CProtocolError("invalid SETTINGS frame")
        initial_window: Optional[int] = None
        for i in range(0, len(payload), 6):
            setting = int.from_bytes(payload[i : i + 2], "big")
            value = int.from_bytes(payload[i + 2 : i + 6], "big")
            if setting == 3:
                self._max_concurrent_streams = max(1, value)
            elif setting == 4:
                if value > _MAX_FLOW_CONTROL_WINDOW:
                    raise H2CProtocolError("invalid SETTINGS_INITIAL_WINDOW_SIZE")
                initial_window = value
            elif setting == 5:
                if value < 16384 or value > 16777215:
                    raise H2CProtocolError("invalid SETTINGS_MAX_FRAME_SIZE")
                self._max_frame = value
        if initial_window is not None:
            with self._lock:
                delta = initial_window - self._remote_initial_window
                self._remote_initial_window = initial_window
                for stream in self._streams.values():
                    stream._send_window += delta
        self._send_frame(_FRAME_SETTINGS, _FLAG_ACK, 0, b"")

    def _handle_headers_frame(self, flags: int, stream_id: int, payload: bytes) -> None:
        block = self._headers_payload(flags, stream_id, payload)
        headers = self._decoder.decode(block)
        with self._lock:
            stream = self._streams.get(stream_id)
            if stream is None:
                return
            stream._handle_headers(headers)
            if flags & _FLAG_END_STREAM:
                stream._response_ended = True

    def _handle_data_frame(self, flags: int, stream_id: int, payload: bytes) -> None:
        data = self._data_payload(flags, payload)
        with self._lock:
            stream = self._streams.get(stream_id)
            if stream is None:
                return
            if data:
                stream._chunks.append(data)
        if data:
            increment = len(data).to_bytes(4, "big")
            self._send_frame(_FRAME_WINDOW_UPDATE, 0, 0, increment)
            self._send_frame(_FRAME_WINDOW_UPDATE, 0, stream_id, increment)
        if flags & _FLAG_END_STREAM:
            with self._lock:
                stream = self._streams.get(stream_id)
                if stream is not None:
                    stream._response_ended = True

    def _handle_window_update(self, stream_id: int, payload: bytes) -> None:
        if len(payload) != 4:
            raise H2CProtocolError("invalid WINDOW_UPDATE frame")
        inc = int.from_bytes(payload, "big") & 0x7FFFFFFF
        if inc == 0:
            raise H2CProtocolError("WINDOW_UPDATE increment must be non-zero")
        with self._lock:
            if stream_id == 0:
                next_window = self._conn_send_window + inc
                if next_window > _MAX_FLOW_CONTROL_WINDOW:
                    raise H2CProtocolError("connection flow-control window overflow")
                self._conn_send_window = next_window
            else:
                stream = self._streams.get(stream_id)
                if stream is not None:
                    next_window = stream._send_window + inc
                    if next_window > _MAX_FLOW_CONTROL_WINDOW:
                        raise H2CProtocolError("stream flow-control window overflow")
                    stream._send_window = next_window

    def _handle_rst_stream(self, stream_id: int, payload: bytes) -> None:
        code = int.from_bytes(payload[-4:], "big") if len(payload) >= 4 else 0
        with self._lock:
            stream = self._streams.pop(stream_id, None)
        if stream is not None:
            stream._mark_error(H2CProtocolError(f"stream reset: {code}"))

    def _handle_goaway(self, payload: bytes) -> None:
        last_stream_id = int.from_bytes(payload[:4], "big") & 0x7FFFFFFF if len(payload) >= 4 else 0
        code = int.from_bytes(payload[4:8], "big") if len(payload) >= 8 else 0
        with self._lock:
            self._goaway_last_stream_id = last_stream_id
            streams = [s for sid, s in self._streams.items() if sid > last_stream_id]
        for stream in streams:
            stream._mark_error(H2CConnectionClosed(f"connection terminated: {code}"))

    def _handle_push_promise(self, flags: int, stream_id: int, payload: bytes) -> None:
        pos = 0
        pad_len = 0
        if flags & _FLAG_PADDED:
            if not payload:
                raise H2CProtocolError("padded PUSH_PROMISE frame missing pad length")
            pad_len = payload[0]
            pos = 1
        if len(payload) < pos + 4 + pad_len:
            raise H2CProtocolError("truncated PUSH_PROMISE frame")
        promised_id = int.from_bytes(payload[pos : pos + 4], "big") & 0x7FFFFFFF
        if promised_id:
            self._send_frame(_FRAME_RST_STREAM, 0, promised_id, _ERROR_REFUSED_STREAM.to_bytes(4, "big"))

    def _headers_payload(self, flags: int, stream_id: int, payload: bytes) -> bytes:
        block = self._strip_headers_prefix(flags, payload)
        if len(block) > _MAX_HEADER_BLOCK:
            raise H2CProtocolError("HTTP/2 header block exceeds local limit")
        while not (flags & _FLAG_END_HEADERS):
            frame_type, flags, cont_stream_id, cont_payload = self._read_frame()
            if frame_type != _FRAME_CONTINUATION or cont_stream_id != stream_id:
                raise H2CProtocolError("expected CONTINUATION frame")
            block += cont_payload
            if len(block) > _MAX_HEADER_BLOCK:
                raise H2CProtocolError("HTTP/2 header block exceeds local limit")
        return block

    def _strip_headers_prefix(self, flags: int, payload: bytes) -> bytes:
        pos = 0
        pad_len = 0
        if flags & _FLAG_PADDED:
            if not payload:
                raise H2CProtocolError("padded HEADERS frame missing pad length")
            pad_len = payload[0]
            pos = 1
        if flags & _FLAG_PRIORITY:
            if len(payload) < pos + 5:
                raise H2CProtocolError("truncated priority section in HEADERS frame")
            pos += 5
        if len(payload) < pos + pad_len:
            raise H2CProtocolError("invalid HEADERS padding")
        if pad_len:
            return payload[pos:-pad_len]
        return payload[pos:]

    def _data_payload(self, flags: int, payload: bytes) -> bytes:
        if flags & _FLAG_PADDED:
            if not payload:
                raise H2CProtocolError("padded DATA frame missing pad length")
            pad_len = payload[0]
            if len(payload) < 1 + pad_len:
                raise H2CProtocolError("invalid DATA padding")
            return payload[1:-pad_len] if pad_len else payload[1:]
        return payload


class H2CStream:
    def __init__(self, connection: H2CConnection, stream_id: int) -> None:
        self._connection = connection
        self._stream_id = stream_id
        self._chunks: list[bytes] = []
        self._response_headers: dict[str, str] = {}
        self._response_ended = False
        self._request_ended = False
        self._closed = False
        self._error: Optional[BaseException] = None
        self._send_window = 65535
        self.status_code: Optional[int] = None

    @property
    def stream_id(self) -> int:
        return self._stream_id

    @property
    def headers(self) -> dict[str, str]:
        return dict(self._response_headers)

    def __enter__(self) -> "H2CStream":
        return self

    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        self.close()

    def close(self) -> None:
        if self._closed:
            return
        self._closed = True
        self._connection.remove_stream(self._stream_id)

    def send_json(self, value: Any, *, end_stream: bool = False) -> None:
        self.send_data(
            _json.dumps(value, separators=(",", ":"), ensure_ascii=False).encode("utf-8"),
            end_stream=end_stream,
        )

    def send_data(self, data: bytes | str, *, end_stream: bool = False) -> None:
        self._raise_if_error()
        if self._request_ended:
            raise H2CProtocolError("request body already ended")
        self._connection.send_data(self, data, end_stream=end_stream)

    def end_request(self) -> None:
        self._raise_if_error()
        if not self._request_ended:
            self._connection.end_stream(self)

    def read_chunk(self) -> Optional[bytes]:
        self._raise_if_error()
        return self._connection.read_chunk(self)

    def iter_bytes(self) -> Iterator[bytes]:
        while True:
            chunk = self.read_chunk()
            if chunk is None:
                break
            yield chunk

    def iter_json_lines(self) -> Iterator[Any]:
        buf = b""
        for chunk in self.iter_bytes():
            buf += chunk
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                if line.strip():
                    yield _json.loads(line)
        if buf.strip():
            yield _json.loads(buf)

    def read_response(self) -> H2CResponse:
        chunks = []
        total = 0
        limit = self._connection._max_response_bytes
        for chunk in self.iter_bytes():
            chunks.append(chunk)
            total += len(chunk)
            if limit is not None and total > limit:
                raise H2CProtocolError("response body exceeds local limit")
        content = b"".join(chunks)
        status = self.status_code or 0
        if status == 0:
            raise H2CProtocolError("response ended without :status")
        return H2CResponse(status, dict(self._response_headers), content)

    def _handle_headers(self, headers: list[tuple[str, str]]) -> None:
        for key, value in headers:
            if key == ":status":
                self.status_code = int(value)
            elif not key.startswith(":"):
                name = key.lower()
                _validate_header_pair(name, value)
                self._response_headers[name] = value

    def _mark_error(self, error: BaseException) -> None:
        self._error = error
        self._response_ended = True
        self._closed = True

    def _raise_if_error(self) -> None:
        if self._error is not None:
            raise self._error


class _AsyncH2CStreamContext:
    def __init__(
        self,
        client: "AsyncH2CClient",
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None,
        timeout: Optional[float],
    ) -> None:
        self._client = client
        self._method = method
        self._url = url
        self._params = params
        self._headers = headers
        self._timeout = timeout
        self._stream: Optional[AsyncH2CStream] = None

    def __await__(self) -> Any:
        return self._open().__await__()

    async def __aenter__(self) -> "AsyncH2CStream":
        return await self._open()

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        if self._stream is not None:
            await self._stream.aclose()

    async def _open(self) -> "AsyncH2CStream":
        if self._stream is None:
            self._stream = await self._client.open_stream(
                self._method,
                self._url,
                params=self._params,
                headers=self._headers,
                timeout=self._timeout,
                end_stream=False,
            )
        return self._stream


class AsyncH2CClient:
    """Async stdlib-only HTTP/2 client.

    Mirrors H2CClient, using asyncio streams. http:// origins use cleartext
    prior-knowledge h2c; https:// origins require TLS ALPN h2.
    """

    def __init__(
        self,
        *,
        timeout: Optional[float] = _DEFAULT_TIMEOUT,
        max_connections_per_origin: int = 1,
        max_response_bytes: Optional[int] = _DEFAULT_MAX_RESPONSE_BYTES,
        ssl_context: Optional[ssl.SSLContext] = None,
    ) -> None:
        if max_response_bytes is not None and max_response_bytes < 0:
            raise ValueError("max_response_bytes must be non-negative or None")
        self._timeout = timeout
        self._max_connections_per_origin = max(1, max_connections_per_origin)
        self._max_response_bytes = max_response_bytes
        self._ssl_context = ssl_context
        self._connections: dict[tuple[str, str, int], list[AsyncH2CConnection]] = {}
        self._lock = asyncio.Lock()
        self._closed = False

    async def __aenter__(self) -> "AsyncH2CClient":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        await self.aclose()

    async def request(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        json: Any = None,
        data: Any = None,
        content: Any = None,
        timeout: Optional[float] = None,
    ) -> H2CResponse:
        body, body_headers = _body_bytes(json, data, content)
        merged_headers = {**body_headers, **dict(_without_none(headers))}
        stream = await self.open_stream(
            method,
            url,
            params=params,
            headers=merged_headers,
            timeout=timeout,
            end_stream=body is None,
        )
        try:
            if body is not None:
                await stream.send_data(body, end_stream=True)
            return await stream.read_response()
        finally:
            await stream.aclose()

    async def get(self, url: str, **kwargs: Any) -> H2CResponse:
        return await self.request("GET", url, **kwargs)

    async def post(self, url: str, **kwargs: Any) -> H2CResponse:
        return await self.request("POST", url, **kwargs)

    async def put(self, url: str, **kwargs: Any) -> H2CResponse:
        return await self.request("PUT", url, **kwargs)

    async def patch(self, url: str, **kwargs: Any) -> H2CResponse:
        return await self.request("PATCH", url, **kwargs)

    async def delete(self, url: str, **kwargs: Any) -> H2CResponse:
        return await self.request("DELETE", url, **kwargs)

    def stream(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        timeout: Optional[float] = None,
    ) -> "_AsyncH2CStreamContext":
        return _AsyncH2CStreamContext(self, method, url, params=params, headers=headers, timeout=timeout)

    async def open_stream(
        self,
        method: str,
        url: str,
        *,
        params: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None = None,
        timeout: Optional[float] = None,
        end_stream: bool = False,
    ) -> "AsyncH2CStream":
        full_url = _url_with_params(url, params)
        parsed = urlsplit(full_url)
        conn = await self._connection_for(parsed, self._timeout if timeout is None else timeout)
        return await conn.open_stream(method, full_url, headers=headers, end_stream=end_stream)

    async def aclose(self) -> None:
        async with self._lock:
            self._closed = True
            conns = [conn for group in self._connections.values() for conn in group]
            self._connections.clear()
        for conn in conns:
            await conn.close()

    async def close(self) -> None:
        await self.aclose()

    async def _connection_for(self, parsed: Any, timeout: Optional[float]) -> "AsyncH2CConnection":
        if parsed.scheme not in {"http", "https"}:
            raise H2CError("HTTP/2 runtime requires an absolute http:// or https:// URL")
        if parsed.hostname is None:
            raise H2CError("absolute http or https URL required")
        port = parsed.port or (443 if parsed.scheme == "https" else 80)
        key = (parsed.scheme, parsed.hostname, port)
        async with self._lock:
            if self._closed:
                raise H2CConnectionClosed("client is closed")
            group = self._connections.setdefault(key, [])
            for conn in group:
                if conn.can_open_stream():
                    return conn
            if len(group) >= self._max_connections_per_origin:
                return min(group, key=lambda conn: conn.open_stream_count)
            conn = AsyncH2CConnection(
                parsed.scheme,
                parsed.hostname,
                port,
                timeout=timeout,
                max_response_bytes=self._max_response_bytes,
                ssl_context=self._ssl_context,
            )
            await conn.connect()
            group.append(conn)
            return conn


class AsyncH2CConnection:
    def __init__(
        self,
        scheme: str,
        host: str,
        port: int,
        *,
        timeout: Optional[float] = None,
        max_response_bytes: Optional[int] = _DEFAULT_MAX_RESPONSE_BYTES,
        ssl_context: Optional[ssl.SSLContext] = None,
    ) -> None:
        if max_response_bytes is not None and max_response_bytes < 0:
            raise ValueError("max_response_bytes must be non-negative or None")
        self._scheme = scheme
        self._host = host
        self._port = port
        self._timeout = timeout
        self._max_response_bytes = max_response_bytes
        self._ssl_context = ssl_context
        self._reader: Optional[asyncio.StreamReader] = None
        self._writer: Optional[asyncio.StreamWriter] = None
        self._next_stream_id = 1
        self._streams: dict[int, AsyncH2CStream] = {}
        self._decoder = _HpackDecoder()
        self._conn_send_window = 65535
        self._remote_initial_window = 65535
        self._max_frame = 16384
        self._max_concurrent_streams = 100
        self._closed = False
        self._goaway_last_stream_id: Optional[int] = None
        self._lock = asyncio.Lock()
        self._read_lock = asyncio.Lock()
        self._send_lock = asyncio.Lock()

    @property
    def open_stream_count(self) -> int:
        return len(self._streams)

    def can_open_stream(self) -> bool:
        return (
            not self._closed
            and self._goaway_last_stream_id is None
            and len(self._streams) < self._max_concurrent_streams
        )

    async def connect(self) -> None:
        async with self._lock:
            if self._writer is not None:
                return
            if self._closed:
                raise H2CConnectionClosed("connection is closed")
            try:
                ssl_context = None
                server_hostname = None
                if self._scheme == "https":
                    ssl_context = self._ssl_context or ssl.create_default_context()
                    ssl_context.set_alpn_protocols(["h2"])
                    server_hostname = self._host
                reader, writer = await _await_with_timeout(
                    asyncio.open_connection(
                        self._host,
                        self._port,
                        ssl=ssl_context,
                        server_hostname=server_hostname,
                    ),
                    self._timeout,
                )
                if self._scheme == "https":
                    ssl_obj = writer.get_extra_info("ssl_object")
                    selected = ssl_obj.selected_alpn_protocol() if ssl_obj is not None else None
                    if selected != "h2":
                        writer.close()
                        await writer.wait_closed()
                        raise H2CProtocolError("TLS ALPN did not negotiate h2")
                self._reader = reader
                self._writer = writer
                writer.write(_CLIENT_PREFACE + _frame_bytes(_FRAME_SETTINGS, 0, 0, _CLIENT_SETTINGS))
                await _await_with_timeout(writer.drain(), self._timeout)
            except asyncio.TimeoutError as exc:
                self._reader = None
                self._writer = None
                raise H2CTimeout("timed out connecting HTTP/2 socket") from exc
            except OSError as exc:
                self._reader = None
                self._writer = None
                raise H2CConnectionClosed(f"failed to connect HTTP/2 socket: {exc}") from exc

    async def close(self) -> None:
        async with self._lock:
            self._closed = True
            streams = list(self._streams.values())
            self._streams.clear()
            writer = self._writer
            self._reader = None
            self._writer = None
        for stream in streams:
            stream._mark_error(H2CConnectionClosed("connection closed"))
        if writer is not None:
            writer.close()
            try:
                await writer.wait_closed()
            except OSError:
                pass

    async def open_stream(
        self,
        method: str,
        url: str,
        *,
        headers: Mapping[str, Any] | Iterable[tuple[str, Any]] | None,
        end_stream: bool,
    ) -> "AsyncH2CStream":
        await self.connect()
        parsed = urlsplit(url)
        async with self._lock:
            if not self.can_open_stream():
                raise H2CConnectionClosed("connection cannot open more streams")
            stream_id = self._next_stream_id
            self._next_stream_id += 2
            stream = AsyncH2CStream(self, stream_id)
            stream._send_window = self._remote_initial_window
            self._streams[stream_id] = stream

        request_headers = [
            (":method", _validate_method(method)),
            (":scheme", parsed.scheme),
            (":authority", _authority(parsed)),
            (":path", _request_path(parsed)),
            ("accept", "application/json"),
        ]
        request_headers.extend(_header_pairs(headers))
        await self._send_frame(
            _FRAME_HEADERS,
            _FLAG_END_HEADERS | (_FLAG_END_STREAM if end_stream else 0),
            stream_id,
            _encode_headers(request_headers),
        )
        if end_stream:
            stream._request_ended = True
        return stream

    async def send_data(self, stream: "AsyncH2CStream", data: bytes | str, *, end_stream: bool = False) -> None:
        body = data.encode("utf-8") if isinstance(data, str) else bytes(data)
        if not body:
            if end_stream:
                await self._send_frame(_FRAME_DATA, _FLAG_END_STREAM, stream.stream_id, b"")
                stream._request_ended = True
            return

        view = memoryview(body)
        offset = 0
        while offset < len(view):
            async with self._lock:
                stream._raise_if_error()
                if stream._closed:
                    raise H2CConnectionClosed("stream is closed")
                size = min(
                    len(view) - offset,
                    self._max_frame,
                    stream._send_window,
                    self._conn_send_window,
                )
                if size > 0:
                    stream._send_window -= size
                    self._conn_send_window -= size
            if size <= 0:
                await self.receive_one()
                continue
            final = end_stream and offset + size == len(view)
            await self._send_frame(
                _FRAME_DATA,
                _FLAG_END_STREAM if final else 0,
                stream.stream_id,
                view[offset : offset + size].tobytes(),
            )
            if final:
                stream._request_ended = True
            offset += size

    async def end_stream(self, stream: "AsyncH2CStream") -> None:
        await self.send_data(stream, b"", end_stream=True)

    async def read_chunk(self, stream: "AsyncH2CStream") -> Optional[bytes]:
        while True:
            async with self._lock:
                stream._raise_if_error()
                if stream._chunks:
                    return stream._chunks.pop(0)
                if stream._response_ended:
                    return None
            async with self._read_lock:
                async with self._lock:
                    stream._raise_if_error()
                    if stream._chunks:
                        return stream._chunks.pop(0)
                    if stream._response_ended:
                        return None
                await self._receive_one_unlocked()

    async def receive_one(self) -> None:
        async with self._read_lock:
            await self._receive_one_unlocked()

    async def _receive_one_unlocked(self) -> None:
        frame_type, flags, stream_id, payload = await self._read_frame()
        await self._handle_frame(frame_type, flags, stream_id, payload)

    async def remove_stream(self, stream_id: int) -> None:
        async with self._lock:
            self._streams.pop(stream_id, None)

    async def _send_frame(self, frame_type: int, flags: int, stream_id: int, payload: bytes) -> None:
        frame = _frame_bytes(frame_type, flags, stream_id, payload)
        async with self._send_lock:
            writer = self._writer
            if writer is None:
                raise H2CConnectionClosed("connection is closed")
            try:
                writer.write(frame)
                await _await_with_timeout(writer.drain(), self._timeout)
            except asyncio.TimeoutError as exc:
                raise H2CTimeout("timed out writing h2c frame") from exc
            except OSError as exc:
                await self.close()
                raise H2CConnectionClosed(f"failed writing h2c frame: {exc}") from exc

    async def _recv_exact(self, n: int) -> bytes:
        reader = self._reader
        if reader is None:
            raise H2CConnectionClosed("connection is closed")
        try:
            return await _await_with_timeout(reader.readexactly(n), self._timeout)
        except asyncio.IncompleteReadError as exc:
            raise H2CConnectionClosed("connection closed before stream ended") from exc
        except asyncio.TimeoutError as exc:
            raise H2CTimeout("timed out reading h2c frame") from exc
        except OSError as exc:
            await self.close()
            raise H2CConnectionClosed(f"failed reading h2c frame: {exc}") from exc

    async def _read_frame(self) -> tuple[int, int, int, bytes]:
        header = await self._recv_exact(9)
        length = int.from_bytes(header[:3], "big")
        if length > _MAX_INBOUND_FRAME:
            raise H2CProtocolError("HTTP/2 inbound frame exceeds local limit")
        frame_type = header[3]
        flags = header[4]
        stream_id = int.from_bytes(header[5:9], "big") & 0x7FFFFFFF
        return frame_type, flags, stream_id, await self._recv_exact(length)

    async def _handle_frame(self, frame_type: int, flags: int, stream_id: int, payload: bytes) -> None:
        if frame_type == _FRAME_SETTINGS:
            await self._handle_settings(flags, payload)
        elif frame_type == _FRAME_HEADERS:
            await self._handle_headers_frame(flags, stream_id, payload)
        elif frame_type == _FRAME_PUSH_PROMISE:
            await self._handle_push_promise(flags, stream_id, payload)
        elif frame_type == _FRAME_DATA:
            await self._handle_data_frame(flags, stream_id, payload)
        elif frame_type == _FRAME_WINDOW_UPDATE:
            await self._handle_window_update(stream_id, payload)
        elif frame_type == _FRAME_RST_STREAM:
            await self._handle_rst_stream(stream_id, payload)
        elif frame_type == _FRAME_GOAWAY:
            await self._handle_goaway(payload)
        elif frame_type == _FRAME_PING and not (flags & _FLAG_ACK):
            await self._send_frame(_FRAME_PING, _FLAG_ACK, 0, payload[:8].ljust(8, b"\0"))
        elif frame_type == _FRAME_PRIORITY:
            return

    async def _handle_settings(self, flags: int, payload: bytes) -> None:
        if flags & _FLAG_ACK:
            return
        if len(payload) % 6 != 0:
            raise H2CProtocolError("invalid SETTINGS frame")
        initial_window: Optional[int] = None
        for i in range(0, len(payload), 6):
            setting = int.from_bytes(payload[i : i + 2], "big")
            value = int.from_bytes(payload[i + 2 : i + 6], "big")
            if setting == 3:
                self._max_concurrent_streams = max(1, value)
            elif setting == 4:
                if value > _MAX_FLOW_CONTROL_WINDOW:
                    raise H2CProtocolError("invalid SETTINGS_INITIAL_WINDOW_SIZE")
                initial_window = value
            elif setting == 5:
                if value < 16384 or value > 16777215:
                    raise H2CProtocolError("invalid SETTINGS_MAX_FRAME_SIZE")
                self._max_frame = value
        if initial_window is not None:
            async with self._lock:
                delta = initial_window - self._remote_initial_window
                self._remote_initial_window = initial_window
                for stream in self._streams.values():
                    stream._send_window += delta
        await self._send_frame(_FRAME_SETTINGS, _FLAG_ACK, 0, b"")

    async def _handle_headers_frame(self, flags: int, stream_id: int, payload: bytes) -> None:
        block = await self._headers_payload(flags, stream_id, payload)
        headers = self._decoder.decode(block)
        async with self._lock:
            stream = self._streams.get(stream_id)
            if stream is None:
                return
            stream._handle_headers(headers)
            if flags & _FLAG_END_STREAM:
                stream._response_ended = True

    async def _handle_data_frame(self, flags: int, stream_id: int, payload: bytes) -> None:
        data = self._data_payload(flags, payload)
        async with self._lock:
            stream = self._streams.get(stream_id)
            if stream is None:
                return
            if data:
                stream._chunks.append(data)
        if data:
            increment = len(data).to_bytes(4, "big")
            await self._send_frame(_FRAME_WINDOW_UPDATE, 0, 0, increment)
            await self._send_frame(_FRAME_WINDOW_UPDATE, 0, stream_id, increment)
        if flags & _FLAG_END_STREAM:
            async with self._lock:
                stream = self._streams.get(stream_id)
                if stream is not None:
                    stream._response_ended = True

    async def _handle_window_update(self, stream_id: int, payload: bytes) -> None:
        if len(payload) != 4:
            raise H2CProtocolError("invalid WINDOW_UPDATE frame")
        inc = int.from_bytes(payload, "big") & 0x7FFFFFFF
        if inc == 0:
            raise H2CProtocolError("WINDOW_UPDATE increment must be non-zero")
        async with self._lock:
            if stream_id == 0:
                next_window = self._conn_send_window + inc
                if next_window > _MAX_FLOW_CONTROL_WINDOW:
                    raise H2CProtocolError("connection flow-control window overflow")
                self._conn_send_window = next_window
            else:
                stream = self._streams.get(stream_id)
                if stream is not None:
                    next_window = stream._send_window + inc
                    if next_window > _MAX_FLOW_CONTROL_WINDOW:
                        raise H2CProtocolError("stream flow-control window overflow")
                    stream._send_window = next_window

    async def _handle_rst_stream(self, stream_id: int, payload: bytes) -> None:
        code = int.from_bytes(payload[-4:], "big") if len(payload) >= 4 else 0
        async with self._lock:
            stream = self._streams.pop(stream_id, None)
        if stream is not None:
            stream._mark_error(H2CProtocolError(f"stream reset: {code}"))

    async def _handle_goaway(self, payload: bytes) -> None:
        last_stream_id = int.from_bytes(payload[:4], "big") & 0x7FFFFFFF if len(payload) >= 4 else 0
        code = int.from_bytes(payload[4:8], "big") if len(payload) >= 8 else 0
        async with self._lock:
            self._goaway_last_stream_id = last_stream_id
            streams = [s for sid, s in self._streams.items() if sid > last_stream_id]
        for stream in streams:
            stream._mark_error(H2CConnectionClosed(f"connection terminated: {code}"))

    async def _handle_push_promise(self, flags: int, stream_id: int, payload: bytes) -> None:
        pos = 0
        pad_len = 0
        if flags & _FLAG_PADDED:
            if not payload:
                raise H2CProtocolError("padded PUSH_PROMISE frame missing pad length")
            pad_len = payload[0]
            pos = 1
        if len(payload) < pos + 4 + pad_len:
            raise H2CProtocolError("truncated PUSH_PROMISE frame")
        promised_id = int.from_bytes(payload[pos : pos + 4], "big") & 0x7FFFFFFF
        if promised_id:
            await self._send_frame(_FRAME_RST_STREAM, 0, promised_id, _ERROR_REFUSED_STREAM.to_bytes(4, "big"))

    async def _headers_payload(self, flags: int, stream_id: int, payload: bytes) -> bytes:
        block = self._strip_headers_prefix(flags, payload)
        if len(block) > _MAX_HEADER_BLOCK:
            raise H2CProtocolError("HTTP/2 header block exceeds local limit")
        while not (flags & _FLAG_END_HEADERS):
            frame_type, flags, cont_stream_id, cont_payload = await self._read_frame()
            if frame_type != _FRAME_CONTINUATION or cont_stream_id != stream_id:
                raise H2CProtocolError("expected CONTINUATION frame")
            block += cont_payload
            if len(block) > _MAX_HEADER_BLOCK:
                raise H2CProtocolError("HTTP/2 header block exceeds local limit")
        return block

    def _strip_headers_prefix(self, flags: int, payload: bytes) -> bytes:
        pos = 0
        pad_len = 0
        if flags & _FLAG_PADDED:
            if not payload:
                raise H2CProtocolError("padded HEADERS frame missing pad length")
            pad_len = payload[0]
            pos = 1
        if flags & _FLAG_PRIORITY:
            if len(payload) < pos + 5:
                raise H2CProtocolError("truncated priority section in HEADERS frame")
            pos += 5
        if len(payload) < pos + pad_len:
            raise H2CProtocolError("invalid HEADERS padding")
        if pad_len:
            return payload[pos:-pad_len]
        return payload[pos:]

    def _data_payload(self, flags: int, payload: bytes) -> bytes:
        if flags & _FLAG_PADDED:
            if not payload:
                raise H2CProtocolError("padded DATA frame missing pad length")
            pad_len = payload[0]
            if len(payload) < 1 + pad_len:
                raise H2CProtocolError("invalid DATA padding")
            return payload[1:-pad_len] if pad_len else payload[1:]
        return payload


class AsyncH2CStream:
    def __init__(self, connection: AsyncH2CConnection, stream_id: int) -> None:
        self._connection = connection
        self._stream_id = stream_id
        self._chunks: list[bytes] = []
        self._response_headers: dict[str, str] = {}
        self._response_ended = False
        self._request_ended = False
        self._closed = False
        self._error: Optional[BaseException] = None
        self._send_window = 65535
        self.status_code: Optional[int] = None

    @property
    def stream_id(self) -> int:
        return self._stream_id

    @property
    def headers(self) -> dict[str, str]:
        return dict(self._response_headers)

    async def __aenter__(self) -> "AsyncH2CStream":
        return self

    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:
        await self.aclose()

    async def aclose(self) -> None:
        if self._closed:
            return
        self._closed = True
        await self._connection.remove_stream(self._stream_id)

    async def close(self) -> None:
        await self.aclose()

    async def send_json(self, value: Any, *, end_stream: bool = False) -> None:
        await self.send_data(
            _json.dumps(value, separators=(",", ":"), ensure_ascii=False).encode("utf-8"),
            end_stream=end_stream,
        )

    async def send_data(self, data: bytes | str, *, end_stream: bool = False) -> None:
        self._raise_if_error()
        if self._request_ended:
            raise H2CProtocolError("request body already ended")
        await self._connection.send_data(self, data, end_stream=end_stream)

    async def end_request(self) -> None:
        self._raise_if_error()
        if not self._request_ended:
            await self._connection.end_stream(self)

    async def read_chunk(self) -> Optional[bytes]:
        self._raise_if_error()
        return await self._connection.read_chunk(self)

    async def iter_bytes(self) -> AsyncIterator[bytes]:
        while True:
            chunk = await self.read_chunk()
            if chunk is None:
                break
            yield chunk

    async def iter_json_lines(self) -> AsyncIterator[Any]:
        buf = b""
        async for chunk in self.iter_bytes():
            buf += chunk
            while b"\n" in buf:
                line, buf = buf.split(b"\n", 1)
                if line.strip():
                    yield _json.loads(line)
        if buf.strip():
            yield _json.loads(buf)

    async def read_response(self) -> H2CResponse:
        chunks = []
        total = 0
        limit = self._connection._max_response_bytes
        async for chunk in self.iter_bytes():
            chunks.append(chunk)
            total += len(chunk)
            if limit is not None and total > limit:
                raise H2CProtocolError("response body exceeds local limit")
        status = self.status_code or 0
        if status == 0:
            raise H2CProtocolError("response ended without :status")
        return H2CResponse(status, dict(self._response_headers), b"".join(chunks))

    def _handle_headers(self, headers: list[tuple[str, str]]) -> None:
        for key, value in headers:
            if key == ":status":
                self.status_code = int(value)
            elif not key.startswith(":"):
                name = key.lower()
                _validate_header_pair(name, value)
                self._response_headers[name] = value

    def _mark_error(self, error: BaseException) -> None:
        self._error = error
        self._response_ended = True
        self._closed = True

    def _raise_if_error(self) -> None:
        if self._error is not None:
            raise self._error
"####;

pub fn emit() -> String {
    let mut out = String::from(HEADER);
    out.push_str(RUNTIME);
    out
}
