//! Kubernetes `status.conditions[]` entries: the clock-free facts a service
//! computes and the projection that stamps them.

use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// One entry of a Kubernetes `status.conditions[]` array, in the shape every
/// controller-aware tool already reads — `kubectl wait --for=condition=…`,
/// Argo CD health assessment, Flux readiness gates.
///
/// Hand-written rather than reused from
/// `k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition` because that type
/// does not derive `JsonSchema`, so it cannot be embedded in a CRD schema
/// generated by `kube`'s derive.
#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct Condition {
    /// CamelCase condition name, e.g. `Ready`.
    #[serde(rename = "type")]
    pub type_: String,
    /// `"True" | "False" | "Unknown"`.
    pub status: String,
    /// CamelCase machine-readable cause of the current status.
    pub reason: String,
    /// Human-readable detail. May be empty.
    #[serde(default)]
    pub message: String,
    /// RFC3339 instant the status last *changed* — not the last time it was
    /// observed. Carried across reconciles by [`project`].
    pub last_transition_time: String,
    /// The `.metadata.generation` this condition was computed from.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub observed_generation: Option<i64>,
}

/// The three values Kubernetes allows in a condition's `status`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConditionStatus {
    True,
    False,
    Unknown,
}

impl ConditionStatus {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::True => "True",
            Self::False => "False",
            Self::Unknown => "Unknown",
        }
    }

    /// `True`/`False` from a plain predicate — the common case.
    pub fn from_bool(value: bool) -> Self {
        if value {
            Self::True
        } else {
            Self::False
        }
    }
}

/// A condition as a service computes it: everything except the clock.
///
/// Services project status synchronously and without I/O, so they cannot stamp
/// `lastTransitionTime` themselves. [`project`] does it with a time the
/// controller injects — that split is what keeps status projection
/// deterministically testable.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ConditionFact {
    pub type_: String,
    pub status: ConditionStatus,
    pub reason: String,
    pub message: String,
}

impl ConditionFact {
    pub fn new(
        type_: impl Into<String>,
        status: ConditionStatus,
        reason: impl Into<String>,
        message: impl Into<String>,
    ) -> Self {
        Self {
            type_: type_.into(),
            status,
            reason: reason.into(),
            message: message.into(),
        }
    }
}

/// Stamp `facts` into full [`Condition`]s, carrying `lastTransitionTime` forward
/// from `prior` for every condition whose `status` did not change.
///
/// `lastTransitionTime` means "when this condition last *changed*", so a
/// reconcile that re-observes the same state must not move it — otherwise the
/// periodic 30s requeue would look like a state change to everything watching.
///
/// Conditions absent from `facts` are dropped: a service declares its whole
/// condition set every pass, and the controller writes status with
/// `Patch::Merge`, which replaces the array wholesale anyway.
pub fn project(
    prior: &[Condition],
    facts: Vec<ConditionFact>,
    observed_generation: i64,
    now: &str,
) -> Vec<Condition> {
    facts
        .into_iter()
        .map(|fact| {
            let status = fact.status.as_str().to_string();
            let last_transition_time = prior
                .iter()
                .find(|c| c.type_ == fact.type_ && c.status == status)
                .map(|c| c.last_transition_time.clone())
                .unwrap_or_else(|| now.to_string());
            Condition {
                type_: fact.type_,
                status,
                reason: fact.reason,
                message: fact.message,
                last_transition_time,
                observed_generation: Some(observed_generation),
            }
        })
        .collect()
}

#[cfg(test)]
mod tests;
