//! Infrastructure layer.

pub(crate) mod analysis_cache;
pub(crate) mod check;
pub(crate) mod checker_config;
pub(crate) mod codegen;
pub(crate) mod config;
pub(crate) mod daemon;
pub(crate) mod frameworks;
pub(crate) mod import_graph;
pub(crate) mod import_resolution;
pub(crate) mod incremental_analysis;
pub(crate) mod index_storage;
pub(crate) mod lint;
pub(crate) mod module_cache;
pub(crate) mod package;
pub(crate) mod project;
pub(crate) mod python_env;
pub(crate) mod rust_source_scan;
pub(crate) mod schema_validation;
pub(crate) mod scope_discovery;
pub(crate) mod spec_import;
pub(crate) mod stubs;
pub(crate) mod syntax;
pub(crate) mod typeshed;
pub(crate) mod watch;
pub(crate) mod watch_bridge;
