//! Emit a `reqwest::blocking` Rust client: one method per operation, returning
//! the serde-deserialized response.

use crate::emit::rust::rsmap;
use crate::ir::names::{to_snake, NameRegistry};
use crate::ir::openapi::RefOr;
use crate::ir::operations::{OperationIR, ParamIR};
use crate::ir::typemap::TypeMap;

pub const HEADER: &str = "// Code generated by openapi-codegen. DO NOT EDIT.\n";

pub fn emit(ops: &[OperationIR], tm: &TypeMap) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use crate::models::*;\n\n");
    out.push_str("pub struct Client {\n");
    out.push_str("    base_url: String,\n");
    out.push_str("    http: reqwest::blocking::Client,\n");
    out.push_str("}\n\n");
    out.push_str("impl Client {\n");
    out.push_str("    pub fn new(base_url: impl Into<String>) -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str("            base_url: base_url.into().trim_end_matches('/').to_string(),\n");
    out.push_str("            http: reqwest::blocking::Client::new(),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    let mut reg = NameRegistry::new();
    reg.unique("new");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(ir, tm, &mut reg));
    }
    out.push_str("}\n");
    out
}

fn fn_name(ir: &OperationIR) -> String {
    match &ir.operation_id {
        Some(id) if !id.trim().is_empty() => to_snake(id),
        _ => to_snake(&format!(
            "{}_{}",
            ir.method,
            ir.path.replace(['/', '{', '}'], "_")
        )),
    }
}

fn param_ann(p: &ParamIR, tm: &TypeMap) -> (String, String, bool) {
    let ty = p
        .schema
        .as_ref()
        .map(|s| rsmap::type_expr(s, tm))
        .unwrap_or_else(|| "String".to_string());
    (to_snake(&p.name), ty, p.required)
}

fn emit_method(ir: &OperationIR, tm: &TypeMap, reg: &mut NameRegistry) -> String {
    let name = reg.unique(&fn_name(ir));

    let path_anns: Vec<_> = ir.path_params.iter().map(|p| param_ann(p, tm)).collect();
    let query_anns: Vec<_> = ir.query_params.iter().map(|p| param_ann(p, tm)).collect();
    let header_anns: Vec<_> = ir.header_params.iter().map(|p| param_ann(p, tm)).collect();

    // Signature: path (required), query, header, body — stable order.
    let mut sig: Vec<String> = Vec::new();
    for (n, t, _) in &path_anns {
        sig.push(format!("{n}: {t}"));
    }
    for (n, t, req) in query_anns.iter().chain(header_anns.iter()) {
        sig.push(format!(
            "{n}: {}",
            if *req { t.clone() } else { rsmap::optional(t) }
        ));
    }
    let body_ty = ir.body.as_ref().map(|b| rsmap::type_expr(&b.schema, tm));
    if let Some(t) = &body_ty {
        let req = ir.body.as_ref().map(|b| b.required).unwrap_or(false);
        sig.push(format!(
            "body: {}",
            if req { t.clone() } else { rsmap::optional(t) }
        ));
    }

    let (ret, ret_stmt) = response(ir, tm);
    let mut m = format!(
        "    pub fn {name}(&self{}) -> reqwest::Result<{ret}> {{\n",
        if sig.is_empty() {
            String::new()
        } else {
            format!(", {}", sig.join(", "))
        }
    );

    // URL with path params substituted into a format string.
    let mut fmt = ir.path.clone();
    let mut args: Vec<String> = Vec::new();
    for (p, (snake, ..)) in ir.path_params.iter().zip(&path_anns) {
        fmt = fmt.replace(&format!("{{{}}}", p.name), "{}");
        args.push(snake.clone());
    }
    let arg_tail = if args.is_empty() {
        String::new()
    } else {
        format!(", {}", args.join(", "))
    };
    m.push_str(&format!(
        "        let url = format!(\"{{}}{fmt}\", self.base_url{arg_tail});\n"
    ));

    let method = ir.method.as_str();
    m.push_str(&format!("        let mut req = self.http.{method}(url);\n"));

    if !ir.query_params.is_empty() {
        m.push_str("        let mut q: Vec<(&str, String)> = Vec::new();\n");
        for (p, (snake, _, req)) in ir.query_params.iter().zip(&query_anns) {
            if *req {
                m.push_str(&format!(
                    "        q.push((\"{}\", {snake}.to_string()));\n",
                    esc(&p.name)
                ));
            } else {
                m.push_str(&format!(
                    "        if let Some(v) = &{snake} {{ q.push((\"{}\", v.to_string())); }}\n",
                    esc(&p.name)
                ));
            }
        }
        m.push_str("        req = req.query(&q);\n");
    }
    for (p, (snake, _, req)) in ir.header_params.iter().zip(&header_anns) {
        if *req {
            m.push_str(&format!(
                "        req = req.header(\"{}\", {snake}.to_string());\n",
                esc(&p.name)
            ));
        } else {
            m.push_str(&format!(
                "        if let Some(v) = &{snake} {{ req = req.header(\"{}\", v.to_string()); }}\n",
                esc(&p.name)
            ));
        }
    }
    if body_ty.is_some() {
        m.push_str("        req = req.json(&body);\n");
    }

    m.push_str("        let resp = req.send()?.error_for_status()?;\n");
    m.push_str(&format!("        {ret_stmt}\n"));
    m.push_str("    }\n");
    m
}

/// `(return type, return statement)` for the operation's response.
fn response(ir: &OperationIR, tm: &TypeMap) -> (String, String) {
    match &ir.response {
        None => ("()".to_string(), "let _ = resp; Ok(())".to_string()),
        Some(RefOr::Ref(r)) => {
            let ty = tm
                .resolve_ref(&r.reference)
                .unwrap_or_else(|| "serde_json::Value".to_string());
            (ty, "resp.json()".to_string())
        }
        Some(node @ RefOr::Item(_)) => (rsmap::type_expr(node, tm), "resp.json()".to_string()),
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
