//! Emit a `reqwest::blocking` Rust client: one method per operation, returning
//! the serde-deserialized response.

use crate::emit::rust::rsmap;
use crate::ir::names::{to_snake, NameRegistry};
use crate::ir::openapi::RefOr;
use crate::ir::operations::{OperationIR, ParamIR};
use crate::ir::typemap::TypeMap;

pub const HEADER: &str = "// Code generated by openapi-codegen. DO NOT EDIT.\n";

pub fn emit(ops: &[OperationIR], tm: &TypeMap) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use crate::models::*;\n\n");
    out.push_str("use std::fmt;\n");
    out.push_str("use std::sync::{Arc, Condvar, Mutex};\n");
    out.push_str("use std::time::{Duration, Instant};\n\n");
    out.push_str("const DEFAULT_MAX_CONNECTIONS: usize = 128;\n");
    out.push_str("const DEFAULT_MAX_KEEPALIVE_CONNECTIONS: usize = 16;\n");
    out.push_str("const DEFAULT_KEEPALIVE_EXPIRY: Duration = Duration::from_secs(5);\n");
    out.push_str("const DEFAULT_POOL_TIMEOUT: Duration = Duration::from_secs(5);\n\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub struct TransportPolicy {\n");
    out.push_str("    pub target_concurrency: usize,\n");
    out.push_str("    pub max_connections: usize,\n");
    out.push_str("    pub max_in_flight_per_origin: usize,\n");
    out.push_str("    pub max_keepalive_connections: usize,\n");
    out.push_str("    pub keepalive_expiry: Duration,\n");
    out.push_str("    pub pool_timeout: Duration,\n");
    out.push_str("}\n\n");
    out.push_str("impl Default for TransportPolicy {\n");
    out.push_str("    fn default() -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str("            target_concurrency: DEFAULT_MAX_CONNECTIONS,\n");
    out.push_str("            max_connections: DEFAULT_MAX_CONNECTIONS,\n");
    out.push_str("            max_in_flight_per_origin: DEFAULT_MAX_CONNECTIONS,\n");
    out.push_str("            max_keepalive_connections: DEFAULT_MAX_KEEPALIVE_CONNECTIONS,\n");
    out.push_str("            keepalive_expiry: DEFAULT_KEEPALIVE_EXPIRY,\n");
    out.push_str("            pool_timeout: DEFAULT_POOL_TIMEOUT,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str(
        "pub fn recommended_h2_connections(concurrency: usize, parallelism: usize) -> usize {\n",
    );
    out.push_str("    let cap = parallelism.max(1);\n");
    out.push_str("    if concurrency <= 2 { return 1; }\n");
    out.push_str("    ((concurrency as f64).ln().ceil() as usize).clamp(1, cap)\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug)]\n");
    out.push_str("pub enum ClientError {\n");
    out.push_str("    Http(reqwest::Error),\n");
    out.push_str("    PoolTimeout(Duration),\n");
    out.push_str("}\n\n");
    out.push_str("impl From<reqwest::Error> for ClientError {\n");
    out.push_str("    fn from(value: reqwest::Error) -> Self { Self::Http(value) }\n");
    out.push_str("}\n\n");
    out.push_str("impl fmt::Display for ClientError {\n");
    out.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    out.push_str("        match self {\n");
    out.push_str("            Self::Http(err) => write!(f, \"{err}\"),\n");
    out.push_str("            Self::PoolTimeout(timeout) => write!(f, \"pool timeout after {timeout:?}\"),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for ClientError {\n");
    out.push_str("    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {\n");
    out.push_str("        match self {\n");
    out.push_str("            Self::Http(err) => Some(err),\n");
    out.push_str("            Self::PoolTimeout(_) => None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("pub type ClientResult<T> = std::result::Result<T, ClientError>;\n\n");
    out.push_str("#[derive(Default)]\n");
    out.push_str("struct AdmissionState { in_flight: usize }\n\n");
    out.push_str("struct SlotGuard { admission: Arc<(Mutex<AdmissionState>, Condvar)> }\n\n");
    out.push_str("impl Drop for SlotGuard {\n");
    out.push_str("    fn drop(&mut self) {\n");
    out.push_str("        let (lock, cv) = &*self.admission;\n");
    out.push_str("        let mut state = lock.lock().expect(\"admission lock poisoned\");\n");
    out.push_str("        state.in_flight = state.in_flight.saturating_sub(1);\n");
    out.push_str("        cv.notify_one();\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("pub struct Client {\n");
    out.push_str("    base_url: String,\n");
    out.push_str("    http: reqwest::blocking::Client,\n");
    out.push_str("    policy: TransportPolicy,\n");
    out.push_str("    admission: Arc<(Mutex<AdmissionState>, Condvar)>,\n");
    out.push_str("}\n\n");
    out.push_str("impl Client {\n");
    out.push_str("    pub fn new(base_url: impl Into<String>) -> Self {\n");
    out.push_str("        Self::with_policy(base_url, TransportPolicy::default())\n");
    out.push_str("    }\n\n");
    out.push_str(
        "    pub fn with_policy(base_url: impl Into<String>, policy: TransportPolicy) -> Self {\n",
    );
    out.push_str("        let http = reqwest::blocking::Client::builder()\n");
    out.push_str("            .pool_max_idle_per_host(policy.max_keepalive_connections)\n");
    out.push_str("            .pool_idle_timeout(policy.keepalive_expiry)\n");
    out.push_str("            .build()\n");
    out.push_str("            .expect(\"generated client reqwest builder\");\n");
    out.push_str("        Self {\n");
    out.push_str("            base_url: base_url.into().trim_end_matches('/').to_string(),\n");
    out.push_str("            http,\n");
    out.push_str("            policy,\n");
    out.push_str("            admission: Arc::new((Mutex::new(AdmissionState::default()), Condvar::new())),\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("\n    fn acquire_slot(&self) -> ClientResult<SlotGuard> {\n");
    out.push_str("        let max = self.policy.max_in_flight_per_origin.max(1);\n");
    out.push_str("        let deadline = Instant::now() + self.policy.pool_timeout;\n");
    out.push_str("        let (lock, cv) = &*self.admission;\n");
    out.push_str("        let mut state = lock.lock().expect(\"admission lock poisoned\");\n");
    out.push_str("        while state.in_flight >= max {\n");
    out.push_str("            let now = Instant::now();\n");
    out.push_str("            if now >= deadline { return Err(ClientError::PoolTimeout(self.policy.pool_timeout)); }\n");
    out.push_str("            let wait = deadline.saturating_duration_since(now);\n");
    out.push_str("            let (next, timeout) = cv.wait_timeout(state, wait).expect(\"admission lock poisoned\");\n");
    out.push_str("            state = next;\n");
    out.push_str("            if timeout.timed_out() && state.in_flight >= max { return Err(ClientError::PoolTimeout(self.policy.pool_timeout)); }\n");
    out.push_str("        }\n");
    out.push_str("        state.in_flight += 1;\n");
    out.push_str("        Ok(SlotGuard { admission: Arc::clone(&self.admission) })\n");
    out.push_str("    }\n");

    let mut reg = NameRegistry::new();
    reg.unique("new");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(ir, tm, &mut reg));
    }
    out.push_str("}\n");
    out
}

fn fn_name(ir: &OperationIR) -> String {
    match &ir.operation_id {
        Some(id) if !id.trim().is_empty() => to_snake(id),
        _ => to_snake(&format!(
            "{}_{}",
            ir.method,
            ir.path.replace(['/', '{', '}'], "_")
        )),
    }
}

fn param_ann(p: &ParamIR, tm: &TypeMap) -> (String, String, bool) {
    let ty = p
        .schema
        .as_ref()
        .map(|s| rsmap::type_expr(s, tm))
        .unwrap_or_else(|| "String".to_string());
    (to_snake(&p.name), ty, p.required)
}

fn emit_method(ir: &OperationIR, tm: &TypeMap, reg: &mut NameRegistry) -> String {
    let name = reg.unique(&fn_name(ir));

    let path_anns: Vec<_> = ir.path_params.iter().map(|p| param_ann(p, tm)).collect();
    let query_anns: Vec<_> = ir.query_params.iter().map(|p| param_ann(p, tm)).collect();
    let header_anns: Vec<_> = ir.header_params.iter().map(|p| param_ann(p, tm)).collect();

    // Signature: path (required), query, header, body — stable order.
    let mut sig: Vec<String> = Vec::new();
    for (n, t, _) in &path_anns {
        sig.push(format!("{n}: {t}"));
    }
    for (n, t, req) in query_anns.iter().chain(header_anns.iter()) {
        sig.push(format!(
            "{n}: {}",
            if *req { t.clone() } else { rsmap::optional(t) }
        ));
    }
    let body_ty = ir.body.as_ref().map(|b| rsmap::type_expr(&b.schema, tm));
    if let Some(t) = &body_ty {
        let req = ir.body.as_ref().map(|b| b.required).unwrap_or(false);
        sig.push(format!(
            "body: {}",
            if req { t.clone() } else { rsmap::optional(t) }
        ));
    }

    let (ret, ret_stmt) = response(ir, tm);
    let mut m = format!(
        "    pub fn {name}(&self{}) -> ClientResult<{ret}> {{\n",
        if sig.is_empty() {
            String::new()
        } else {
            format!(", {}", sig.join(", "))
        }
    );

    // URL with path params substituted into a format string.
    let mut fmt = ir.path.clone();
    let mut args: Vec<String> = Vec::new();
    for (p, (snake, ..)) in ir.path_params.iter().zip(&path_anns) {
        fmt = fmt.replace(&format!("{{{}}}", p.name), "{}");
        args.push(snake.clone());
    }
    let arg_tail = if args.is_empty() {
        String::new()
    } else {
        format!(", {}", args.join(", "))
    };
    m.push_str(&format!(
        "        let url = format!(\"{{}}{fmt}\", self.base_url{arg_tail});\n"
    ));

    let method = ir.method.as_str();
    m.push_str(&format!("        let mut req = self.http.{method}(url);\n"));

    if !ir.query_params.is_empty() {
        m.push_str("        let mut q: Vec<(&str, String)> = Vec::new();\n");
        for (p, (snake, _, req)) in ir.query_params.iter().zip(&query_anns) {
            if *req {
                m.push_str(&format!(
                    "        q.push((\"{}\", {snake}.to_string()));\n",
                    esc(&p.name)
                ));
            } else {
                m.push_str(&format!(
                    "        if let Some(v) = &{snake} {{ q.push((\"{}\", v.to_string())); }}\n",
                    esc(&p.name)
                ));
            }
        }
        m.push_str("        req = req.query(&q);\n");
    }
    for (p, (snake, _, req)) in ir.header_params.iter().zip(&header_anns) {
        if *req {
            m.push_str(&format!(
                "        req = req.header(\"{}\", {snake}.to_string());\n",
                esc(&p.name)
            ));
        } else {
            m.push_str(&format!(
                "        if let Some(v) = &{snake} {{ req = req.header(\"{}\", v.to_string()); }}\n",
                esc(&p.name)
            ));
        }
    }
    if body_ty.is_some() {
        m.push_str("        req = req.json(&body);\n");
    }

    m.push_str("        let _slot = self.acquire_slot()?;\n");
    m.push_str("        let resp = req.send()?.error_for_status()?;\n");
    m.push_str(&format!("        {ret_stmt}\n"));
    m.push_str("    }\n");
    m
}

/// `(return type, return statement)` for the operation's response.
fn response(ir: &OperationIR, tm: &TypeMap) -> (String, String) {
    match &ir.response {
        None => ("()".to_string(), "let _ = resp; Ok(())".to_string()),
        Some(RefOr::Ref(r)) => {
            let ty = tm
                .resolve_ref(&r.reference)
                .unwrap_or_else(|| "serde_json::Value".to_string());
            (ty, "Ok(resp.json()?)".to_string())
        }
        Some(node @ RefOr::Item(_)) => (rsmap::type_expr(node, tm), "Ok(resp.json()?)".to_string()),
    }
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
