//! Emit serde structs / aliases for the spec's component schemas.

use crate::emit::rust::rsmap;
use crate::ir::names::{to_pascal, to_snake};
use crate::ir::openapi::{RefOr, Schema, Spec};
use crate::ir::typemap::TypeMap;

pub const HEADER: &str = "// Code generated by openapi-codegen. DO NOT EDIT.\n";

const RUST_KEYWORDS: &[&str] = &[
    "as", "break", "const", "continue", "crate", "dyn", "else", "enum", "extern", "false", "fn",
    "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref",
    "return", "self", "Self", "static", "struct", "super", "trait", "true", "type", "unsafe",
    "use", "where", "while", "async", "await", "box", "do", "macro", "try", "yield",
];

/// `(rust_field_name, serde_rename)` — the rename is `Some` when the field name
/// differs from the JSON key.
pub fn field_name(key: &str) -> (String, Option<String>) {
    let snake = to_snake(key);
    let field = if RUST_KEYWORDS.contains(&snake.as_str()) {
        format!("{snake}_")
    } else {
        snake
    };
    let rename = (field != key).then(|| key.to_string());
    (field, rename)
}

pub fn emit(spec: &Spec, tm: &TypeMap) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use serde::{Deserialize, Serialize};\n");

    let blocks: Vec<String> = spec
        .components
        .schemas
        .iter()
        .map(|(key, node)| {
            let name = tm.names.get(key).cloned().unwrap_or_else(|| to_pascal(key));
            emit_schema(&name, node, tm)
        })
        .collect();
    if !blocks.is_empty() {
        out.push('\n');
        out.push_str(&blocks.join("\n"));
    }
    out
}

fn emit_schema(name: &str, node: &RefOr<Schema>, tm: &TypeMap) -> String {
    match node {
        RefOr::Ref(_) => format!("pub type {name} = {};\n", rsmap::type_expr(node, tm)),
        RefOr::Item(schema) if schema.properties.is_empty() => {
            format!("pub type {name} = {};\n", rsmap::type_expr(node, tm))
        }
        RefOr::Item(schema) => emit_struct(name, schema, tm),
    }
}

fn emit_struct(name: &str, schema: &Schema, tm: &TypeMap) -> String {
    let mut s = String::from("#[derive(Debug, Clone, Serialize, Deserialize)]\n");
    s.push_str(&format!("pub struct {name} {{\n"));
    for (key, prop) in &schema.properties {
        let required = schema.required.iter().any(|r| r == key);
        let ty = rsmap::type_expr(prop, tm);
        let ty = if required { ty } else { rsmap::optional(&ty) };
        let (field, rename) = field_name(key);
        if let Some(orig) = rename {
            s.push_str(&format!("    #[serde(rename = \"{}\")]\n", esc(&orig)));
        }
        if !required {
            s.push_str("    #[serde(skip_serializing_if = \"Option::is_none\")]\n");
        }
        s.push_str(&format!("    pub {field}: {ty},\n"));
    }
    s.push_str("}\n");
    s
}

fn esc(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
