//! Emits `types.ts`: named interfaces and aliases for component schemas, plus
//! named per-operation `XxxData` (grouped request) and `XxxResponse` types.

use crate::emit::ts::plan::{OperationPlan, ParamField};
use crate::emit::ts::tsmap::{type_expr, TypeMap};
use crate::ir::names::{self, to_pascal};
use crate::ir::openapi::{AdditionalProperties, RefOr, Schema, Spec};

pub const HEADER: &str = "// Code generated by jet codegen openapi. DO NOT EDIT.\n\n";

/// Render `types.ts` from `components.schemas` plus per-operation types.
///
pub fn emit(spec: &Spec, tm: &TypeMap, plans: &[OperationPlan]) -> String {
    let mut out = String::from(HEADER);
    for (key, node) in &spec.components.schemas {
        let name = tm.names.get(key).cloned().unwrap_or_else(|| to_pascal(key));
        match node {
            RefOr::Ref(r) => {
                let target = tm
                    .resolve_ref(&r.reference)
                    .unwrap_or_else(|| "unknown".to_string());
                out.push_str(&format!("export type {name} = {target};\n\n"));
            }
            RefOr::Item(schema) => {
                if is_named_object(schema) {
                    out.push_str(&emit_interface(&name, schema, tm));
                } else {
                    out.push_str(&format!(
                        "export type {name} = {};\n\n",
                        type_expr(node, tm)
                    ));
                }
            }
        }
    }
    for p in plans {
        if let Some(data_name) = &p.data_type_name {
            out.push_str(&format!(
                "export type {data_name} = {};\n\n",
                data_type_body(p)
            ));
        }
        out.push_str(&format!(
            "export type {} = {};\n\n",
            p.response_type_name, p.response_type
        ));
    }
    out
}

/// The grouped request shape: `{ path: {...}; query?: {...}; headers?: {...}; body?: T }`,
/// including only the keys the operation actually uses.
fn data_type_body(p: &OperationPlan) -> String {
    let mut parts: Vec<String> = Vec::new();
    if !p.path_params.is_empty() {
        parts.push(format!("path: {{ {} }}", obj_fields(&p.path_params)));
    }
    if !p.query_params.is_empty() {
        let opt = if p.query_required() { "" } else { "?" };
        parts.push(format!("query{opt}: {{ {} }}", obj_fields(&p.query_params)));
    }
    if !p.header_params.is_empty() {
        let opt = if p.headers_required() { "" } else { "?" };
        parts.push(format!(
            "headers{opt}: {{ {} }}",
            obj_fields(&p.header_params)
        ));
    }
    if let Some(body) = &p.body {
        let opt = if body.required { "" } else { "?" };
        parts.push(format!("body{opt}: {}", body.ts_type));
    }
    format!("{{ {} }}", parts.join("; "))
}

fn obj_fields(fields: &[ParamField]) -> String {
    fields
        .iter()
        .map(|f| {
            format!(
                "{}{}: {}",
                names::prop_key(&f.name),
                if f.required { "" } else { "?" },
                f.ts_type
            )
        })
        .collect::<Vec<_>>()
        .join("; ")
}

/// An object schema worth emitting as an `interface` (not a union/enum/alias).
fn is_named_object(schema: &Schema) -> bool {
    schema.one_of.is_empty()
        && schema.any_of.is_empty()
        && schema.all_of.is_empty()
        && schema.enum_values.is_empty()
        && (schema.type_names().iter().any(|t| t == "object") || !schema.properties.is_empty())
}

fn emit_interface(name: &str, schema: &Schema, tm: &TypeMap) -> String {
    let mut out = format!("export interface {name} {{\n");
    for (key, prop) in &schema.properties {
        let optional = !schema.required.iter().any(|r| r == key);
        out.push_str(&format!(
            "  {}{}: {};\n",
            names::prop_key(key),
            if optional { "?" } else { "" },
            type_expr(prop, tm)
        ));
    }
    match &schema.additional_properties {
        Some(AdditionalProperties::Bool(true)) => out.push_str("  [key: string]: unknown;\n"),
        Some(AdditionalProperties::Schema(s)) => {
            out.push_str(&format!("  [key: string]: {};\n", type_expr(s, tm)));
        }
        _ => {}
    }
    out.push_str("}\n\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::build_type_map;
    use crate::emit::ts::plan;

    fn spec(json: &str) -> Spec {
        serde_json::from_str(json).unwrap()
    }

    fn render(json: &str) -> String {
        let s = spec(json);
        let tm = build_type_map(&s);
        let plans = plan::build(&s, &tm);
        emit(&s, &tm, &plans)
    }

    #[test]
    fn emits_interface_with_optional_and_required() {
        let out = render(
            r##"{"components":{"schemas":{"Pet":{"type":"object",
            "properties":{"id":{"type":"integer"},"name":{"type":"string"},"tag":{"type":"string"}},
            "required":["id","name"]}}}}"##,
        );
        assert!(out.contains("export interface Pet {"));
        assert!(out.contains("  id: number;"));
        assert!(out.contains("  name: string;"));
        assert!(out.contains("  tag?: string;"));
    }

    #[test]
    fn emits_type_alias_for_enum_and_union() {
        let out = render(
            r##"{"components":{"schemas":{
            "Status":{"type":"string","enum":["open","closed"]},
            "Id":{"oneOf":[{"type":"string"},{"type":"integer"}]}}}}"##,
        );
        assert!(out.contains("export type Status = \"open\" | \"closed\";"));
        assert!(out.contains("export type Id = string | number;"));
    }

    #[test]
    fn emits_grouped_data_and_response_types() {
        let out = render(
            r##"{"paths":{"/pets/{petId}":{"get":{"operationId":"getPetById",
            "parameters":[
              {"name":"petId","in":"path","required":true,"schema":{"type":"integer"}},
              {"name":"expand","in":"query","required":false,"schema":{"type":"boolean"}}],
            "responses":{"200":{"content":{"application/json":{"schema":{"type":"string"}}}}}}}}}"##,
        );
        assert!(
            out.contains("export type GetPetByIdData = { path: { petId: number }; query?: { expand?: boolean } };"),
            "{out}"
        );
        assert!(
            out.contains("export type GetPetByIdResponse = string;"),
            "{out}"
        );
    }

    #[test]
    fn emits_body_data_and_void_response() {
        let out = render(
            r##"{"paths":{"/pets":{"post":{"operationId":"createPet",
              "requestBody":{"required":true,"content":{"application/json":{"schema":{"$ref":"#/components/schemas/NewPet"}}}},
              "responses":{"204":{"description":"created"}}}}},
            "components":{"schemas":{"NewPet":{"type":"object","properties":{"name":{"type":"string"}},"required":["name"]}}}}"##,
        );
        assert!(
            out.contains("export type CreatePetData = { body: NewPet };"),
            "{out}"
        );
        assert!(
            out.contains("export type CreatePetResponse = void;"),
            "{out}"
        );
    }
}
