from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from openapi_codegen.domain.errors import TargetLanguageMismatch, UnknownTargetProfile
from openapi_codegen.domain.lang import Lang
from openapi_codegen.domain.target import (
    TargetProfile,
    default_profile_for,
    profile_from_id,
    profile_id,
    profile_lang,
)
from openapi_codegen.infrastructure.options import (
    GenOptions,
    GeneratedFile,
    GeneratedOutput,
    for_target,
    legacy,
)

TS_HEADER = "// Code generated by openapi-codegen. DO NOT EDIT.\n\n"
PY_HEADER = "# Code generated by openapi-codegen. DO NOT EDIT.\n"
RUST_HEADER = "// Code generated by openapi-codegen. DO NOT EDIT.\n"


@dataclass(frozen=True)
class ConflictingTarget:
    argument: str
    configured: str

    def message(self) -> str:
        return f"explicit target argument {self.argument} conflicts with GenOptions target {self.configured}"


def planned_paths(opts: GenOptions) -> tuple[str, ...]:
    paths: list[str] = []
    if opts.lang is Lang.TS:
        if opts.emit_types:
            paths.append("types.ts")
        if opts.emit_client:
            paths.append("runtime.ts")
            paths.append("client.ts")
        if opts.emit_hooks:
            paths.append("hooks.ts")
        paths.append("index.ts")
    elif opts.lang is Lang.PY:
        if opts.emit_types:
            paths.append("models.py")
        if opts.emit_client:
            paths.append("h2c_runtime.py")
            paths.append("client.py")
        paths.append("__init__.py")
    elif opts.lang is Lang.RUST:
        if opts.emit_types:
            paths.append("models.rs")
        if opts.emit_client:
            paths.append("client.rs")
        paths.append("mod.rs")
    return tuple(paths)


def barrel_path(lang: Lang) -> str:
    if lang is Lang.TS:
        return "index.ts"
    if lang is Lang.PY:
        return "__init__.py"
    if lang is Lang.RUST:
        return "mod.rs"
    raise ValueError(f"Unknown language: {lang}")


def barrel_contents(opts: GenOptions) -> str:
    if opts.lang is Lang.TS:
        out = TS_HEADER
        if opts.emit_types:
            out += 'export * from "./types";\n'
        if opts.emit_client:
            out += 'export * from "./runtime";\n'
            out += 'export * from "./client";\n'
        if opts.emit_hooks:
            out += 'export * from "./hooks";\n'
        return out

    if opts.lang is Lang.PY:
        out = PY_HEADER
        if opts.emit_types:
            out += "from .models import *  # noqa: F401,F403\n"
        if opts.emit_client:
            out += "from .client import AsyncClient, Client  # noqa: F401\n"
            out += "from .h2c_runtime import AsyncH2CClient, AsyncH2CConnection, AsyncH2CStream, H2CClient, H2CConnection, H2CResponse, H2CStream  # noqa: F401\n"
        return out

    if opts.lang is Lang.RUST:
        out = RUST_HEADER
        if opts.emit_types:
            out += "pub mod models;\n"
        if opts.emit_client:
            out += "pub mod client;\n"
        return out

    raise ValueError(f"Unknown language: {opts.lang}")


def dispatch_error(
    opts: GenOptions, target: TargetProfile | None
) -> TargetLanguageMismatch | ConflictingTarget | None:
    if target is not None:
        if profile_lang(target) != opts.lang:
            return TargetLanguageMismatch(
                profile_id(target), profile_lang(target), opts.lang
            )
        if opts.target is not None and opts.target != target:
            return ConflictingTarget(
                argument=profile_id(target), configured=profile_id(opts.target)
            )
    return None


def generate_for_target(
    opts: GenOptions,
    explicit_target: str | None,
    callback: Callable[[TargetProfile | None], tuple[GeneratedFile, ...] | list[GeneratedFile]],
) -> GeneratedOutput | TargetLanguageMismatch | ConflictingTarget | UnknownTargetProfile:
    target = opts.target
    if explicit_target is not None:
        resolved = profile_from_id(explicit_target)
        if isinstance(resolved, UnknownTargetProfile):
            return resolved
        # Language ownership is checked before target conflict so a mismatched
        # explicit profile cannot be hidden by an already configured profile.
        if profile_lang(resolved) != opts.lang:
            return TargetLanguageMismatch(
                profile_id=profile_id(resolved),
                profile_lang=profile_lang(resolved),
                requested=opts.lang,
            )
        if target is not None and target != resolved:
            return ConflictingTarget(argument=profile_id(resolved), configured=profile_id(target))
        target = resolved

    if target is None and explicit_target is None:
        files = callback(None)
        return legacy(files)

    if target is None:
        target = default_profile_for(opts.lang)

    if profile_lang(target) != opts.lang:
        return TargetLanguageMismatch(
            profile_id=profile_id(target),
            profile_lang=profile_lang(target),
            requested=opts.lang,
        )

    files = callback(target)
    return for_target(files, target)
