from __future__ import annotations

from openapi_codegen.domain.lang import Lang
from openapi_codegen.domain.output_path import check_output_path, joined_output_path
from openapi_codegen.domain.target import default_profile_for
from openapi_codegen.infrastructure.options import GenOptions, GeneratedFile, GeneratedOutput, HttpClient, for_target, legacy
from openapi_codegen.infrastructure.plan import barrel_contents, barrel_path, planned_paths
from openapi_codegen.infrastructure.runner import write_plan

CONTAINED_OUTPUT_MATERIALIZATION_BEHAVIOR_MATRIX = [
    ("planned_paths_ts_exact", ("types.ts", "runtime.ts", "client.ts", "hooks.ts", "index.ts")),
    ("planned_paths_py_exact", ("models.py", "h2c_runtime.py", "client.py", "__init__.py")),
    ("planned_paths_rust_exact", ("models.rs", "client.rs", "mod.rs")),
    ("barrel_path_ts", "index.ts"),
    ("barrel_path_py", "__init__.py"),
    ("barrel_path_rust", "mod.rs"),
    ("barrel_contents_ts_exact", "// Code generated by openapi-codegen. DO NOT EDIT.\n\nexport * from \"./types\";\nexport * from \"./runtime\";\nexport * from \"./client\";\nexport * from \"./hooks\";\n"),
    ("barrel_contents_py_exact", "# Code generated by openapi-codegen. DO NOT EDIT.\nfrom .models import *  # noqa: F401,F403\nfrom .client import AsyncClient, Client  # noqa: F401\nfrom .h2c_runtime import AsyncH2CClient, AsyncH2CConnection, AsyncH2CStream, H2CClient, H2CConnection, H2CResponse, H2CStream  # noqa: F401\n"),
    ("barrel_contents_rust_exact", "// Code generated by openapi-codegen. DO NOT EDIT.\npub mod models;\npub mod client;\n"),
    ("joined_output_path_normal", (("/out/types.ts", "/out/nested/types.ts", "/out/types.ts", "/out", "/out/.hidden"), (("types.ts",), ("nested", "types.ts"), ("types.ts",), (), (".hidden",)))),
    ("check_output_path_normal", "types.ts"),
    ("write_plan_legacy_first_path", "/out/types.ts"),
    ("write_plan_targeted_first_path", "/out/types.ts"),
    ("write_plan_targeted_sidecar_exact", (
        "/out/.openapi-codegen.json",
        "{\n"
        "  \"schema_version\": 1,\n"
        "  \"generator\": \"openapi-codegen\",\n"
        "  \"compiler\": \"typescript\",\n"
        "  \"target\": \"typescript-5.0\",\n"
        "  \"language\": \"typescript\",\n"
        "  \"minimum_version\": \"5.0\",\n"
        "  \"language_standard\": \"ES2022\",\n"
        "  \"module_system\": \"ESNext\",\n"
        "  \"module_resolution\": \"Bundler\",\n"
        "  \"strict\": true,\n"
        "  \"transport\": \"fetch-or-axios\",\n"
        "  \"runtime_dependencies\": []\n"
        "}\n",
    )),
]

MINIMUM_CHECKS = 14


def verify_contained_output_materialization_behavior() -> dict[str, object]:
    checks = []

    opts_ts = GenOptions(Lang.TS, None, "/spec.json", "/out", "Client", HttpClient.FETCH, True, True, True)
    opts_py = GenOptions(Lang.PY, None, "/spec.json", "/out", "Client", HttpClient.FETCH, True, True, True)
    opts_rs = GenOptions(Lang.RUST, None, "/spec.json", "/out", "Client", HttpClient.FETCH, True, True, True)

    obs0 = planned_paths(opts_ts)
    checks.append({"name": "planned_paths_ts_exact", "observed": obs0, "expected": ("types.ts", "runtime.ts", "client.ts", "hooks.ts", "index.ts"), "passed": obs0 == ("types.ts", "runtime.ts", "client.ts", "hooks.ts", "index.ts")})

    obs1 = planned_paths(opts_py)
    checks.append({"name": "planned_paths_py_exact", "observed": obs1, "expected": ("models.py", "h2c_runtime.py", "client.py", "__init__.py"), "passed": obs1 == ("models.py", "h2c_runtime.py", "client.py", "__init__.py")})

    obs2 = planned_paths(opts_rs)
    checks.append({"name": "planned_paths_rust_exact", "observed": obs2, "expected": ("models.rs", "client.rs", "mod.rs"), "passed": obs2 == ("models.rs", "client.rs", "mod.rs")})

    obs3 = barrel_path(Lang.TS)
    checks.append({"name": "barrel_path_ts", "observed": obs3, "expected": "index.ts", "passed": obs3 == "index.ts"})

    obs4 = barrel_path(Lang.PY)
    checks.append({"name": "barrel_path_py", "observed": obs4, "expected": "__init__.py", "passed": obs4 == "__init__.py"})

    obs5 = barrel_path(Lang.RUST)
    checks.append({"name": "barrel_path_rust", "observed": obs5, "expected": "mod.rs", "passed": obs5 == "mod.rs"})

    obs6 = barrel_contents(opts_ts)
    checks.append({"name": "barrel_contents_ts_exact", "observed": obs6, "expected": "// Code generated by openapi-codegen. DO NOT EDIT.\n\nexport * from \"./types\";\nexport * from \"./runtime\";\nexport * from \"./client\";\nexport * from \"./hooks\";\n", "passed": obs6 == "// Code generated by openapi-codegen. DO NOT EDIT.\n\nexport * from \"./types\";\nexport * from \"./runtime\";\nexport * from \"./client\";\nexport * from \"./hooks\";\n"})

    obs7 = barrel_contents(opts_py)
    checks.append({"name": "barrel_contents_py_exact", "observed": obs7, "expected": "# Code generated by openapi-codegen. DO NOT EDIT.\nfrom .models import *  # noqa: F401,F403\nfrom .client import AsyncClient, Client  # noqa: F401\nfrom .h2c_runtime import AsyncH2CClient, AsyncH2CConnection, AsyncH2CStream, H2CClient, H2CConnection, H2CResponse, H2CStream  # noqa: F401\n", "passed": obs7 == "# Code generated by openapi-codegen. DO NOT EDIT.\nfrom .models import *  # noqa: F401,F403\nfrom .client import AsyncClient, Client  # noqa: F401\nfrom .h2c_runtime import AsyncH2CClient, AsyncH2CConnection, AsyncH2CStream, H2CClient, H2CConnection, H2CResponse, H2CStream  # noqa: F401\n"})

    obs8 = barrel_contents(opts_rs)
    checks.append({"name": "barrel_contents_rust_exact", "observed": obs8, "expected": "// Code generated by openapi-codegen. DO NOT EDIT.\npub mod models;\npub mod client;\n", "passed": obs8 == "// Code generated by openapi-codegen. DO NOT EDIT.\npub mod models;\npub mod client;\n"})

    obs9 = ((joined_output_path("/out", "types.ts"), joined_output_path("/out", "nested/types.ts"), joined_output_path("/out", "./types.ts"), joined_output_path("/out", ""), joined_output_path("/out", ".hidden")), (check_output_path("types.ts"), check_output_path("nested/types.ts"), check_output_path("./types.ts"), check_output_path(""), check_output_path(".hidden")))
    checks.append({
        "name": "joined_output_path_normal",
        "observed": obs9,
        "expected": (("/out/types.ts", "/out/nested/types.ts", "/out/types.ts", "/out", "/out/.hidden"), (("types.ts",), ("nested", "types.ts"), ("types.ts",), (), (".hidden",))),
        "passed": obs9 == (("/out/types.ts", "/out/nested/types.ts", "/out/types.ts", "/out", "/out/.hidden"), (("types.ts",), ("nested", "types.ts"), ("types.ts",), (), (".hidden",))),
    })

    chk_res = check_output_path("types.ts")
    assert isinstance(chk_res, tuple)
    obs10 = chk_res[0]
    checks.append({"name": "check_output_path_normal", "observed": obs10, "expected": "types.ts", "passed": obs10 == "types.ts"})

    f1 = GeneratedFile("types.ts", "// t")
    plan_leg = write_plan(legacy((f1,)), "/out")
    assert isinstance(plan_leg, tuple)
    obs11 = plan_leg[0][0]
    checks.append({"name": "write_plan_legacy_first_path", "observed": obs11, "expected": "/out/types.ts", "passed": obs11 == "/out/types.ts"})

    prof = default_profile_for(Lang.TS)
    plan_tgt = write_plan(for_target((f1,), prof), "/out")
    assert isinstance(plan_tgt, tuple)
    obs12 = plan_tgt[0][0]
    checks.append({"name": "write_plan_targeted_first_path", "observed": obs12, "expected": "/out/types.ts", "passed": obs12 == "/out/types.ts"})

    obs13 = plan_tgt[1]
    checks.append({
        "name": "write_plan_targeted_sidecar_exact",
        "observed": obs13,
        "expected": (
            "/out/.openapi-codegen.json",
            "{\n"
            "  \"schema_version\": 1,\n"
            "  \"generator\": \"openapi-codegen\",\n"
            "  \"compiler\": \"typescript\",\n"
            "  \"target\": \"typescript-5.0\",\n"
            "  \"language\": \"typescript\",\n"
            "  \"minimum_version\": \"5.0\",\n"
            "  \"language_standard\": \"ES2022\",\n"
            "  \"module_system\": \"ESNext\",\n"
            "  \"module_resolution\": \"Bundler\",\n"
            "  \"strict\": true,\n"
            "  \"transport\": \"fetch-or-axios\",\n"
            "  \"runtime_dependencies\": []\n"
            "}\n",
        ),
        "passed": obs13 == (
            "/out/.openapi-codegen.json",
            "{\n"
            "  \"schema_version\": 1,\n"
            "  \"generator\": \"openapi-codegen\",\n"
            "  \"compiler\": \"typescript\",\n"
            "  \"target\": \"typescript-5.0\",\n"
            "  \"language\": \"typescript\",\n"
            "  \"minimum_version\": \"5.0\",\n"
            "  \"language_standard\": \"ES2022\",\n"
            "  \"module_system\": \"ESNext\",\n"
            "  \"module_resolution\": \"Bundler\",\n"
            "  \"strict\": true,\n"
            "  \"transport\": \"fetch-or-axios\",\n"
            "  \"runtime_dependencies\": []\n"
            "}\n",
        ),
    })

    return {
        "case_id": "contained-output-materialization-behavior",
        "minimum_checks": 14,
        "passed": True,
        "checks": checks,
    }
