//! Language-specific checkers

mod asyncapi;
pub mod autofix;
mod css;
pub mod custom;
mod dockerfile;
pub mod embedded_markdown;
mod gitlab_ci;
mod gitlab_ci_rules;
mod go;
mod graphql;
mod html;
mod javascript;
mod kubernetes;
mod kubernetes_rules;
pub mod markdown;
mod mdx;
mod mermaid;
mod openapi;
mod openrpc;
mod proto;
mod python;
mod python_security;
mod rust_checker;
mod sql;
mod terraform;
mod terraform_rules;
mod toml_checker;
mod typescript;
mod yaml_dispatch;

pub use crate::domain::lint::checker::Checker;
pub use crate::domain::lint::registry::CheckerRegistry;
pub use asyncapi::AsyncApiChecker;
pub use css::CssChecker;
pub use custom::CustomLintEngine;
pub use dockerfile::DockerfileChecker;
pub use gitlab_ci::GitlabCiChecker;
pub use go::GoChecker;
pub use graphql::GraphqlChecker;
pub use html::HtmlChecker;
pub use javascript::JavaScriptChecker;
pub use kubernetes::KubernetesChecker;
pub use markdown::MarkdownChecker;
pub use mdx::MdxChecker;
pub use mermaid::MermaidChecker;
pub use openapi::OpenApiChecker;
pub use openrpc::OpenRpcChecker;
pub use proto::ProtoChecker;
pub use python::PythonChecker;
pub use rust_checker::RustChecker;
pub use sql::{detect_sql_injection, SqlChecker};
pub use terraform::TerraformChecker;
pub use toml_checker::TomlChecker;
pub use typescript::TypeScriptChecker;
pub use yaml_dispatch::YamlDispatcher;
