use super::literal::python_literal;
use super::method::emit_method;
use crate::domain::emit::py::pymap;
use crate::domain::ir::names::NameRegistry;
use crate::domain::ir::operations::OperationIR;
use crate::domain::ir::typemap::TypeMap;
use crate::domain::{FileBearerAuth, PythonTarget};

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

pub fn emit(
    ops: &[OperationIR],
    tm: &TypeMap,
    target: Option<PythonTarget>,
    auth: Option<&FileBearerAuth>,
) -> String {
    let mut out = String::from(HEADER);
    out.push_str("from __future__ import annotations\n");
    out.push_str("import ssl\n");
    out.push_str("from dataclasses import dataclass\n");
    out.push_str("from urllib.parse import urlsplit\n");
    if auth.is_some() {
        out.push_str("from ipaddress import ip_address\n");
        out.push_str("from pathlib import Path\n");
    }
    if target.is_some() {
        out.push_str("from typing import Any, Literal, Mapping, Protocol, Self\n");
    } else {
        out.push_str("from typing import Any, Literal, Mapping, Optional, Protocol\n");
    }
    out.push_str("from pydantic import BaseModel\n");
    out.push_str("from .h2c_runtime import AsyncH2CClient, H2CClient\n");
    out.push_str("from .models import *  # noqa: F401,F403\n\n\n");

    if let Some(auth) = auth {
        out.push_str(&format!(
            "_FILE_BEARER_TOKEN_PATH = {}\n",
            python_literal(
                auth.token_path()
                    .to_str()
                    .expect("FileBearerAuth validates UTF-8 paths")
            )
        ));
        out.push_str(&format!(
            "_FILE_BEARER_HOSTNAME_SUFFIX = {}\n",
            python_literal(auth.hostname_suffix())
        ));
        let schemes = auth
            .schemes()
            .map(|scheme| python_literal(scheme.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "_FILE_BEARER_SCHEMES = frozenset(({schemes},))\n\n\n"
        ));
        out.push_str("def _has_authorization(headers: Mapping[str, Any]) -> bool:\n");
        out.push_str(
            "    return any(str(name).casefold() == \"authorization\" for name in headers)\n\n\n",
        );
        out.push_str("def _is_dns_hostname(host: str) -> bool:\n");
        out.push_str("    if not host or len(host) > 253 or host.endswith(\".\"):\n");
        out.push_str("        return False\n");
        out.push_str("    try:\n");
        out.push_str("        ip_address(host)\n");
        out.push_str("        return False\n");
        out.push_str("    except ValueError:\n");
        out.push_str("        pass\n");
        out.push_str("    for label in host.split(\".\"):\n");
        out.push_str("        if not (1 <= len(label) <= 63):\n");
        out.push_str("            return False\n");
        out.push_str(
            "        if not ((\"a\" <= label[0] <= \"z\") or (\"0\" <= label[0] <= \"9\")):\n",
        );
        out.push_str("            return False\n");
        out.push_str(
            "        if not ((\"a\" <= label[-1] <= \"z\") or (\"0\" <= label[-1] <= \"9\")):\n",
        );
        out.push_str("            return False\n");
        out.push_str("        if not all((\"a\" <= char <= \"z\") or (\"0\" <= char <= \"9\") or char == \"-\" for char in label):\n");
        out.push_str("            return False\n");
        out.push_str("    return True\n\n\n");
        out.push_str(
            "def _file_bearer_headers(base_url: str, headers: dict[str, Any]) -> dict[str, Any]:\n",
        );
        out.push_str("    if _has_authorization(headers):\n");
        out.push_str("        return headers\n");
        out.push_str("    try:\n");
        out.push_str("        parsed = urlsplit(base_url)\n");
        out.push_str("        host = parsed.hostname or \"\"\n");
        out.push_str("    except ValueError:\n");
        out.push_str("        return headers\n");
        out.push_str("    if (\n");
        out.push_str("        parsed.scheme not in _FILE_BEARER_SCHEMES\n");
        out.push_str("        or parsed.username is not None\n");
        out.push_str("        or parsed.password is not None\n");
        out.push_str("        or \"?\" in base_url\n");
        out.push_str("        or \"#\" in base_url\n");
        out.push_str("        or parsed.path not in (\"\", \"/\")\n");
        out.push_str("        or not _is_dns_hostname(host)\n");
        out.push_str("        or not host.endswith(_FILE_BEARER_HOSTNAME_SUFFIX)\n");
        out.push_str("        or not host.removesuffix(_FILE_BEARER_HOSTNAME_SUFFIX)\n");
        out.push_str(
            "        or host.removesuffix(_FILE_BEARER_HOSTNAME_SUFFIX).endswith(\".\")\n",
        );
        out.push_str("    ):\n");
        out.push_str("        return headers\n");
        out.push_str("    try:\n");
        out.push_str(
            "        token = Path(_FILE_BEARER_TOKEN_PATH).read_text(encoding=\"utf-8\").strip()\n",
        );
        out.push_str("        value = f\"Bearer {token}\"\n");
        out.push_str("        if not token or not token.isascii() or not all(char.isprintable() and not char.isspace() for char in token):\n");
        out.push_str("            raise ValueError\n");
        out.push_str("    except (OSError, UnicodeError, ValueError):\n");
        out.push_str("        raise ValueError(\"request authentication token is unavailable or invalid\") from None\n");
        out.push_str("    result = dict(headers)\n");
        out.push_str("    result[\"Authorization\"] = value\n");
        out.push_str("    return result\n\n\n");
    }

    out.push_str("@dataclass(frozen=True)\n");
    out.push_str("class PrivateTrust:\n");
    out.push_str(
        "    \"\"\"Verify the server against a private CA instead of the public roots.\n\n",
    );
    out.push_str("    For a service published only inside a cluster the public roots cannot\n");
    out.push_str("    vouch for it and should not be consulted: a private trust domain merely\n");
    out.push_str("    *added* to the public set still lets any public CA certify this name. The\n");
    out.push_str(
        "    context built from this replaces the root store rather than extending it.\n\n",
    );
    out.push_str("    There is no option to skip verification. If the server cannot be\n");
    out.push_str("    verified, the fix is the anchor or the name -- not the check.\n");
    out.push_str("    \"\"\"\n\n");
    out.push_str("    #: PEM bundle holding the CA that signed the server's leaf.\n");
    out.push_str("    ca_bundle: str\n");
    out.push_str("    #: The DNS name the leaf must assert. The base URL has to address this\n");
    out.push_str("    #: same name: a client that verified one name while addressing another\n");
    out.push_str("    #: would be checking a certificate it never actually relies on.\n");
    out.push_str("    server_name: str\n\n\n");
    out.push_str(
        "def _private_trust_context(trust: PrivateTrust, base_url: str) -> ssl.SSLContext:\n",
    );
    out.push_str("    addressed = urlsplit(base_url).hostname or \"\"\n");
    out.push_str("    if addressed != trust.server_name:\n");
    out.push_str("        raise ValueError(\n");
    out.push_str(
        "            f\"this client would verify {trust.server_name} while addressing \"\n",
    );
    out.push_str(
        "            f\"{addressed}; point the base URL at the name the certificate asserts\"\n",
    );
    out.push_str("        )\n");
    out.push_str(
        "    # Naming a cafile makes this the *only* trust anchor: create_default_context\n",
    );
    out.push_str("    # loads the system store only when no explicit one is given.\n");
    out.push_str("    context = ssl.create_default_context(cafile=trust.ca_bundle)\n");
    out.push_str("    context.check_hostname = True\n");
    out.push_str("    context.verify_mode = ssl.CERT_REQUIRED\n");
    out.push_str("    return context\n\n\n");
    out.push_str("class ResponseLike(Protocol):\n");
    out.push_str("    def raise_for_status(self) -> None: ...\n");
    out.push_str("    def json(self) -> Any: ...\n\n\n");
    out.push_str("class SupportsRequest(Protocol):\n");
    out.push_str(&format!(
        "    def request(self, method: str, url: str, *, params: dict[str, Any], headers: dict[str, Any], json: Any = None, data: Any = None, content: Any = None, timeout: {} = None) -> ResponseLike: ...\n\n\n",
        pymap::optional("float", target),
    ));
    out.push_str("class AsyncSupportsRequest(Protocol):\n");
    out.push_str(&format!(
        "    async def request(self, method: str, url: str, *, params: dict[str, Any], headers: dict[str, Any], json: Any = None, data: Any = None, content: Any = None, timeout: {} = None) -> ResponseLike: ...\n\n\n",
        pymap::optional("float", target),
    ));

    out.push_str("class Client:\n");
    out.push_str(&format!(
        "    def __init__(self, base_url: str, *, client: {} = None, default_headers: {} = None, auth_token: {} = None, trust: {} = None, use_post_fallback: bool = False) -> None:\n",
        pymap::optional("SupportsRequest", target),
        pymap::optional("Mapping[str, Any]", target),
        pymap::optional("str", target),
        pymap::optional("PrivateTrust", target),
    ));
    out.push_str("        self._base_url = base_url.rstrip(\"/\")\n");
    out.push_str("        if trust is None:\n");
    out.push_str("            ssl_context = None\n");
    out.push_str("        elif client is not None:\n");
    out.push_str(
        "            # An injected transport carries its own TLS configuration; silently\n",
    );
    out.push_str("            # ignoring `trust` here would leave the caller believing they had\n");
    out.push_str("            # pinned an anchor that nothing consults.\n");
    out.push_str("            raise ValueError(\n");
    out.push_str("                \"pass trust to the injected client instead; this one cannot configure it\"\n");
    out.push_str("            )\n");
    out.push_str("        else:\n");
    out.push_str("            ssl_context = _private_trust_context(trust, self._base_url)\n");
    out.push_str("        self._client = client or H2CClient(ssl_context=ssl_context)\n");
    out.push_str("        self._default_headers: dict[str, Any] = dict(default_headers or {})\n");
    out.push_str("        # Epic #1296 POST-twin fallback: route QUERY operations through their\n");
    out.push_str("        # documented POST twin instead of the HTTP QUERY method (RFC 10008).\n");
    out.push_str("        self._use_post_fallback = use_post_fallback\n");
    out.push_str("        if auth_token is not None:\n");
    out.push_str(
        "            self._default_headers[\"Authorization\"] = f\"Bearer {auth_token}\"\n",
    );
    out.push_str("\n");
    if target.is_some() {
        out.push_str("    def __enter__(self) -> Self:\n");
    } else {
        out.push_str("    def __enter__(self) -> \"Client\":\n");
    }
    out.push_str("        return self\n");
    out.push_str("\n");
    out.push_str("    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None:\n");
    out.push_str("        self.close()\n");
    out.push_str("\n");
    out.push_str("    def close(self) -> None:\n");
    out.push_str("        close = getattr(self._client, \"close\", None)\n");
    out.push_str("        if close is not None:\n");
    out.push_str("            close()\n");

    let mut reg = NameRegistry::new();
    reg.unique("__init__");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(
            ir,
            tm,
            &mut reg,
            false,
            target,
            auth.is_some(),
        ));
    }

    out.push_str("\n\nclass AsyncClient:\n");
    out.push_str(&format!(
        "    def __init__(self, base_url: str, *, client: {} = None, default_headers: {} = None, auth_token: {} = None, trust: {} = None, use_post_fallback: bool = False) -> None:\n",
        pymap::optional("AsyncSupportsRequest", target),
        pymap::optional("Mapping[str, Any]", target),
        pymap::optional("str", target),
        pymap::optional("PrivateTrust", target),
    ));
    out.push_str("        self._base_url = base_url.rstrip(\"/\")\n");
    out.push_str("        if trust is None:\n");
    out.push_str("            ssl_context = None\n");
    out.push_str("        elif client is not None:\n");
    out.push_str(
        "            # An injected transport carries its own TLS configuration; silently\n",
    );
    out.push_str("            # ignoring `trust` here would leave the caller believing they had\n");
    out.push_str("            # pinned an anchor that nothing consults.\n");
    out.push_str("            raise ValueError(\n");
    out.push_str("                \"pass trust to the injected client instead; this one cannot configure it\"\n");
    out.push_str("            )\n");
    out.push_str("        else:\n");
    out.push_str("            ssl_context = _private_trust_context(trust, self._base_url)\n");
    out.push_str("        self._client = client or AsyncH2CClient(ssl_context=ssl_context)\n");
    out.push_str("        self._default_headers: dict[str, Any] = dict(default_headers or {})\n");
    out.push_str("        # Epic #1296 POST-twin fallback: route QUERY operations through their\n");
    out.push_str("        # documented POST twin instead of the HTTP QUERY method (RFC 10008).\n");
    out.push_str("        self._use_post_fallback = use_post_fallback\n");
    out.push_str("        if auth_token is not None:\n");
    out.push_str(
        "            self._default_headers[\"Authorization\"] = f\"Bearer {auth_token}\"\n",
    );
    out.push_str("\n");
    if target.is_some() {
        out.push_str("    async def __aenter__(self) -> Self:\n");
    } else {
        out.push_str("    async def __aenter__(self) -> \"AsyncClient\":\n");
    }
    out.push_str("        return self\n");
    out.push_str("\n");
    out.push_str("    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None:\n");
    out.push_str("        await self.aclose()\n");
    out.push_str("\n");
    out.push_str("    async def aclose(self) -> None:\n");
    out.push_str("        close = getattr(self._client, \"aclose\", None) or getattr(self._client, \"close\", None)\n");
    out.push_str("        if close is not None:\n");
    out.push_str("            result = close()\n");
    out.push_str("            if hasattr(result, \"__await__\"):\n");
    out.push_str("                await result\n");
    out.push_str("\n");
    out.push_str("    async def close(self) -> None:\n");
    out.push_str("        await self.aclose()\n");
    let mut async_reg = NameRegistry::new();
    async_reg.unique("__init__");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(
            ir,
            tm,
            &mut async_reg,
            true,
            target,
            auth.is_some(),
        ));
    }
    out
}
