//! Emit the generated Python HTTP/2 runtime.

use crate::domain::PythonTarget;

pub const HEADER: &str = "# Code generated by openapi-codegen. DO NOT EDIT.\n";

const RUNTIME: &str = include_str!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/assets/py/h2c_runtime.py"
));

pub fn emit(target: Option<PythonTarget>) -> String {
    let mut out = String::from(HEADER);
    match target {
        Some(target) => out.push_str(&modernize_annotations(RUNTIME, target)),
        None => out.push_str(RUNTIME),
    }
    out
}

/// Every supported Python target is at least 3.11. Convert the legacy
/// `Optional[T]` spelling in the large handwritten runtime mechanically so it
/// remains consistent with the profile-aware model and client emitters.
fn modernize_annotations(source: &str, _target: PythonTarget) -> String {
    let mut modern = source.replace(
        "from typing import Any, AsyncIterator, Iterable, Iterator, Mapping, Optional",
        "from typing import Any, AsyncIterator, Iterable, Iterator, Mapping, Self",
    );
    modern = replace_optional_annotations(&modern);
    for (legacy, replacement) in [
        (
            "def __enter__(self) -> \"H2CClient\":",
            "def __enter__(self) -> Self:",
        ),
        (
            "def __enter__(self) -> \"H2CStream\":",
            "def __enter__(self) -> Self:",
        ),
        (
            "async def __aenter__(self) -> \"AsyncH2CStream\":",
            "async def __aenter__(self) -> Self:",
        ),
        (
            "async def _open(self) -> \"AsyncH2CStream\":",
            "async def _open(self) -> Self:",
        ),
        (
            "async def __aenter__(self) -> \"AsyncH2CClient\":",
            "async def __aenter__(self) -> Self:",
        ),
    ] {
        modern = modern.replace(legacy, replacement);
    }
    modern
}

/// Replace balanced `Optional[...]` type expressions without touching other
/// nested generic brackets. Runtime annotations may contain mappings, tuples,
/// and callable signatures, so a flat string replacement is insufficient.
fn replace_optional_annotations(source: &str) -> String {
    let mut out = String::with_capacity(source.len());
    let mut cursor = 0;
    while let Some(offset) = source[cursor..].find("Optional[") {
        let start = cursor + offset;
        out.push_str(&source[cursor..start]);
        let content_start = start + "Optional[".len();
        let mut depth = 1_u32;
        let mut end = content_start;
        for (offset, ch) in source[content_start..].char_indices() {
            match ch {
                '[' => depth += 1,
                ']' => {
                    depth -= 1;
                    if depth == 0 {
                        end = content_start + offset;
                        break;
                    }
                }
                _ => {}
            }
        }
        if depth != 0 {
            out.push_str("Optional[");
            cursor = content_start;
            continue;
        }
        out.push_str(&replace_optional_annotations(&source[content_start..end]));
        out.push_str(" | None");
        cursor = end + 1;
    }
    out.push_str(&source[cursor..]);
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn python_311_runtime_uses_modern_optional_and_self_annotations() {
        let runtime = emit(Some(PythonTarget::Py311));
        assert!(runtime
            .contains("from typing import Any, AsyncIterator, Iterable, Iterator, Mapping, Self"));
        assert!(runtime.contains("concurrency: int, parallelism: int | None = None"));
        assert!(runtime.contains("def __enter__(self) -> Self:"));
        assert!(!runtime.contains("Optional["));
    }
}
