use super::{DataDependencies, Definition, Use};
use crate::domain::semantic::pdg::cfg::{BlockId, ControlFlowGraph, StatementInfo};
use crate::domain::syntax::parsed_file::ParsedFile;
use std::collections::{HashMap, HashSet, VecDeque};

/// Data flow analyzer
pub(super) struct DataFlowAnalyzer<'a> {
    cfg: &'a ControlFlowGraph,
    _file: &'a ParsedFile,
    /// Definitions generated by each block
    gen: HashMap<BlockId, HashSet<Definition>>,
    /// Definitions killed by each block
    kill: HashMap<BlockId, HashSet<Definition>>,
    /// All definitions by variable name
    all_defs: HashMap<String, Vec<Definition>>,
    /// Uses in each block
    uses_in_block: HashMap<BlockId, Vec<Use>>,
}

impl<'a> DataFlowAnalyzer<'a> {
    pub(super) fn new(cfg: &'a ControlFlowGraph, file: &'a ParsedFile) -> Self {
        Self {
            cfg,
            _file: file,
            gen: HashMap::new(),
            kill: HashMap::new(),
            all_defs: HashMap::new(),
            uses_in_block: HashMap::new(),
        }
    }

    pub(super) fn analyze(mut self) -> DataDependencies {
        // Phase 1: Extract definitions and uses from each block
        self.extract_defs_uses();

        // Phase 2: Compute gen and kill sets
        self.compute_gen_kill();

        // Phase 3: Compute reaching definitions
        let (reaching_in, reaching_out) = self.compute_reaching_definitions();

        // Phase 4: Build def-use and use-def chains
        let (def_use, use_def) = self.build_chains(&reaching_in);

        // Build name indices
        let mut defs_by_name: HashMap<String, Vec<Definition>> = HashMap::new();
        let mut uses_by_name: HashMap<String, Vec<Use>> = HashMap::new();

        for def in def_use.keys() {
            defs_by_name
                .entry(def.name.clone())
                .or_default()
                .push(def.clone());
        }

        for u in use_def.keys() {
            uses_by_name
                .entry(u.name.clone())
                .or_default()
                .push(u.clone());
        }

        DataDependencies {
            def_use,
            use_def,
            defs_by_name,
            uses_by_name,
            reaching_in,
            reaching_out,
        }
    }

    /// Extract definitions and uses from AST
    fn extract_defs_uses(&mut self) {
        for (&block_id, block) in &self.cfg.blocks {
            let mut block_defs = HashSet::new();
            let mut block_uses = Vec::new();

            for (stmt_index, stmt) in block.statements.iter().enumerate() {
                // Parse the statement to find definitions and uses
                let (defs, uses) = self.extract_from_statement(stmt, block_id, stmt_index);

                for def in defs {
                    self.all_defs
                        .entry(def.name.clone())
                        .or_default()
                        .push(def.clone());
                    block_defs.insert(def);
                }

                block_uses.extend(uses);
            }

            self.gen.insert(block_id, block_defs);
            self.uses_in_block.insert(block_id, block_uses);
        }
    }

    /// Extract definitions and uses from a single statement
    fn extract_from_statement(
        &self,
        stmt: &StatementInfo,
        block: BlockId,
        stmt_index: usize,
    ) -> (Vec<Definition>, Vec<Use>) {
        let mut defs = Vec::new();
        let mut uses = Vec::new();

        // Parse the statement text to extract variable names
        // This is a simplified approach - for full accuracy, we'd parse the AST
        let text = &stmt.text;

        // For assignments, extract LHS as definition and RHS as uses
        if text.contains('=') && !text.contains("==") {
            let parts: Vec<&str> = text.splitn(2, '=').collect();
            if parts.len() == 2 {
                // LHS: definition
                let lhs = parts[0].trim();
                if let Some(name) = Self::extract_simple_name(lhs) {
                    defs.push(Definition {
                        name: name.to_string(),
                        span: stmt.span,
                        line: stmt.line,
                        block,
                        stmt_index,
                    });
                }

                // RHS: uses
                let rhs = parts[1].trim();
                for name in Self::extract_identifiers(rhs) {
                    uses.push(Use {
                        name,
                        span: stmt.span,
                        line: stmt.line,
                        block,
                        stmt_index,
                    });
                }
            }
        } else {
            // For other statements, all identifiers are uses
            for name in Self::extract_identifiers(text) {
                uses.push(Use {
                    name,
                    span: stmt.span,
                    line: stmt.line,
                    block,
                    stmt_index,
                });
            }
        }

        (defs, uses)
    }

    /// Extract a simple variable name (no subscripts, attributes, etc.)
    fn extract_simple_name(text: &str) -> Option<&str> {
        let text = text.trim();
        // Skip if it contains brackets, dots, etc.
        if text.contains('[') || text.contains('.') || text.contains('(') {
            return None;
        }
        // Check if it's a valid identifier
        if text.chars().all(|c| c.is_alphanumeric() || c == '_') && !text.is_empty() {
            if !text.chars().next().unwrap().is_numeric() {
                return Some(text);
            }
        }
        None
    }

    /// Extract all identifiers from an expression
    fn extract_identifiers(text: &str) -> Vec<String> {
        let mut identifiers = Vec::new();
        let mut current = String::new();

        for c in text.chars() {
            if c.is_alphanumeric() || c == '_' {
                current.push(c);
            } else {
                if !current.is_empty() {
                    // Check if it's a valid identifier (not a number, not a keyword)
                    if !current.chars().next().unwrap().is_numeric() {
                        if !Self::is_keyword(&current) {
                            identifiers.push(current.clone());
                        }
                    }
                    current.clear();
                }
            }
        }

        if !current.is_empty() && !current.chars().next().unwrap().is_numeric() {
            if !Self::is_keyword(&current) {
                identifiers.push(current);
            }
        }

        identifiers
    }

    /// Check if a word is a Python keyword
    fn is_keyword(word: &str) -> bool {
        matches!(
            word,
            "and"
                | "as"
                | "assert"
                | "async"
                | "await"
                | "break"
                | "class"
                | "continue"
                | "def"
                | "del"
                | "elif"
                | "else"
                | "except"
                | "finally"
                | "for"
                | "from"
                | "global"
                | "if"
                | "import"
                | "in"
                | "is"
                | "lambda"
                | "None"
                | "nonlocal"
                | "not"
                | "or"
                | "pass"
                | "raise"
                | "return"
                | "True"
                | "False"
                | "try"
                | "while"
                | "with"
                | "yield"
        )
    }

    /// Compute gen and kill sets for each block
    fn compute_gen_kill(&mut self) {
        // Kill: for each definition of variable V in block B,
        // kill all other definitions of V
        for (&block_id, defs) in &self.gen {
            let mut kill_set = HashSet::new();

            for def in defs {
                // Kill all other definitions of this variable
                if let Some(all_var_defs) = self.all_defs.get(&def.name) {
                    for other_def in all_var_defs {
                        if other_def != def {
                            kill_set.insert(other_def.clone());
                        }
                    }
                }
            }

            self.kill.insert(block_id, kill_set);
        }
    }

    /// Compute reaching definitions using iterative data flow analysis
    fn compute_reaching_definitions(
        &self,
    ) -> (
        HashMap<BlockId, HashSet<Definition>>,
        HashMap<BlockId, HashSet<Definition>>,
    ) {
        let mut reaching_in: HashMap<BlockId, HashSet<Definition>> = HashMap::new();
        let mut reaching_out: HashMap<BlockId, HashSet<Definition>> = HashMap::new();

        // Initialize
        for block_id in self.cfg.block_ids() {
            reaching_in.insert(block_id, HashSet::new());
            reaching_out.insert(block_id, HashSet::new());
        }

        // Worklist algorithm
        let mut worklist: VecDeque<BlockId> = self.cfg.block_ids().into_iter().collect();

        while let Some(block_id) = worklist.pop_front() {
            // IN[B] = union of OUT[P] for all predecessors P
            let mut new_in = HashSet::new();
            for pred in self.cfg.get_predecessors(block_id) {
                if let Some(pred_out) = reaching_out.get(&pred) {
                    new_in.extend(pred_out.iter().cloned());
                }
            }

            // OUT[B] = GEN[B] union (IN[B] - KILL[B])
            let gen = self.gen.get(&block_id).cloned().unwrap_or_default();
            let kill = self.kill.get(&block_id).cloned().unwrap_or_default();

            let mut new_out = gen;
            for def in &new_in {
                if !kill.contains(def) {
                    new_out.insert(def.clone());
                }
            }

            // Check if OUT changed
            let old_out = reaching_out.get(&block_id).cloned().unwrap_or_default();
            if new_out != old_out {
                reaching_out.insert(block_id, new_out);
                reaching_in.insert(block_id, new_in);

                // Add successors to worklist
                for succ in self.cfg.get_successors(block_id) {
                    if !worklist.contains(&succ) {
                        worklist.push_back(succ);
                    }
                }
            } else {
                reaching_in.insert(block_id, new_in);
            }
        }

        (reaching_in, reaching_out)
    }

    /// Build def-use and use-def chains from reaching definitions
    fn build_chains(
        &self,
        reaching_in: &HashMap<BlockId, HashSet<Definition>>,
    ) -> (HashMap<Definition, Vec<Use>>, HashMap<Use, Vec<Definition>>) {
        let mut def_use: HashMap<Definition, Vec<Use>> = HashMap::new();
        let mut use_def: HashMap<Use, Vec<Definition>> = HashMap::new();

        for (&block_id, uses) in &self.uses_in_block {
            // Get reaching definitions at block entry
            let reaching = reaching_in.get(&block_id).cloned().unwrap_or_default();

            // Also include definitions within this block (for uses after defs)
            let mut local_defs: HashMap<String, Definition> = HashMap::new();

            if let Some(block) = self.cfg.get_block(block_id) {
                for (stmt_index, _stmt) in block.statements.iter().enumerate() {
                    // Process uses in this statement
                    for u in uses.iter().filter(|u| u.stmt_index == stmt_index) {
                        let mut reaching_defs = Vec::new();

                        // Check local definitions first
                        if let Some(local_def) = local_defs.get(&u.name) {
                            reaching_defs.push(local_def.clone());
                        } else {
                            // Check reaching definitions from predecessors
                            for def in &reaching {
                                if def.name == u.name {
                                    reaching_defs.push(def.clone());
                                }
                            }
                        }

                        // Update chains
                        for def in &reaching_defs {
                            def_use.entry(def.clone()).or_default().push(u.clone());
                        }
                        use_def.insert(u.clone(), reaching_defs);
                    }

                    // Update local definitions after processing uses
                    if let Some(gen) = self.gen.get(&block_id) {
                        for def in gen {
                            if def.stmt_index == stmt_index {
                                local_defs.insert(def.name.clone(), def.clone());
                            }
                        }
                    }
                }
            }
        }

        (def_use, use_def)
    }
}
