use super::literal::rust_literal;
use super::method::emit_method;
use crate::domain::ir::names::NameRegistry;
use crate::domain::ir::operations::OperationIR;
use crate::domain::ir::typemap::TypeMap;
use crate::domain::FileBearerAuth;

pub const HEADER: &str = "// Code generated by openapi-codegen. DO NOT EDIT.\n";

pub fn emit(ops: &[OperationIR], tm: &TypeMap, auth: Option<&FileBearerAuth>) -> String {
    let mut out = String::from(HEADER);
    out.push_str("use crate::models::*;\n\n");
    out.push_str("use std::fmt;\n");
    out.push_str("use std::sync::{Arc, Condvar, Mutex};\n");
    out.push_str("use std::time::{Duration, Instant};\n\n");
    if let Some(auth) = auth {
        out.push_str(&format!(
            "const FILE_BEARER_TOKEN_PATH: &str = {};\n",
            rust_literal(
                auth.token_path()
                    .to_str()
                    .expect("FileBearerAuth validates UTF-8 paths")
            )
        ));
        out.push_str(&format!(
            "const FILE_BEARER_HOSTNAME_SUFFIX: &str = {};\n",
            rust_literal(auth.hostname_suffix())
        ));
        let schemes = auth
            .schemes()
            .map(|scheme| rust_literal(scheme.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!(
            "const FILE_BEARER_SCHEMES: &[&str] = &[{schemes}];\n\n"
        ));
    }
    out.push_str("const DEFAULT_MAX_CONNECTIONS: usize = 128;\n");
    out.push_str("const DEFAULT_MAX_KEEPALIVE_CONNECTIONS: usize = 16;\n");
    out.push_str("const DEFAULT_KEEPALIVE_EXPIRY: Duration = Duration::from_secs(5);\n");
    out.push_str("const DEFAULT_POOL_TIMEOUT: Duration = Duration::from_secs(5);\n\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub struct TransportPolicy {\n");
    out.push_str("    pub target_concurrency: usize,\n");
    out.push_str("    pub max_connections: usize,\n");
    out.push_str("    pub max_in_flight_per_origin: usize,\n");
    out.push_str("    pub max_keepalive_connections: usize,\n");
    out.push_str("    pub keepalive_expiry: Duration,\n");
    out.push_str("    pub pool_timeout: Duration,\n");
    out.push_str("}\n\n");
    out.push_str("impl Default for TransportPolicy {\n");
    out.push_str("    fn default() -> Self {\n");
    out.push_str("        Self {\n");
    out.push_str("            target_concurrency: DEFAULT_MAX_CONNECTIONS,\n");
    out.push_str("            max_connections: DEFAULT_MAX_CONNECTIONS,\n");
    out.push_str("            max_in_flight_per_origin: DEFAULT_MAX_CONNECTIONS,\n");
    out.push_str("            max_keepalive_connections: DEFAULT_MAX_KEEPALIVE_CONNECTIONS,\n");
    out.push_str("            keepalive_expiry: DEFAULT_KEEPALIVE_EXPIRY,\n");
    out.push_str("            pool_timeout: DEFAULT_POOL_TIMEOUT,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str(
        "pub fn recommended_h2_connections(concurrency: usize, parallelism: usize) -> usize {\n",
    );
    out.push_str("    let cap = parallelism.max(1);\n");
    out.push_str("    if concurrency <= 2 { return 1; }\n");
    out.push_str("    ((concurrency as f64).ln().ceil() as usize).clamp(1, cap)\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug)]\n");
    out.push_str("pub enum ClientError {\n");
    out.push_str("    Http(reqwest::Error),\n");
    out.push_str("    PoolTimeout(Duration),\n");
    out.push_str("    /// The private trust anchor could not be used as configured.\n");
    out.push_str("    Trust(String),\n");
    if auth.is_some() {
        out.push_str("    /// A request header could not be represented safely.\n");
        out.push_str("    RequestHeader,\n");
        out.push_str("    /// The per-request bearer credential was unavailable or invalid.\n");
        out.push_str("    RequestAuth,\n");
    }
    out.push_str("}\n\n");
    out.push_str("impl From<reqwest::Error> for ClientError {\n");
    out.push_str("    fn from(value: reqwest::Error) -> Self { Self::Http(value) }\n");
    out.push_str("}\n\n");
    out.push_str("impl fmt::Display for ClientError {\n");
    out.push_str("    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {\n");
    out.push_str("        match self {\n");
    out.push_str("            Self::Http(err) => write!(f, \"{err}\"),\n");
    out.push_str("            Self::PoolTimeout(timeout) => write!(f, \"pool timeout after {timeout:?}\"),\n");
    out.push_str("            Self::Trust(why) => write!(f, \"{why}\"),\n");
    if auth.is_some() {
        out.push_str(
            "            Self::RequestHeader => f.write_str(\"request header is invalid\"),\n",
        );
        out.push_str("            Self::RequestAuth => f.write_str(\"request authentication token is unavailable or invalid\"),\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for ClientError {\n");
    out.push_str("    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {\n");
    out.push_str("        match self {\n");
    out.push_str("            Self::Http(err) => Some(err),\n");
    out.push_str("            Self::PoolTimeout(_) => None,\n");
    out.push_str("            Self::Trust(_) => None,\n");
    if auth.is_some() {
        out.push_str("            Self::RequestHeader | Self::RequestAuth => None,\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("pub type ClientResult<T> = std::result::Result<T, ClientError>;\n\n");
    out.push_str("/// Verify the server against a private CA instead of the public roots.\n");
    out.push_str("///\n");
    out.push_str("/// For a service published only inside a cluster, the public roots cannot\n");
    out.push_str("/// vouch for it and should not be consulted: a private trust domain that is\n");
    out.push_str("/// merely *added* to the public set still lets any public CA certify this\n");
    out.push_str("/// name. `with_private_ca` therefore replaces the root store rather than\n");
    out.push_str("/// extending it.\n");
    out.push_str("///\n");
    out.push_str("/// There is no option to skip verification. If the server cannot be\n");
    out.push_str("/// verified, the fix is the anchor or the name -- not the check.\n");
    out.push_str("#[derive(Debug, Clone)]\n");
    out.push_str("pub struct PrivateTrust {\n");
    out.push_str("    /// PEM bundle holding the CA that signed the server's leaf.\n");
    out.push_str("    pub ca_bundle: std::path::PathBuf,\n");
    out.push_str("    /// The DNS name the leaf must assert. The base URL has to address this\n");
    out.push_str("    /// same name: a client that verified one name while addressing another\n");
    out.push_str("    /// would be checking a certificate it never actually relies on.\n");
    out.push_str("    pub server_name: String,\n");
    out.push_str("}\n\n");
    out.push_str("/// The host a base URL actually connects to, with scheme, port, and path\n");
    out.push_str("/// removed -- the string TLS will check the certificate against.\n");
    out.push_str("fn addressed_host(base_url: &str) -> &str {\n");
    out.push_str(
        "    let after_scheme = base_url.split_once(\"://\").map_or(base_url, |(_, rest)| rest);\n",
    );
    out.push_str(
        "    let authority = after_scheme.split(['/', '?', '#']).next().unwrap_or(\"\");\n",
    );
    out.push_str(
        "    let authority = authority.rsplit_once('@').map_or(authority, |(_, host)| host);\n",
    );
    out.push_str("    if let Some(rest) = authority.strip_prefix('[') {\n");
    out.push_str(
        "        // A bracketed IPv6 literal: the colons inside are part of the address.\n",
    );
    out.push_str("        return rest.split_once(']').map_or(rest, |(host, _)| host);\n");
    out.push_str("    }\n");
    out.push_str("    authority.rsplit_once(':').map_or(authority, |(host, _)| host)\n");
    out.push_str("}\n\n");
    if auth.is_some() {
        out.push_str("fn file_bearer_dns_hostname_is_valid(host: &str) -> bool {\n");
        out.push_str("    if host.is_empty() || host.len() > 253 || host.ends_with('.') || host.parse::<std::net::IpAddr>().is_ok() { return false; }\n");
        out.push_str("    host.split('.').all(|label| {\n");
        out.push_str("        let bytes = label.as_bytes();\n");
        out.push_str("        !bytes.is_empty() && bytes.len() <= 63\n");
        out.push_str("            && bytes.first().is_some_and(u8::is_ascii_alphanumeric)\n");
        out.push_str("            && bytes.last().is_some_and(u8::is_ascii_alphanumeric)\n");
        out.push_str("            && bytes.iter().all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || *byte == b'-')\n");
        out.push_str("    })\n");
        out.push_str("}\n\n");
        out.push_str("fn file_bearer_target_is_eligible(base_url: &str) -> bool {\n");
        out.push_str("    let Ok(url) = reqwest::Url::parse(base_url) else { return false; };\n");
        out.push_str("    if !FILE_BEARER_SCHEMES.contains(&url.scheme()) { return false; }\n");
        out.push_str("    if !url.username().is_empty() || url.password().is_some() || base_url.contains('?') || base_url.contains('#') { return false; }\n");
        out.push_str("    if !matches!(url.path(), \"\" | \"/\") { return false; }\n");
        out.push_str("    let Some(host) = url.host_str() else { return false; };\n");
        out.push_str("    if !file_bearer_dns_hostname_is_valid(host) { return false; }\n");
        out.push_str("    host.strip_suffix(FILE_BEARER_HOSTNAME_SUFFIX)\n");
        out.push_str(
            "        .is_some_and(|prefix| !prefix.is_empty() && !prefix.ends_with('.'))\n",
        );
        out.push_str("}\n\n");
        out.push_str("fn insert_request_header(headers: &mut reqwest::header::HeaderMap, name: &str, value: &str) -> ClientResult<()> {\n");
        out.push_str("    use reqwest::header::{HeaderName, HeaderValue, AUTHORIZATION};\n");
        out.push_str("    let name = HeaderName::from_bytes(name.as_bytes()).map_err(|_| ClientError::RequestHeader)?;\n");
        out.push_str("    let mut value = HeaderValue::from_str(value).map_err(|_| ClientError::RequestHeader)?;\n");
        out.push_str("    if name == AUTHORIZATION { value.set_sensitive(true); }\n");
        out.push_str("    headers.insert(name, value);\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");
        out.push_str("fn attach_file_bearer(base_url: &str, headers: &mut reqwest::header::HeaderMap) -> ClientResult<()> {\n");
        out.push_str("    use reqwest::header::{HeaderValue, AUTHORIZATION};\n");
        out.push_str("    if headers.contains_key(AUTHORIZATION) || !file_bearer_target_is_eligible(base_url) { return Ok(()); }\n");
        out.push_str("    let raw = std::fs::read_to_string(FILE_BEARER_TOKEN_PATH).map_err(|_| ClientError::RequestAuth)?;\n");
        out.push_str("    let token = raw.trim();\n");
        out.push_str("    if token.is_empty() || !token.bytes().all(|byte| byte.is_ascii_graphic()) { return Err(ClientError::RequestAuth); }\n");
        out.push_str("    let mut value = HeaderValue::from_str(&format!(\"Bearer {token}\")).map_err(|_| ClientError::RequestAuth)?;\n");
        out.push_str("    value.set_sensitive(true);\n");
        out.push_str("    headers.insert(AUTHORIZATION, value);\n");
        out.push_str("    Ok(())\n");
        out.push_str("}\n\n");
    }
    out.push_str("#[derive(Default)]\n");
    out.push_str("struct AdmissionState { in_flight: usize }\n\n");
    out.push_str("struct SlotGuard { admission: Arc<(Mutex<AdmissionState>, Condvar)> }\n\n");
    out.push_str("impl Drop for SlotGuard {\n");
    out.push_str("    fn drop(&mut self) {\n");
    out.push_str("        let (lock, cv) = &*self.admission;\n");
    out.push_str("        let mut state = lock.lock().expect(\"admission lock poisoned\");\n");
    out.push_str("        state.in_flight = state.in_flight.saturating_sub(1);\n");
    out.push_str("        cv.notify_one();\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("pub struct Client {\n");
    out.push_str("    base_url: String,\n");
    out.push_str("    http: reqwest::blocking::Client,\n");
    out.push_str("    policy: TransportPolicy,\n");
    out.push_str("    admission: Arc<(Mutex<AdmissionState>, Condvar)>,\n");
    out.push_str("    /// Epic #1296 POST-twin fallback: when true, every generated `QUERY`\n");
    out.push_str(
        "    /// operation is sent as `POST` against its documented twin path instead of\n",
    );
    out.push_str("    /// the HTTP `QUERY` method (RFC 10008). Off by default.\n");
    out.push_str("    use_post_fallback: bool,\n");
    if auth.is_some() {
        out.push_str("    default_headers: reqwest::header::HeaderMap,\n");
    }
    out.push_str("}\n\n");
    out.push_str("impl Client {\n");
    out.push_str("    pub fn new(base_url: impl Into<String>) -> Self {\n");
    out.push_str("        Self::with_policy(base_url, TransportPolicy::default())\n");
    out.push_str("    }\n\n");
    out.push_str(
        "    pub fn with_policy(base_url: impl Into<String>, policy: TransportPolicy) -> Self {\n",
    );
    out.push_str("        let http = reqwest::blocking::Client::builder()\n");
    out.push_str("            .pool_max_idle_per_host(policy.max_keepalive_connections)\n");
    out.push_str("            .pool_idle_timeout(policy.keepalive_expiry)\n");
    out.push_str("            .build()\n");
    out.push_str("            .expect(\"generated client reqwest builder\");\n");
    out.push_str("        Self {\n");
    out.push_str("            base_url: base_url.into().trim_end_matches('/').to_string(),\n");
    out.push_str("            http,\n");
    out.push_str("            policy,\n");
    out.push_str("            admission: Arc::new((Mutex::new(AdmissionState::default()), Condvar::new())),\n");
    out.push_str("            use_post_fallback: false,\n");
    if auth.is_some() {
        out.push_str("            default_headers: reqwest::header::HeaderMap::new(),\n");
    }
    out.push_str("        }\n");
    out.push_str("    }\n\n");
    out.push_str("    /// Epic #1296 POST-twin fallback: route every `QUERY` operation through\n");
    out.push_str("    /// its documented POST twin instead of HTTP `QUERY`.\n");
    out.push_str("    pub fn with_post_fallback(mut self, use_post_fallback: bool) -> Self {\n");
    out.push_str("        self.use_post_fallback = use_post_fallback;\n");
    out.push_str("        self\n");
    out.push_str("    }\n");
    if auth.is_some() {
        out.push_str(
            "\n    /// Add one explicit default header. An explicit Authorization header\n",
        );
        out.push_str("    /// always wins and prevents the token file from being read.\n");
        out.push_str("    pub fn with_default_header(mut self, name: &str, value: &str) -> ClientResult<Self> {\n");
        out.push_str("        use reqwest::header::{HeaderName, HeaderValue, AUTHORIZATION};\n");
        out.push_str("        let name = HeaderName::from_bytes(name.as_bytes()).map_err(|_| ClientError::RequestHeader)?;\n");
        out.push_str("        let mut value = HeaderValue::from_str(value).map_err(|_| ClientError::RequestHeader)?;\n");
        out.push_str("        if name == AUTHORIZATION { value.set_sensitive(true); }\n");
        out.push_str("        self.default_headers.insert(name, value);\n");
        out.push_str("        Ok(self)\n");
        out.push_str("    }\n");
    }
    out.push_str("\n    /// The same client, verifying the server against a private CA.\n");
    out.push_str("    ///\n");
    out.push_str("    /// Fails rather than falls back: an unreadable bundle, a bundle holding\n");
    out.push_str("    /// no certificate, or a base URL addressing a different host than the\n");
    out.push_str("    /// one being verified are all configuration errors, and a client that\n");
    out.push_str("    /// quietly kept the public roots in any of those cases would verify\n");
    out.push_str("    /// something other than what the caller asked for.\n");
    out.push_str("    pub fn with_private_ca(base_url: impl Into<String>, policy: TransportPolicy, trust: PrivateTrust) -> ClientResult<Self> {\n");
    out.push_str("        let base_url = base_url.into().trim_end_matches('/').to_string();\n");
    out.push_str("        let addressed = addressed_host(&base_url);\n");
    out.push_str("        if addressed != trust.server_name {\n");
    out.push_str("            return Err(ClientError::Trust(format!(\n");
    out.push_str("                \"this client would verify {} while addressing {addressed}; point the base URL at the name the certificate asserts\",\n");
    out.push_str("                trust.server_name,\n");
    out.push_str("            )));\n");
    out.push_str("        }\n");
    out.push_str("        let pem = std::fs::read(&trust.ca_bundle).map_err(|err| {\n");
    out.push_str("            ClientError::Trust(format!(\"read the trust bundle {}: {err}\", trust.ca_bundle.display()))\n");
    out.push_str("        })?;\n");
    out.push_str("        let anchor = reqwest::Certificate::from_pem(&pem).map_err(|err| {\n");
    out.push_str("            ClientError::Trust(format!(\"{} is not a PEM certificate: {err}\", trust.ca_bundle.display()))\n");
    out.push_str("        })?;\n");
    out.push_str("        let http = reqwest::blocking::Client::builder()\n");
    out.push_str("            .pool_max_idle_per_host(policy.max_keepalive_connections)\n");
    out.push_str("            .pool_idle_timeout(policy.keepalive_expiry)\n");
    out.push_str("            .tls_built_in_root_certs(false)\n");
    out.push_str("            .add_root_certificate(anchor)\n");
    out.push_str("            .build()?;\n");
    out.push_str("        Ok(Self {\n");
    out.push_str("            base_url,\n");
    out.push_str("            http,\n");
    out.push_str("            policy,\n");
    out.push_str("            admission: Arc::new((Mutex::new(AdmissionState::default()), Condvar::new())),\n");
    out.push_str("            use_post_fallback: false,\n");
    if auth.is_some() {
        out.push_str("            default_headers: reqwest::header::HeaderMap::new(),\n");
    }
    out.push_str("        })\n");
    out.push_str("    }\n");
    out.push_str("\n    fn acquire_slot(&self) -> ClientResult<SlotGuard> {\n");
    out.push_str("        let max = self.policy.max_in_flight_per_origin.max(1);\n");
    out.push_str("        let deadline = Instant::now() + self.policy.pool_timeout;\n");
    out.push_str("        let (lock, cv) = &*self.admission;\n");
    out.push_str("        let mut state = lock.lock().expect(\"admission lock poisoned\");\n");
    out.push_str("        while state.in_flight >= max {\n");
    out.push_str("            let now = Instant::now();\n");
    out.push_str("            if now >= deadline { return Err(ClientError::PoolTimeout(self.policy.pool_timeout)); }\n");
    out.push_str("            let wait = deadline.saturating_duration_since(now);\n");
    out.push_str("            let (next, timeout) = cv.wait_timeout(state, wait).expect(\"admission lock poisoned\");\n");
    out.push_str("            state = next;\n");
    out.push_str("            if timeout.timed_out() && state.in_flight >= max { return Err(ClientError::PoolTimeout(self.policy.pool_timeout)); }\n");
    out.push_str("        }\n");
    out.push_str("        state.in_flight += 1;\n");
    out.push_str("        Ok(SlotGuard { admission: Arc::clone(&self.admission) })\n");
    out.push_str("    }\n");

    let mut reg = NameRegistry::new();
    reg.unique("new");
    for ir in ops {
        out.push('\n');
        out.push_str(&emit_method(ir, tm, &mut reg, auth.is_some()));
    }
    out.push_str("}\n");
    out
}
